.circleci/config.yml, README.md, cucumber/features/devLoginPup.feature, cucumber/features/steps/devLoginPupSteps.js, cucumber/features/steps/hooks.js, cucumber/features/support/scope.js, cucumber/features/world.js, cucumber/index.js, docker-compose-test.yml, docs/adr/0009-security-scans.md, frontend/run-yarn-audit.sh, package.json, run-yarn-audit.sh, yarn.lock
This PR covers the initial setup of cucumberJS. Before getting to deep into writing a lot of tests, we want to make sure the approach here is approved.
More information on how to test can be found here
https://github.com/adhocteam/Head-Start-TTADP/pull/43
**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/43
**Checklist**
- API methods
- Boundary and Data Flow Diagrams
- [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
- OSCAL templates completed when security controls are implemented or modified
=> Initial setup of cucumber (#43)

.circleci/config.yml
Run security scans weekday mornings.
N/A
**Issue(s)**
* #125 
**Checklist**
=> Reset daily_scan timing

frontend/src/components/DeleteReportModal.css, frontend/src/components/DeleteReportModal.js
Minor changes to match the delete dialog design. Screenshot attached.
Pull changes
Attempt to delete a report
Note that dialog matches the design:
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/138467436/simulate/no-panels
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-83
=> Adjust text  and style on Activity Report delete confirmation modal

frontend/src/components/DateRangePicker.js, frontend/src/components/SiteNav.js, frontend/src/widgets/TopicFrequencyGraph.css, frontend/src/widgets/TopicFrequencyGraph.js, frontend/src/widgets/TotalHrsAndGranteeGraph.css, src/widgets/overview.js
- The participant count as well as the total tta hours did not show the correct number when the "All regions" option was selected for the TTA Overview widget on the activity reports page. This PR fixes it.
- the topic/frequency graph had too much whitespace between the filters and the graph. The container wasn't staying static.
- Rename the link to the dashboard in the side navigation
- added an error message to the date range picker if a date isn't entered in the correct format, rather than silently correcting the date to the first available in the date range
- navigate to https://tta-smarthub-dev.app.cloud.gov/ 
(Note - Christine's new account in Dev is all set with permissions. Patrice's still needs to be set up - test.tta.patrice)
- verify that the "All regions" option shows the …
=> Fix incorrect participant count for all regions (#377) and dashboard visual fixes (#375)

README.md, frontend/src/widgets/AccessibleWidgetData.js, frontend/src/widgets/TotalHrsAndGranteeGraph.js, frontend/src/widgets/__tests__/TotalHrsAndGranteeGraph.js, src/widgets/totalHrsAndGranteeGraph.js
The table now has a horizontal scroll bar to handle large data sets.
Hours are rounded to one decimal place.
The language "hours" was removed from the individual cells and placed in the row heading.
Text was added to the dummy column
Tooltips now handle numbers with decimal a little bit better
View a large dataset with some oddball floats. Observe that the table will scroll and that any floats are rounded to one decimal place
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-280
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-281
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-282
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-283
- [n/a] [Architectural Decision Records](https://adr.github.io/) …
=>  [TTAHUB 280/281/282/283] Fixes for the accessible data view & line graph

frontend/src/components/CheckboxSelect.css, frontend/src/components/CheckboxSelect.js, frontend/src/widgets/TopicFrequencyGraph.js, frontend/src/widgets/__tests__/AccessibleWidgetData.js, frontend/src/widgets/__tests__/TopicFrequencyGraph.js
Add a table view for the topics bar graph.
Visit the dashboard. Check out the bar graph and click on the "View Accessible Data" link. Make sure the table data accurately reflects the data on the chart.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-220
=> [TTAHUB-220] Regional Dashboard: Add accessibility option for Topics Graph

frontend/src/App.js, frontend/src/components/SiteNav.js, src/routes/activityReports/handlers.js
Remove code preventing non-admins from viewing dashboard and from including goals and objectives in csv download.
Visit the /regional-dashboard as a non-admin. Export a CSV and note the presence of goals & objectives.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-277
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-294
=> [TTAHUB-294/277] remove feature flag from dashboard & including goals/objectives in csv downloads 

docs/openapi/paths/activity-reports/activity-reports-id.yaml, docs/openapi/paths/activity-reports/activity-reports.yaml, docs/openapi/paths/activity-reports/reset.yaml, docs/openapi/paths/activity-reports/review.yaml, docs/openapi/paths/activity-reports/submit.yaml, docs/openapi/paths/files.yaml, frontend/src/components/ButtonSelect.css, frontend/src/components/MultiSelect.js, frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalPicker.js, src/middleware/checkIdParamMiddleware.js, src/middleware/checkIdParamMiddleware.test.js, src/routes/activityReports/handlers.js, src/routes/activityReports/handlers.test.js, src/routes/activityReports/index.js, src/routes/files/handlers.js, src/routes/files/index.js, src/services/activityReports.js, src/services/activityReports.test.js
- Goals are now created and selected on the same control.
- Legacy CSVs are now available on the export for all users.
- API parameters are now checked for validity on the backend and the error handling made more explicit.
- Create an activity report. You can now type and create goals directly in the goals select, as well as pick from existing goals.
- Verify that CSV downloads work
- Verify that they can include legacy reports
- Verify that the warning appears and doesn't interfere with CSV formatting
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-296
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-343
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major …
=> [TTAHUB-296/343] Change design for goal selection, remove feature flags for legacy reports on CSV export

frontend/src/pages/ActivityReport/Pages/components/GoalInput.js, frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalPicker.js
The improved goal picker design made it to production without updated help text. To resolve confusion, "Select goal(s)" has been replaced with "Select goal(s) or type here to create a new goal" in two places.
View the goal picker and note the updated labelling
- [n/a ] Meets issue criteria
=> improve goal picker labeling

.circleci/config.yml, frontend/src/widgets/BarGraph.js
Plotly was causing OOMs when building.
Build passes and deploys to dev
=> Fix plotly import

frontend/src/App.css, frontend/src/components/ActivityReportsTable/index.js, frontend/src/pages/ActivityReport/constants.js, frontend/src/pages/ApprovedActivityReport/components/ViewTable.css, frontend/src/pages/ApprovedActivityReport/components/ViewTable.js, frontend/src/pages/GranteeRecord/components/GrantsList.css, frontend/src/pages/GranteeRecord/index.css, frontend/src/pages/GranteeSearch/index.css, frontend/src/pages/Landing/index.css, frontend/src/widgets/AccessibleWidgetData.css, frontend/src/widgets/AccessibleWidgetData.js, frontend/src/widgets/TableWidget.css, frontend/src/widgets/TableWidget.js, src/constants.js, src/widgets/helpers.js, src/widgets/reasonList.js, src/widgets/targetPopulationTable.js
Missed acceptance criteria that made it into prod (oops)
- Grant list on the Grantee profile page should have a background color
- The target population table should show populations even if they 0 as a count
View the Grantee record, both the profile and TTA history tabs and verify that these issues are resolved
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-462
=> Grantee record table bugs

bin/run-tests, frontend/src/pages/ApprovedActivityReport/index.css, frontend/src/pages/ApprovedActivityReport/index.js
Add the approved date and created date to the approved report view.
Refactor the way the page worked to see if it could load and render API data a little more quickly.
View an approved report and note that everything appears correct and that the new fields are present in the activity summary at the top.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-488
=> Add created data and approved date to approved report view

frontend/src/components/ActivityReportsTable/ReportRow.js, frontend/src/components/CheckboxSelect.js, frontend/src/components/DateRangeSelect.js, frontend/src/components/DropdownMenu.css, frontend/src/components/DropdownMenu.js, frontend/src/components/Filter.js, frontend/src/components/filter/FilterDateRange.css, frontend/src/components/filter/FilterDateRange.js, frontend/src/components/filter/FilterItem.css, frontend/src/components/filter/FilterItem.js, frontend/src/components/filter/FilterMenu.js, frontend/src/components/filter/FilterPills.js, frontend/src/pages/GranteeRecord/components/GrantsList.css, frontend/src/pages/GranteeRecord/pages/Profile.js, frontend/src/pages/Landing/ReportMenu.js, frontend/src/pages/Landing/index.css, frontend/src/pages/RegionalDashboard/index.css, frontend/src/widgets/TopicFrequencyGraph.css, frontend/src/widgets/TopicFrequencyGraph.js, src/constants.js, src/widgets/targetPopulationTable.js
There are currently 4 different filters variations on the Recipient TTA record page
- Specialist filters
- Date range within
- Date before or after
- Either topic or condition not selected
In all those scenarios, the select dropdowns should align vertically.
This PR also modifies the activity report menu buttons so that they aren't outliers style-wise (worked with Lauren to get those styles).
View the UI and check that all the above variations do align in the filters panel.
Make sure the regional dashboard controls still look correct, and the activity report table menu buttons also still work.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-489
- [n/a] Logical …
=> css fixes for grantee record

src/scopes/activityReport/grantNumber.js, src/scopes/activityReport/index.js, src/scopes/activityReport/index.test.js
Add Backend Filter for Grant Number.
Code not yet implemented on front end. Review code and run unit tests.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-486
=> TTAHUB-486: Add Backend Filter for Grant Number

src/lib/updateGrantsGrantees.js, src/lib/updateGrantsGrantees.test.js, src/migrations/20211207214532-add_grant_state.js, src/models/grant.js, temp/grant_award.xml
Pull in new state code from HSES
Pull down code, run tests
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-346
=> Add state code to grants table

src/widgets/reasonList.js, src/widgets/reasonList.test.js
Update Dashboard Reasons List to Show Zero Values
View the Regional Dashboard page the reason list should show all reasons regardless of number.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-508
=> TTAHUB-5089: Update Dashboard Reasons List to Show Zero Values

docs/TTA Hub dropdowns - master list.csv
Add master list of dropdown options from smartsheets
=> Add dropdowns master list

README.md
Maintenance mode persists through deploys
=> Update maintenance mode docs

frontend/src/pages/Landing/__tests__/index.js, frontend/src/pages/Landing/index.js, frontend/src/widgets/Overview.js
Update Titles on AR Landing.
View the AR landing page, all section headers should now be sentence case.
The region 'all' or # should now display once in the page header.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-538
=> TTAHUB-538: Update Titles on AR Landing

src/services/recipient.js, src/services/recipient.test.js
Filter Out Old Inactive Grants from Grant List
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-543
=> TTAHUB-543: Filter Out Old Inactive Grants from Grant List

frontend/src/pages/ApprovedActivityReport/components/ViewTable.css, frontend/src/pages/ApprovedActivityReport/components/ViewTable.js
Fix missing bullets on approved reports.
Create a AR that uses bullets in the rich text fields. Viewing and printing the approved version of the report should show all bullets.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-577
=> [TTAHUB-577] Fix missing bullets on approved reports

src/lib/updateGrantsRecipients.js, src/lib/updateGrantsRecipients.test.js, temp/grant_award.xml
Fixes an issue when only new grants had their state codes populated in the grant table.
Make sure tests pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-595
=> Fix null states in existing grants

src/seeders/20201124160449-users.js
Populated the hsesUserId and email columns so validation will pass for any edits made via admin page.
Use any of the non-Harry Potter users on the admin page and make an edit.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-604
=> Add missing data

src/testUtils.js
Check that all foreign keys references have been removed prior to deletion from each table.
On CircleCI in the backend test, the "Container circleci/postgres:12.4-ram" does not have any errors.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-598
=> Ttahub 598 db errors

src/scopes/goals/index.js, src/scopes/goals/index.test.js, src/scopes/goals/recipientId.js, src/scopes/goals/region.js, src/testUtils.js, src/widgets/goalStatusGraph.js, src/widgets/goalStatusGraph.test.js, src/widgets/index.js
Needed to add two missing scopes to goals, region and recipient id. Added some test utilities to create/destroy goals to aid in testing. Check pointing at the backend so someone else can pickup the ticket and do the frontend as I won't have time to work on the frontend for a few days.
Make sure tests make sense and pass.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-456
=> Add goal status graph widget on backend

src/scopes/goals/index.test.js
Fix three failing tests on main. I'm not 100% sure how this code made it into main with failing tests, I'm assuming during the merge? I'm looking into why a bit more.
=> Properly pull out goal scope in tests

frontend/package.json, frontend/yarn.lock, package.json, yarn.lock
Update follow-redirects package (frontend & backend) to pass yarn audit
CI passes
=> Update follow-redirects to pass yarn audit

frontend/src/pages/RecipientRecord/__tests__/index.js
Fix failing test after merge.
All tests pass.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-568
=> [TTAHUB-568] Fix failing test after merge

package.json
Added `marked `to the resolutions file based on the dependabot warnings.
Running `yarn audit` locally should not produce warnings related to `marked`
=> Address dependabot alerts

docs/adr/0016-rds-read-replica.md
This is a discussion of how an RDS Read Replica might help solve three separate issues we have. After review, only the second item seems like it could go either way.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-401
=> Add initial ADR discussion

frontend/src/pages/ActivityReport/__tests__/index.js, frontend/src/pages/ActivityReport/index.js
A report will no longer try to save invalid dates to the database
- Start creating a new AR
- Enter the start and end date
- Clear the start date
- Note a validation error "Please enter a valid date" is showing
- Save draft
- Note the report was successfully saved
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-677
=> fix error on save when clearing date

src/models/activityReport.js
All reports to be submitted even if creator role is null.
Find a report that was created before the creator role change but is in needs action state. You should be able to submit the report without issue.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-372
=> remove creator role db validation

frontend/src/components/CloseSuspendReasonModal.css
Minor css fix.
Set a goal to Cease/Suspend the title message "Why are you suspending this goal? (required)" should fit horizontally without wrapping to the next line.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-656
~- [ ] Logical Data Model updated`
=> minor css fix

src/migrations/20220311135140-update-topics-table.js, src/migrations/20220311155440-add-objective-topics.js, src/migrations/20220311160359-add-resource-objectives.js, src/models/objectiveResources.js, src/models/objectiveTopic.js, src/models/resource.js, src/models/topic.js, src/tools/importPlanGoals.test.js
In order to support the new create goals form, some changes to the DB schema will be necessary.
Referenced this doc when writing the new migrations: https://docs.google.com/drawings/d/1xIDlhbKtZ6UiujSX0eqiELvWSPiYRKf-h44jqhvDe8k/edit
Make sure changes are logical and line up with the long term plan 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-707
=> [TTAHUB-707] Update DB schema for the create goals MVP

frontend/src/pages/ActivityReport/constants.js, package.json, src/tools/updateParticipantsList.js, src/tools/updateParticipantsList.test.js, src/tools/updateParticipantsListCLI.js
Update other entity participants list to be alphabetical. 
Write a script to update participants.
Create an AR of type other entity the participants list should now be alphabetized. 
Run the yarn command to execute the 'updateParticipantsList'. The script should run successfully and only bad participant data should be updated (see JIRA for list).
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-691
=> [TTAHUB-691] Update Participants

frontend/package.json, frontend/yarn.lock
Update the frontend dependency async, used in react scripts dev server.
CI passes, dev server still functions.
=> update async to 3.23

frontend/public/index.html
Removed "Smart" from meta-description-content and title.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-771
=> Remove Smart

frontend/src/pages/Landing/__tests__/index.js, frontend/src/pages/Landing/index.js
Default date filter removed from landing page
Open the landing page and verify no date filter by default
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-703
- ~[ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)~
- ~[ ] API Documentation updated~
- ~[ ] Boundary diagram updated~
- ~[ ] Logical Data Model updated~
- ~[ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
=> Default filter removed from landing page

frontend/package.json, frontend/yarn.lock
EJS is used by create-react-app. Updated through resolutions
Site build works, CI passes
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-NO-TICKET
=> update ejs to 3.1.7

frontend/src/components/GoalsTable/GoalRow.js, frontend/src/components/GoalsTable/GoalRow.scss, frontend/src/components/GoalsTable/ObjectiveRow.js, frontend/src/components/GoalsTable/ObjectiveRow.scss, frontend/src/components/GoalsTable/__tests__/GoalsTable.js, src/services/recipient.js
Add grant numbers to the RTR objectives table
- Check my logic for for the relationship for the grant number -> objectives linkage
- Ensure that the RTR goals & objectives table has a grant number and that it looks reasonable at all viewport sizes (the table is starting to strain and heave a bit)
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-801
=> [TTAHUB-801] add grant numbers to objective table on RTR

package.json, yarn.lock
Update failing npm audit dependency, protobufjs, used by New Relic.
CI passes, site works.
=> update protobufjs dependency

frontend/src/components/Navigator/__tests__/index.js, frontend/src/components/Navigator/index.js, frontend/src/hooks/useARLocalStorage.js, frontend/src/pages/ActivityReport/index.js, src/services/goals.js
=> fix duped goal problem

frontend/src/components/ActivityReportsTable/ReportRow.js, frontend/src/components/ActivityReportsTable/__tests__/index.js, frontend/src/components/ActivityReportsTable/index.js, frontend/src/fetchers/__tests__/activityReports.js, frontend/src/fetchers/activityReports.js, frontend/src/pages/Landing/__tests__/index.js, frontend/src/testHelpers.js, src/models/activityRecipient.js, src/routes/activityReports/handlers.js, src/services/activityReports.js, src/services/activityReports.test.js
=> fix report tables

src/models/hooks/objective.js, src/services/goalServices/getGoalsByActivityRecipient.test.js, src/services/recipient.js
Unit test fix as discussed in the meeting for the failing test 'getGoalsByActivityRecipient.test'.
Test should now pass.
~* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0~
=> Fix Recipient Goal Test

frontend/src/components/ControlledDatePicker.js, frontend/src/pages/ActivityReport/Pages/__tests__/nextSteps.js, frontend/src/pages/ActivityReport/Pages/activitySummary.js, frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.css, frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js, frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.scss, frontend/src/pages/ActivityReport/Pages/nextSteps.js, src/migrations/20220527150122-create-next-steps-date.js, src/models/nextStep.js, src/services/activityReports.js, src/services/activityReports.test.js
Add a complete date to next steps.
This is a copy of PR #909 that can be merged into the **main-ar-redesign** branch when ready.
Create a new report. On the 'Next Steps' page Create / Add / Remove / Update new steps.
Ultimately you should be able to create and submit and approve a report containing Next Steps with dates.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-11
=> [TTAHUB-11] Add AR Next Step Complete Date

package.json
Added "got" to the resolutions section.
- yarn audit 
- there should be no vulnerabilities warnings
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-906
=> Handle Dependabot alert related to "got"

frontend/src/components/GoalForm/ObjectiveTitle.js, frontend/src/components/GoalForm/ObjectiveTopics.js, frontend/src/components/GoalForm/ResourceRepeater.js, frontend/src/pages/ActivityReport/Pages/components/ObjectiveStatus.js
=> add suspended objective status'

frontend/package.json, frontend/yarn.lock, package.json, src/routes/goals/handlers.test.js, src/services/goalServices/saveGoalForReport.test.js, src/services/goals.js, yarn.lock
Fix BE tests.
All BE tests should pass.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-908
=> [TTAHUB-908] Fix BE Tests

frontend/src/App.js, frontend/src/__tests__/utils.js, frontend/src/components/Accordion.js, frontend/src/components/AppWrapper.js, frontend/src/components/Modal.js, frontend/src/components/MultiSelect.js, frontend/src/components/Navigator/__tests__/index.js, frontend/src/components/Navigator/index.js, frontend/src/pages/ActivityReport/Pages/__tests__/goalsObjectives.js, frontend/src/pages/ActivityReport/Pages/__tests__/supportingAttachments.js, frontend/src/pages/ActivityReport/__tests__/index.js, frontend/src/pages/ActivityReport/index.js, frontend/src/utils.js
Frontend tests should pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-907
=> [TTAHUB-907] Fix frontend tests on main ar redesign after merging latest schema changes

deployment_config/staging_vars.yml
Temporarily increase staging memory for the restoreTopics script
=> Temporarily increase staging memory for the restoreTopics script

.circleci/config.yml, deployment_config/staging_vars.yml
Reverts the temporary memory increase in staging and deploys the migration branch to Dev
Dev is functional again
- [bn/a ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ n/a] API Documentation updated
- [n/a ] Boundary diagram updated
- [n/a ] Logical Data Model updated
- [n/a ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
=> Revert the temporary memory increase in staging and deploy the migration branch to Dev

frontend/src/pages/Landing/ReportMenu.js, frontend/src/pages/RecipientRecord/components/RecipientTabs.js, frontend/src/pages/RecipientRecord/index.js
This change removes the feature flag hiding the Goals & Objectives tab. 
View the site as a user without the feature flag. Confirm that you can see everything you are supposed to and that you won't see anything you aren't.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-NO
=> [Prod] Remove feature flag from goals & objectives tab

src/services/activityReports.js
To reproduce the bug
- Save some ECLKC resources and non-ECLKC resources
- Clear local storage for hygiene
- Navigate away
- Navigate back
ECLKC resources and non-ECLKC resources should have disappeared
This change should fix that.
See description
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-918
=> [TTAHUB-918] fix for resources not saving properly

src/models/auditModelGenerator.js, src/models/hooks/activityReport.js, src/models/hooks/objective.js, src/routes/goals/handlers.test.js
Cleanup test output and fix a few tests that were not functional but not failing.
run test for backend and the output will be less cluttered.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-915
=> Ttahub 915/cleanup and fix tests

README.md
Looks like a typo when I updated Node
=> update node version in main readme

src/services/goalServices/getGoalsByActivityRecipient.test.js, src/services/recipient.js
Add "or" check for onApprovedAR or isFromSmartsheetTtaPlan
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-914
=> Add or check for onApprovedAR or isFromSmartsheetTtaPlan

frontend/src/pages/ActivityReport/index.js, src/services/activityReports.js, src/services/activityReports.test.js
Fix for stringified JSON being stored in the DB. This PR does not do anything about rogue data that might have made it to the DB while this bug was active.
To verify bug,
- Start a new report (no need to fill anything out)
- Click on topics and resources in the left hand nav
- Observe in the database that the report has been created and both ECKLC resources and non ECKLC resource fields are empty
- Click on next steps in the left hand nav
- Rechecking the database or the response from the network, you'll see that the stringified JSON has been
stored in the database
Then, rechecking these steps with this code, you'll note that there is no stringified JSON stored in the DB
=> fix for json in db

src/migrations/20220728000000-revert-g-13970.js
Revert goal to an `In Progress` state per a user request because they accidentally closed it.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-932
=> Revert Goal 13970 to In Progress for user

src/migrations/20220728000000-revert-g-13970.js
Revise to add 11 additional goal reversions (August 1st is a major user deadline)
https://ocio-jira.acf.hhs.gov/browse/TTAHUB-932
=> revert additional goals to in progress

frontend/src/fetchers/goals.js, frontend/src/pages/ActivityReport/Pages/components/GoalForm.js, frontend/src/pages/ActivityReport/Pages/components/Objectives.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalForm.js, src/routes/goals/handlers.js, src/routes/goals/index.js, src/services/goals.js
If the user selects an existing goal we need to display existing objectives as selectable.
Create a new AR and select an existing goal. All the objectives for that goal should be selectable that aren't 'completed' or 'draft'.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-939
=> [TTAHUB-939] Fix Objectives for Goals

frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js, frontend/src/pages/ActivityReport/Pages/components/GoalValue.js, frontend/src/pages/ActivityReport/Pages/components/ObjectiveOption.js, frontend/src/pages/ActivityReport/Pages/components/ObjectiveSelect.js, frontend/src/pages/ActivityReport/Pages/components/ObjectiveValue.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalOption.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalValue.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/OtherEntity.js, src/services/goals.js
The goal & objective pickers on the AR will now show the relevant IDs.
=> show goal and objective ids

src/README.md
Looking for something else, found this small inaccuracy
=> Update sequelize info in backend README.md

axe-urls, frontend/src/components/ActivityReportsTable/index.js, frontend/src/components/GoalsTable/StatusDropdown.js, frontend/src/components/SiteNav.js, frontend/src/pages/RecipientRecord/components/RecipientTabs.js, frontend/src/pages/RecipientRecord/pages/components/PrintableGoal.js, frontend/src/pages/RecipientRecord/pages/components/PrintableObjective.js, frontend/src/pages/RecipientSearch/index.js, frontend/src/widgets/ReasonList.js, frontend/src/widgets/TableWidget.js, frontend/src/widgets/__tests__/ReasonList.js
- Update pages to be run through our automated accessibility scanning
- Found a few small errors and did some mild cleanup while poking around
CI runs and successfully completes a scan with no issues found
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-942
=> [TTAHUB-942] update axe urls for new pages and features

package.json, yarn.lock
Update undici module (used by elasticsearch) to get CI passing again
CI passes
=> update undici through package.json resolutions

frontend/src/components/GoalsTable/GoalsTableHeader.js, frontend/src/pages/RecipientRecord/index.js, frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js, frontend/src/pages/RecipientRecord/pages/PrintGoals.js, frontend/src/pages/RecipientRecord/pages/__tests__/PrintGoals.js, frontend/src/pages/RecipientRecord/pages/constants.js
`PrintGoals` respects the filters applied at the Goals & Objectives page.
Apply some filters and ensure that the goals in the table below are the same as the goals that are listed on the `PrintGoals` page.
https://user-images.githubusercontent.com/17074357/183964612-dc501623-f5cc-47b1-a952-f9ebfe1f68e8.mov
=> [TTAHUB-916] Printing goals respects filters

.env.example, README.md
Reviewing the instructions for new engineers, I ran into some updated information about setting up your development environment.
Verify the information in the readme
=> update readme with more current instructions

frontend/package.json
d3-color used as a dependency had a vulnerability identified. Added to the resolutions section
Make sure the frontend tests pass
=> Add d3-color to the resolutions

deployment_config/prod_vars.yml
Turn the notifications on in production. 
No testing needed.
=> Set SEND_NOTIFICATIONS to true in prod

.circleci/config.yml, Dockerfile, README.md, bin/run-tests, bin/test-backend-ci
=> attempt to store coverage

.circleci/config.yml, src/app.js, src/lib/cron.js, src/lib/cron.test.js
Refactors the code moving the cron related functions to a separate file. Adds a function to trigger the monthly digests on the last day of a month.
Look at the code. No specific tests.
Code deployed to Sandbox.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1023
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1024
=> Create a monthly cron all months to run on the last day

frontend/src/pages/ApprovedActivityReport/index.js, src/models/hooks/activityReport.js, src/services/goals.js, src/services/reportCache.js
Reverts HHS/Head-Start-TTADP#1060
=> Revert "[TTAHUB-1040] Update ARO status only via Activity Report"

frontend/src/pages/ApprovedActivityReport/index.js, src/models/hooks/activityReport.js, src/services/goals.js, src/services/reportCache.js
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1040
=> [TTAHUB-1040] Update ARO status

src/models/hooks/activityReport.js, src/models/hooks/activityReport.test.js, src/models/tests/objectiveStatus.test.js
This PR is to resolve the comments/issues found on https://github.com/HHS/Head-Start-TTADP/pull/1054.
Make sure all comments have been addressed from https://github.com/HHS/Head-Start-TTADP/pull/1054.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1034
=> [TTAHUB-1034] PR Review Issues

src/services/goalServices/getGoalsByActivityRecipient.test.js, src/services/recipient.js
This change fixes the following bug
- Create a new AR with an existing goal and add an objective with topics.
- Approve the AR.
- Note that the topics from above didn't show up on the RTR.
Repeat the steps from above, you will see that topics appear on the RTR
=> [TTAHUB-1029] Missing topics on the RTR

frontend/src/components/GoalForm/__tests__/index.js, frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js, src/routes/roles/handlers.js
Rename Topics to Roles in Handler
Rename Topics to Roles in Handler
=> Rename Topics to Roles in Handler

src/services/goals.js
To recreate issue - create a multi recipient report, on the AR, create a new goal and objective, set the objective to "In Progress", you will see multiple objectives.
Issue is resolved
=> [TTAHUB-1029] fix issue with duping objectives

src/services/goals.js
Fix Missing Topics
Create an AR with a goal and objective add more than one topic and save. The topics should show on both the read only and edit views.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1068
=> [TTAHUB-1068] Fix Missing Topics

src/models/auditModelGenerator.js
Log output is very polluted from multi-line queries relating to audit log. 
view log output as a single line per audit log query
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-819
=> [TTAHUB-819] Reduce output from 23 lines to 1 line

package.json, src/lib/transform.js, yarn.lock
The original implementation only supported deduping records in the following pattern:
AAAAAAABBBBBBB => AB
When duplicate records are not consecutive they are not deduped:
ABABABABABABAB => ABABABABABABAB
=> [TTAHUB-1063] change matching from previous to hash lookup in processed array

frontend/src/components/GoalCards/GoalCard.js, frontend/src/components/GoalCards/GoalCards.js, frontend/src/components/GoalCards/GoalDataController.js, frontend/src/components/GoalCards/GoalsCardsHeader.js, frontend/src/components/GoalCards/__tests__/GoalCards.js, frontend/src/fetchers/recipient.js, frontend/src/pages/RecipientRecord/pages/PrintGoals.js, src/services/goalServices/getGoalsByActivityRecipient.test.js, src/services/recipient.js
Add ability to select individual or all goals.
1. Ability to select one goal
2. Ability to select just one page of goals (should display alert with option for all)
3. Ability to select all goals
4. Selected goals should stick from page to page
5. Pill that displays the count of selected goals
6. Remove pill removes all selections
7. On G&O tab - change link language "Preview and print selected" (add "selected")
8. When "Preview and print selected" is selected, then only print the selected goals
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-856
=> [TTAHUB-856] Goal Select

.circleci/config.yml, src/lib/cron.js
There is an issue with merging main into main-ar-redesign, but we need to ensure this change deploys successfully to Dev. This PR limits the changes going in to the feature branch ones.
Make sure the build succeeds and the code is deployed to Dev
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1077
=> Disable non prod Recipient & Grant updates (merge into main-ar-redesign)

frontend/src/pages/RecipientRecord/index.js
Trying not to leave this till the last minute, remove the feature flag from the create goals related routes
=> [TTAHUB-1029] remove feature flag from create goals route

src/scopes/goals/topics.js
Combine new and old topics filter so that the RTR properly filters topics
Filter by topics on the RTR and confirm that the info is correct.
=> [TTAHUB-1029] Fix topics filter

frontend/src/components/GoalForm/ObjectiveFiles.js, src/routes/files/handlers.js, src/services/goals.js, src/services/objectives.js
Changes to the goal creation logic meant that sometimes the spontaneous goal creation on the file uploader would fail. This change fixes errors that sometimes occur when files are being created.
Ensure that file uploads work from the AR and the manage goals feature.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1087
=> [TTAHUB-1087] fix file uploads

src/services/activityReports.js
If you create a report go to the next steps page then leave (or fill out some text then leave) you get a server 500 for invalid date.
Complete the above steps for both Recipient and OE.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1108
=> [TTAHUB-1108] Fix saving of invalid NS date

frontend/src/components/GoalCards/ObjectiveCard.js, src/services/reportCache.js
The status of an objective is not saving.
Create an OE report and add an objective with the status 'Suspended'. Approve the report and verify in the 'Approved' view it shows as suspended.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1102
=> [TTAHUB-1102] Fix OE Objective Status Saving

src/models/auditModelGenerator.js, src/models/hooks/objectiveFile.js, src/models/hooks/objectiveResource.js, src/models/hooks/objectiveTopic.js
Performance issues when multiple recipients are selected on an AR
monitor speed of goal creation for multiple recipients.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1111
=> [Ttahub 1111] performance issues

src/migrations/20221103000000-emergent-goals-not-rttapa.js, src/models/goal.js
set all goals with isFromSmartsheetTtaPlan as not true to isRttapa is false
edit a non rttapa goal, the no radio `button should be selected for the is rttapa question.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1113
=> [Ttahub 1113] emergent goals not rttapa

frontend/src/App.js, frontend/src/AppLoadingContext.js, frontend/src/components/Header.js, frontend/src/components/Loader.css, frontend/src/components/Loader.js, frontend/src/components/Navigator/__tests__/index.js, frontend/src/components/Navigator/index.js, frontend/src/pages/ActivityReport/Pages/components/GoalForm.js, frontend/src/pages/ActivityReport/Pages/components/OtherEntity.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalForm.js, frontend/src/pages/ActivityReport/testHelpers.js, frontend/src/widgets/__tests__/DashboardOverview.js, frontend/src/widgets/__tests__/TopicFrequencyGraph.js, frontend/src/widgets/__tests__/TotalHrsAndRecipientGraph.js
When creating an AR we want to put a loader over the entire application.
We should display a App loader when performing the following AR actions.
- 'Save and Continue'
- 'Save Draft'
- 'Save Goal' 
- Jumping between AR Pages via NAV
It should NOT occur during an auto save.
The AR creation process should work as it did before.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1069
=> [TTAHUB-1069] Add AR App Loader

frontend/src/pages/RecipientRecord/components/RecipientSummary.js, frontend/src/pages/RecipientRecord/components/__tests__/RecipientSummary.js, src/services/recipient.js
swap id with uei on rtr page
view rtr page, should see uei value as Recipient ID
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-900
=> [TTAHUB-900] Display UEI data from HSES on RTR

frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV1.js, frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
when data value is empty dont show the field
view ar approved prior to 11/16/2021
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-665
=> [Ttahub-665] Remove "Date Approved" from AR when there is no date in the database

.circleci/config.yml, frontend/src/fetchers/__tests__/recipient.js, frontend/src/pages/RecipientRecord/pages/__tests__/TTAHistory.js, src/services/currentUser.js
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1152
=> [TTAHUB-1152] add some test coverage

src/routes/activityReports/handlers.js, src/routes/activityReports/handlers.test.js
Reset a report to draft would throw an error.
Should not throw an error.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1159
=> [TTAHUB-1159] Fix reset to draft

.circleci/config.yml
=> disable artifact storage on CI

.circleci/config.yml, frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
Instead of selecting all objectives for an existing goal, with this change we only select one (change deployed on sandbox for testing)
- Verify the above
- Also verify AR file uploads are working proplery
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1221
=> [TTAHUB-1221] Properly select objectives for existing goal

.circleci/config.yml, frontend/src/pages/ActivityReport/Pages/components/GoalForm.js, src/services/goals.js
Revert a change that caused all objectives for a goal to show up as selected on the activity report
Select an existing goal on the activity report - no objectives will be auto-selected
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1221
=> [Prod] Properly handle loading objectives for existing goals

src/services/goals.js
There is a check on the BE that isn't correctly removing ARO's.
Find an existing AR with goals and objectives. Should should be able to remove objectives leave the page and come back and see the objectives deleted.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1223
=> [TTAHUB-1223] Fix objective delete

frontend/src/components/ControlledDatePicker.js, frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js, src/services/goals.js
Remove min date validation from next steps on the activity report form
Use the next steps repeater with a combination of valid and invalid info. Delete and add steps. Check the validation behaves as expected.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1224
=> [Production] [TTAHUB-1224] Remove min date and improve validation on next steps

README.md
Documenting the process we used to delete and recreate the redis service - PR is already approved but I'll leave it open for a day or so in case anyone else has a comment on it.
=> update readme with instructions for removing and recreating a service

tests/activity-report.spec.ts
a change on `main` defined new behavior for the new goal selector after `add new goal` was clicked, which means this test needs to be updated
if this PR passes in CI, it should be all good 👍 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1257
=> [TTAHUB-1257] Fix AR e2e test

frontend/src/Constants.js, frontend/src/components/filter/MyReportsSelect.js, frontend/src/components/filter/__tests__/FilterMenu.js, frontend/src/components/filter/__tests__/MyReportsSelect.js, frontend/src/components/filter/activityReportFilters.js, frontend/src/pages/Landing/constants.js, frontend/src/pages/RecipientRecord/pages/constants.js, frontend/src/pages/RegionalDashboard/constants.js, src/routes/activityReports/handlers.js, src/routes/widgets/handlers.js, src/scopes/activityReport/index.js, src/scopes/activityReport/index.test.js, src/scopes/activityReport/myReports.js, src/scopes/activityReport/userReportRoles.js, src/scopes/index.js, src/scopes/utils.js, src/services/activityReports.js
Added a new 'My reports' filter to the AR Landing, Regional Dashboard, and TTA History pages.
- Test filtering various combinations of the new filter from each page (Creator, Collaborator, Approver).
- Try mixing new filters with existing filters.
- Exports should work as they did before and reflect new filter.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-793
=> [TTAHUB-793] My reports filter

src/scopes/activityReport/index.test.js
There have been a bunch of flaky tests in the scopes testing area. It seems to have gotten worse with the addition of the 'My Reports' filter tests. This changes hopes to prevent these errors from occurring.
Review the code make sure all tests pass.
=> Fix Filter Scope Tests

frontend/src/widgets/TotalHrsAndRecipientGraph.js, frontend/src/widgets/TotalHrsAndRecipientGraph.scss
Embarassingly, committed my changes but did not push before clicking merge on my existing branch. These are the changes to the TTA hours graph that Lauren requested to this PR #1210. Lauren already agreed that these changes addressed her feedback.
Verify the responsive behavior
https://user-images.githubusercontent.com/3288586/208505026-192495d1-2ed7-4c45-be91-7ddafd98e1b9.mov
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1245
=> [TTAHUB-1245] Fixes to responsive behavior per Lauren

frontend/src/pages/ActivityReport/__tests__/formDataHelpers.js, frontend/src/pages/ActivityReport/formDataHelpers.js, frontend/src/widgets/TotalHrsAndRecipientGraph.js, src/tools/createAwsElasticSearchIndexes.test.js
because I didn't merge main into #1246 recent enough before it was merged into main earlier, I didn't have a chance to update a few imports. whoops
=> fix imports on main

frontend/src/pages/RecipientRecord/index.js, frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js, frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js, src/services/recipient.test.js, tests/ttahub-1322.spec.ts
To keep consistency and fix google analytics page title needs to include recipient name. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1322
=> [TTAHUB-1322] Change page title for goals and objectives page

tests/activity-reports.spec.ts
This PR adds an integration test that confirms the proper behavior is observed when a user is given a URL that contains regions that they don't have access to
CI passes, test makes sense
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1282
=> [TTAHUB-1282] Add integration test for URL sharing

.circleci/config.yml, package.json, src/lib/awsElasticSearch/index.js, src/models/hooks/activityReport.js, src/models/tests/activityReport.test.js, tests/activity-report-text-search-filter.spec.ts
Add AWS ElasticSearch (image) to e2e testing and write a test.
Review the code. Make sure all tests pass on CircleCi.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-873
=> [TTAHUB-873] AWS ElasticSearch e2e test

src/lib/awsElasticSearch/modelMapper.js
This fixes an error that occurred when running the script on staging.
All unit tests should pass.
=> Fix error on create index script

deployment_config/staging_vars.yml
=> Increase staging memory test

playwright.config.js, tests/activity-report-text-search-filter.spec.ts
Combine the new 'Report text' filter with other filters.
Make sure all e2e tests pass.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-872
=> [TTAHUB-872] Combined e2e report text test

src/migrations/20230124000000-missing-objectives.js
Rerun a migration to restore missing AROs and Objectives since last time it was run.
I reran this on a local dump
* https://ocio-jira.acf.hhs.gov/browse/[TTAHUB-1065](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1065)
=> re-add_migration_and_remove_objectivegoals

src/migrations/20221129000000-dedupe-objectives.js, tests/activity-report-text-search-filter.spec.ts
This PR fixes an end to end test failure that is currently blocking the CI/CD pipeline.
The CI passes
=> [Prod] Fix end-to-end test failure

frontend/src/components/IndicatesRequiredField.js, frontend/src/components/Navigator/index.js, frontend/src/pages/ActivityReport/Pages/Review/Approver/Review.js, frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js, frontend/src/pages/ActivityReport/Pages/Review/Submitter/NeedsAction.js, frontend/src/pages/ActivityReport/Pages/__tests__/goalsObjectives.js, frontend/src/pages/ActivityReport/Pages/activitySummary.js, frontend/src/pages/ActivityReport/Pages/goalsObjectives.js, frontend/src/pages/ActivityReport/Pages/nextSteps.js, frontend/src/pages/ActivityReport/index.scss
Add "* indicates required field" under the heading on the Goals and objectives page, the next steps page, and the Review and submit page.
Confirm the language is present
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1285
=> [TTAHUB-1285] add required language to other AR pages

frontend/package.json, package.json
This PR adds the packages to the resolutions sections to handle the dependabot/yarn audit vulnerabilities alert.
Verify the application is functional and the tests pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1426
=> Handle vulnerabilities from dependabot

src/lib/cron.js
This change disables the daily notifications that run on weekends.
Verify tests pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1445
=> Adjust daily email notifications to run on weekdays only

frontend/src/App.scss
=> [TTAHUB-1439] plotly-notifier fix

frontend/src/pages/ApprovedActivityReport/__tests__/ApprovedReportV1.js, frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV1.js
Fix error with other entity approved reports where the wrong field was being referenced on the API response, causing a fatal javascript error
View report 8671 and some other approved reports. Confirm that they all function appropriately.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1437
=> [TTAHUB-1437] fix parsing error with OE approved reports

frontend/src/pages/AccountManagement/index.js
`Manager approves` -> `Managers approve`
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1465
=> [TTAHUB-1465] Email preference typo

.circleci/config.yml
This change specifies large resource class for the jobs in config.yml.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1472
=> Update pipeline jobs to large resource class

.circleci/config.yml, deployment_config/dev_vars.yml, deployment_config/staging_vars.yml
Swap memory between Staging and DEV in order to do more testing on ES performance.
=> Swap memory between Staging and DEV

src/services/goals.js
Fix unhandled exception in the goals reducer
View report 7199 on any prod-like environment. You should be able to view the report without a fatal error
=> check for null on reducer, use try/catch

frontend/src/pages/ApprovedActivityReport/__tests__/ApprovedReportV1.js, frontend/src/pages/ApprovedActivityReport/__tests__/ApprovedReportV2.js, frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV1.js, frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js, src/lib/transform.js, src/migrations/20230208151755-ar-submitted-date.js, src/models/activityReport.js, src/models/hooks/activityReport.js, src/models/tests/activityReport.test.js, src/routes/activityReports/handlers.js, src/services/activityReports.js
Added submitted date to approved reports.
Run the migration, then create and submit and approve the report. Verify the submitted date shows on the approved report.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1347
=> [TTAHUB-1347] AR submitted date

src/models/hooks/activityReport.js, src/models/tests/activityReport.test.js
Fix needs_action bug for submittedDate.
Create and submit and approve a report. Unlock the report and verify the db still has the initial submitted date. Approve the report again verify the submitted date remains.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1347
=> [TTAHUB-1347] Fix needs_action bug for submittedDate

frontend/src/pages/Home/index.js, src/migrations/20230301200028-anv-statistics-feature-flag.js, src/models/user.js, src/services/users.js
Add a feature flag for anniversary statistics.
- Review code.
- Make sure if the user isn't an admin  and doesn't have the feature flag enabled they don't see the new ann statistics.
=> Add a feature flag for anniversary statistics

src/tools/processData.js
Updates the data transform seeders to reflect the current team
Verify that the added users are visible in the Admin -> Users UI
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1535
=> Update data transform seeders with the most recent user data

README.md
=> [No ticket] Add instructions/examples for updating network policy

src/lib/transform.js, src/lib/transform.test.js
A bug was discovered where goals without objectives don't appear on the CSV export. This PR fixes that.
Export selected reports including goals where there are no objectives and confirm that the goals are present. The Jira has a spreadsheet containing many, (23470 is a good option) although note that some of those are legacy goals, which this PR does not attempt to fix.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1490
=> [TTHUB-1490] goals missing from csv

src/widgets/topicFrequencyGraph.js
After we applied the topics frequency perf fix the tests started failing this fixes the tests.
- Make sure we still have perf increase.
- All tests pass.
=> Fix for Topics Frequency Test

src/migrations/20230315124028-remove-unique-group-name.js
A support ticket was created for a user unable to create a group with the same name as another person.
This migration removes the unique index.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1581
=> [TTAHUB-1581] Allow for duplicate group names

src/tools/changeReportStatus.js, src/tools/changeReportStatus.test.js
This PR updates the existing script used for changing the activity report status.
- create an AR and approve it
-` yarn changeReportStatus:local -i <actiityReportId> -s draft`
- verify that the status was changed
=> Update the change status script

src/services/dashboards/resource.js
switch from array scan to map lookup
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1587
=> [TTAHUB-1587] - Performance enhancement for Resource dashboard

.circleci/config.yml, src/migrations/20230322150923-add-rtr-order-goals.js, src/models/goal.js, src/services/goalServices/goalByIdAndRecipient.test.js, src/services/goals.js
This changes adds a column to the Goals table that tracks the order they were created in on the RTR.
Create two goals on the RTR. Note that the newest goal moves to the bottom each time.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1208
=> [TTAHUB-1208] put the goals in the correct order on the RTR

package.json, src/services/currentUser.js, tests/api/README.md, tests/api/common.ts, tests/api/settings.spec.ts, tests/api/user.spec.ts, tests/api/users.spec.ts, yarn.lock
1360 is a somewhat large epic with many API tests that need to be written. They will all be branched off of this branch (`jp/ttahub-1262/ttahub-1360/validation`) as a starting point because it includes the required dependencies and folder structure.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1360
=> [TTAHUB-1262 / TTAHUB-1360] initial scaffold for api validation testing using playwright

frontend/yarn.lock, package.json, yarn.lock
Update dependency blocking CI
CI passes
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-
=> update xml2js dependency via resolution

frontend/src/pages/Admin/UserSection.js
this change was missed as part of the impersonation release
the "Impersonate user" button should now be visible.
=> Impersonation fix - FE button guard removal

tests/api/topics.spec.ts
this small PR adds a test for `/api/topic/`
if the e2e tests pass, 👍 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1361
=> [TTAHUB-1262] [TTAHUB-1361] API validation: /topic

tests/api/role.spec.ts
adds tests for `/role` and `/role/specialists`
if the e2e tests pass, 👍
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1358
=> [TTAHUB-1262] [TTAHUB-1358] API validation: /role

tests/api/recipient.spec.ts
adds tests for `/recipient` endpoint
if the e2e tests pass, 👍
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1357
=> [TTAHUB-1262] [TTAHUB-1357] API validation: `/recipient`

frontend/package.json, package.json
Fix an audit vlunerability with yaml.
Site works and all tests pass.
=> Fix Yaml Audit Vlun

src/lib/cache.ts
There is a logical error in the way the caching function works right now. If the cache is not expired, then it will be extended for 10 minutes without the data reloading, which isn't correct
Visit any of the places where data is cached, wait 1 minute and change the data, wait 5 minutes, visit again. The data should be the same. Wait an additional 5 minutes - you should see the updated data.
=> [No ticket] Fix cache so its only set when empty

tests/api/goals.spec.ts, tests/api/recipient.spec.ts
Add `deleted `to the API validation
Tests pass
=> Fix API validation test

.circleci/config.yml, src/newrelic.js
New Relic supports monitoring queries to aid in identifying issues. The instrumenting of query logging had not been done.
The required changes are added to the config passed to New Relic using environment variables to support changing the values without the need of pushing changes through CI just to adjust logging.
- NEW_RELIC_AUDIT_LOG_ENABLED
-- defaults to false, pass true to enable 
- NEW_RELIC_AUDIT_LOG_ENDPOINTS
-- defaults to ['error_data',  'error_event_data', 'sql_trace_data',], pass any combination of [agent_settings, analytic_event_dataconnect, custom_event_data, error_data,error_event_data, metric_data,preconnect, shutdown, span_event_data, sql_trace_data, transaction_sample_data]
- NEW_RELIC_TRACER_ENABLED
-- defaults to false, pass true to enable 
- NEW_RELIC_RECORD_SQL
-- …
=> [TTAHUB-224] turn on a lot of additional logging for new relic

src/tools/logicalDataModel.ts
=> [NO JIRA] remove console.log

frontend/src/components/Navigator/__tests__/index.js, frontend/src/components/Navigator/index.js, frontend/src/pages/ActivityReport/__tests__/index.js, frontend/src/pages/ActivityReport/formDataHelpers.js, src/services/goalTemplates.ts, src/services/resource.js
There are three changes here, intended to resolve the user problem detailed in the Jira ticket.
1) As discussed in the original requirements, the front end should not be sending prompts to the back end if the report is a multi-recipient report. Likely, this particular bug is caused by switching the number of recipients after setting prompts, but we are now handling that case. The front end now formats the goals appropriately each time they are sent to the backend, to remove the prompts where necessary.
2) Upon reflection, there is no need at this time for the back end to validate the presence of the prompts. Given the disparate amount of states prompts & goals can be in, I've removed the validation from the backend that checks the required key. This is checked on the frontend. The max …
=> [TTAHUB-1713] Better handle prompts on multirecipient reports, add resource bug workaround

frontend/src/pages/ResourcesDashboard/__tests__/index.js, frontend/src/pages/ResourcesDashboard/index.js, src/services/dashboards/resource.js, src/services/dashboards/resource.test.js
Remove the topic use widget from the resource dashboard
Ensure the widget is removed and that normal service is not interrupted.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1683
=> [TTAHUB-1683] remove widget, for real, the topic use one this time

src/lib/updateGrantsRecipients.js, src/lib/updateGrantsRecipients.test.js, src/scopes/grants/activeWithin.js, src/scopes/grants/index.test.js
Since we have the inactivation date, we no longer need the deletion code for the recipients and grants updates. This PR removes it. It also adds inactivation date to filters with dates
Make sure the tests pass.
Confirm the numbers on filters with dates on the Regional Dashboard are correct.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1707
=> Remove deletion code

frontend/src/components/HeaderUserMenu.js, frontend/src/components/SiteAlert.js, frontend/src/pages/AccountManagement/components/Groups.js, frontend/src/pages/Home/Llama.css, frontend/src/pages/Home/Llama.js, tests/e2e/my-groups.spec.ts
Doing some routine auditing of our recent work, found a few issues.
- Improved llama loading message
- ensured "prefers-reduced-motion" was being respected in the llama.css
- site alerts should announce themselves
- notifications should be announced when focused on the user menu button
- add context to "edit" and "delete" links on the my groups page
=> Accessibility fixes

src/models/hooks/resource.js
queue refactor caused a loading recursive issue
=> [TTAHUB-1781] recursive resource model loading

packages/common/README.md
Now that `common` is a public package under the `@ttahub` organization, the README doesn't really make sense.
Please, if I missed anything or if you can think of anything to add to the README, go ahead and commit changes directly to this branch.
=> [no ticket] Update README for common package

.githooks/pre-commit
This hook checks to see if common/src/index.js was updated, and if so, won't commit unless both yarn.locks and the package.json for common is also updated. As with all pre-commit hooks, we have to **install** the file for it do to anything 😄 .
=> New pre commit hook

.circleci/config.yml
The latest version of ZAP has resolved the issue that caused us to switch to a static version. Build now succeeds for the dynamic_security_scan. 
Look at build... dynamic_security_scan passed.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1027
=> [TTAHUB-1027] Try latest zap tag

docs/adr/0018-audit-log-archive.md
ADR to outline the pros and cons of implementing the audit log archiving and the proposed solution.
No tests needed.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1738
=> Audit log archiving strategy proposal

frontend/src/pages/SessionForm/__tests__/index.js, frontend/src/pages/SessionForm/constants.js, frontend/src/pages/SessionForm/index.js, frontend/src/pages/SessionForm/pages.js, frontend/src/pages/SessionForm/pages/__tests__/completeSession.js, frontend/src/pages/SessionForm/pages/completeSession.js, frontend/src/pages/SessionForm/pages/sessionSummary.js
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1804
=> [TTAHUB-1804] Complete session form

package.json, yarn.lock
Update semver to non-vulnerable version
CI runs
=> [NO-TICKET] update semver

frontend/src/components/filter/activityReportFilters.js, frontend/src/pages/Landing/constants.js, frontend/src/pages/RegionalDashboard/constants.js
It was decided to name these two new resource filters "Resource link" and "Resource attachment".
=> [TTAHUB-1703] Rename filters

frontend/src/pages/TrainingReportForm/pages/eventSummary.js
Rename the field "Event owner" should be "Event creator."
Rename the field "Event owner" should be "Event creator."
=> [TTAHUB-1875] Creator label change

tests/e2e/training-report.spec.ts
Meant to be a framework upon which we can build. 
CI passes. Test seems to be written in a sustainable manner
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1880
=> [TTAHUB-1880] create basic e2e test training and session reports

frontend/src/pages/SessionForm/__tests__/index.js, frontend/src/pages/SessionForm/index.js, frontend/src/pages/TrainingReportForm/__tests__/index.js, frontend/src/pages/TrainingReportForm/index.js
- Update training report form header from _Regional/National Training Report_ to _Training Report - Event_
- Update session form header from _Regional/National Training Report_ to _Training Report - Session_
Confirm updates
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1917
=> [TTAHUB-1917] Update the titles for the training forms

frontend/package.json, frontend/yarn.lock, package.json, packages/common/README.md, packages/common/package.json, packages/common/src/index.js, yarn.lock
We need to add 'Program Staff' as a target population on the AR.
Confirmed with Patrice only AR for now and at the end of the list (alpha).
Create a report with the target population 'Program Staff'.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1941
=> [TTAHUB-1764] Add new target population Program Staff

docs/adr/0018-audit-log-archive.md, docs/adr/0019-audit-log-archive-details.md
This PR dives deeper into implementation details of the audit log archival. It incorporates Garrett's feedback from #1566. (please ignore `0018-audit-log-archive.md` which is covered in #1566)
No tests are needed.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1738
=> Archiving audit log details ADR

frontend/src/components/filter/FilterStateSelect.js, frontend/src/components/filter/__tests__/FilterMenu.js, frontend/src/components/filter/__tests__/FilterStateSelect.js, frontend/src/components/filter/activityReportFilters.js, tests/e2e/regional-dashboard.spec.ts
Stakeholder is requesting change to the state filter name from "State" to "State or Territory". Required changes to filter name, select label text for screen reader, and updates to 2 test files.
- Look at filter list on Activity Reports page, Regional Dashboard, Goal Dashboard, Resource Dashboard and RTR TTA History and Goals & Objectives tabs to see filter list
- inspect select input to see updated label text
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1928
=> Updated state label to State and Territory

src/migrations/20230822192328-internal-goal-duplicate-cleanup.js
In preparing for deployment it was discovered that 1 recipient had 1 duplicate goal that had "root cause" defined. The script was not prepared to support that.
Run migration, if succeeds, then its good.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1785
=> {TTAHUB-1785] updated to support FEI type goals use of field responses

frontend/src/pages/SessionForm/pages/__tests__/sessionSummary.js, tests/e2e/activity-report-text-search-filter.spec.ts, tests/e2e/activity-report.spec.ts
I made an error and merged in a PR that didn't have the latest main merged into it. I was immediately repaid for my hubris when a frontend test and some end-to-end tests began to fail. This PR fixes those failing tests.
CI passes
=> Fix frontend & e2e test

src/migrations/20230908140816-fix-fei-goals.js
We need to change the goal template on a handful of FEI goals.
Run the migration make sure all goals in the below list have a goal template id of: **19017**
**Goal Ids:**
52248
52251
52249
52250
55244
55172
55908
55420
55421
56033
50565
50613
50612
50343
50614
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2083
=> [TTAHUB-2083] Update goal templates

src/migrations/20230908155325-fix-fei-root-causes.js
A handful of grants in region six have invalid root causes set. This migration updates the table values to be the correct root cause.
Run the migration all root causes should match the PDF on the ticket.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2042
=> [TTAHUB-2042] Fix FEI root causes

docker-compose.dss.yml, docker-compose.test.yml, docker-compose.yml
Rollback PostgreSQL version to 12.
=> No-Ticket: Rollback postgresql version

src/services/recipient.js, src/services/recipient.test.js
If root cause is different on FEI goal for recipient's multiple grants, then display the FEI goal on multiple cards on the RTR.
The Jira ticket includes examples of grants that suffer from this problem
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2085
=> [TTAHUB-2085] do not de-duplicate RTR goals based on responses

.circleci/config.yml, frontend/src/pages/TrainingReportForm/index.js
=> push cflinuxfs4 to testing sites.

deployment_config/prod_vars.yml, deployment_config/staging_vars.yml
```yml
similarity_api_instances: 1
similarity_api_memory: 1GB
similarity_api_disk_quota: 5GB
```
^ these were missing from `prod_vars.yml` and `staging_vars.yml`, so deployment to those environments will fail. This PR resolves that.
=> Add required vars for prod/staging for similarity

src/lib/maintenance/db.js, src/lib/maintenance/db.nextBlock.test.js, src/lib/maintenance/db.test.js, src/lib/orderGoalsBy.js, src/lib/orderGoalsBy.test.js
Deploys to prod are blocked by CI test coverage thresholds
=> [No ticket] Add some tests to increase test coverage past threshold

src/tools/logicalDataModel.ts
- Added more coverage for validation
-- Column references
-- Column types for type mismatch
- Added better support for numeric fields
=> [TTAHUB-2252] Logical Data Model enhancements from Generic Refactor

.gitignore, src/queries/fei-goals.sql
Query added to /src/queries dir for reuse and integration into future JDI (Jorge Data Interface)
- Run query
- Run query using any combination of the JDI flags
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2250
=> [TTA-2250] fei goals query for JDI

frontend/src/App.scss, frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/components/DisplayNextSteps.js, frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/components/LogLine.js, frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/components/__tests__/DisplayNextSteps.js, frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/components/__tests__/LogLine.js, frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/index.js
Create/finish the "view" component for the communication log.
Make sure that the log matches the mockup and functions as expected
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2242
=> [TTAHUB-2242] Finish "View communication log" component

src/lib/migration.js, src/lib/migration.test.js, src/migrations/20231115000000-revise-reason.js
Change "Planning/Coordination (also TTA Plan Agreement)"  to "Planning/Coordination" in ActivityReports.reason & EventReportPilots.data.reasons
run migration, check data in DB for ActivityReports.reason & EventReportPilots.data.reasons
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2141
=> [TTAHUB-2141] revise the "reason" of "Planning/Coordination (also TTA Plan Agreement)"

frontend/src/components/GoalCards/GoalDataController.js, frontend/src/components/GoalCards/__tests__/GoalDataController.js, frontend/src/fetchers/__tests__/communicationLog.js, frontend/src/fetchers/communicationLog.js, frontend/src/pages/Landing/index.scss, frontend/src/pages/RecipientRecord/pages/CommunicationLog.js, frontend/src/pages/RecipientRecord/pages/__tests__/CommunicationLog.js, frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js, frontend/src/widgets/RttapaUpdates.css, frontend/src/widgets/RttapaUpdates.js, frontend/src/widgets/__tests__/RttapaUpdates.js, src/routes/communicationLog/handlers.test.js, src/routes/communicationLog/handlers.ts, src/scopes/communicationLog/index.test.js, src/scopes/communicationLog/index.ts, src/scopes/communicationLog/purpose.ts, src/services/communicationLog.test.js, src/services/communicationLog.ts
Add a table to the RTR > RTTAPA page displaying recent communication logs where purpose = "Rttapa updates"
Verify empty state of table. Create some communication logs. Verify that they display in the table accurately.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2247
=> [TTAHUB-2247] RTTAPA update table

frontend/src/pages/SessionForm/pages/__tests__/supportingAttachments.js, frontend/src/pages/SessionForm/pages/supportingAttachments.js
Found during demo fix last bullet point to be:
"other non-resource items not available online"
- Review code
- All tests pass
- Check language in UI
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2154
=> [TTAHB-2154] Fix session attachment langue

src/lib/updateGrantsRecipients.js, src/lib/updateGrantsRecipients.test.js, temp/grant_award.xml
Grant id 12128 needs to be updated in the Hub to reflect its correct state code, which is "OH". This PR creates a structure to apply this change during processing.
Make sure the tests pass.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2126
- [n/a] Staging smoke test completed
=> [TTAHUB-2126] Apply a patch for a grant with a 'PA' state code.

frontend/src/pages/RecipientRecord/pages/MergeGoals/components/GoalMergeGuidanceDrawer.js
Update the guidance drawer for merge goals
=> Update guidance drawer for merge goals frontend

frontend/src/pages/TrainingReportForm/pages/completeEvent.js
Fix spelling error on TR.
Make sure spelling error is corrected.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2317
=> [TTAHUB-2317] Spelling error

frontend/src/App.scss, frontend/src/components/WidgetContainer.js, frontend/src/pages/RecipientRecord/pages/CommunicationLog.js, frontend/src/pages/RecipientRecord/pages/components/CommunicationLogTable.js
Small fix from UI review on communication log
Confirm the communication log table is constrained to whatever the maxw-widescreen is
=> [NO TICKET] Add max width to communication log

frontend/src/pages/Admin/index.js
Move "Training reports" and "diag" up a section in the admin panel.
Confirm the buttons appear in the correct section (per the ticket) and are alphabetical.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2364
=> [TTAHUB-2364] Rearrange admin buttons

frontend/src/fetchers/__tests__/activityReports.js, frontend/src/fetchers/activityReports.js, frontend/src/pages/ActivityReport/Pages/__tests__/activitySummary.js, frontend/src/pages/ActivityReport/Pages/activitySummary.js, frontend/src/pages/ActivityReport/Pages/activitySummary.scss, frontend/src/pages/ActivityReport/__tests__/index.js, frontend/src/pages/ActivityReport/__tests__/localStorage.js, frontend/src/pages/ActivityReport/index.js, frontend/src/pages/ActivityReport/testHelpers.js, src/routes/activityReports/handlers.js, src/routes/activityReports/handlers.test.js, src/routes/activityReports/index.js
When creating a recipient AR we now allow the user to select a group that will pre fill the list of recipients. If the pre filled list of recipients is altered in anyway (add/remove). The user is informed that they have modified the group recipients and will be given the option to start over.
**NOTE 12/07/2023:** Right now we are getting all groups by region regardless of shared users as this change is still pending on the BE. **ATM the FE can be reviewed.**
- Review all code.
- Create a recipient report and test the workflow from the UX Workflow:
https://www.figma.com/proto/zciEyTLd2MeSK7z5YVKdbF/Create-AR-and-TR-session-from-%22my-group%22?page-id=1%3A52&type=design&node-id=531-7254&viewport=-848%2C-3704%2C0.25&t=GBVp5tULq3N2QVO3-1&scaling=min-zoom&starting-point-node-id=531%3A7254&show- …
=> [TTAHUB-2317] AR groups

src/migrations/20231213210654-goalusers.js, src/migrations/20231213210654-objectiveusers.js
Change needed to correctly support case where merge data already exists
migration succeeds on staging data
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2402
=> [TTAHUB-2402] Migration issue with existing merged goals

frontend/src/components/GoalForm/ObjectiveFiles.js, frontend/src/pages/SessionForm/pages/sessionSummary.js
Capitalized TTA in 2 files that had the tooltip text for non-link resources.
Look at objectives section of activity report form or goal creation form. Look at the second bullet for the tooltip next to the field labelled "Did you use any TTA resources that aren't available as link?". TTA should be capitalized.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2309
=> "TTA" in the tooltip for non-link resources needs to be capitalized

frontend/src/pages/Admin/UserSection.js, src/services/accessValidation.js, src/services/currentUser.js
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2414
=> [TTAHUB-2414] Check formUser.id before using it

src/middleware/authMiddleware.js, src/services/accessValidation.js
=> [TTAHUB-2414] More auth middleware fixes

src/services/accessValidation.test.js
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2414
=> Fix validate authforaccess test

src/middleware/authMiddleware.js
We handled an auth check where the user ID was invalid input for a query, however, we need to make sure that we haven't already responded to the client
=> TTAHUB-2414 Additional patching of bad user ID input

src/lib/apiErrorHandler.js
In the handleErrors function, log the connection pool so we can better diagnose timeout/pool related errors
=> Log connection pool in the case of connection error

src/lib/updateGrantsRecipients.js, src/lib/updateGrantsRecipients.test.js, temp/grant_award.xml
Updates grant ids 10291 and 14869 with the correct state ("PW")
Make sure the tests pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2334
=> [TTAHUB-2334] Patch incorrect state code for Palau

frontend/src/hooks/__tests__/useFilters.js, frontend/src/pages/Admin/__tests__/Courses.js, frontend/src/pages/Admin/__tests__/Email.js, frontend/src/pages/ApprovedActivityReport/__tests__/helpers.js
- Main is below the coverage threshold for FE tests
- Here are some tests to raise the coverage
Tests pass
=> add tests for coverage

bin/run-owasp-scan
=> Update OWASP image

src/queries/class-goal-use.sql, src/queries/fake-class-goal-use.sql
Added two new JDI queries:
- class-goal-use.sql
- fake-class-goal-use.sql
run the queries using the description provided in each file for how to use it.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2587
=> [TTAHUB-2587] Data Request - Approved Activity Reports with CLASS Goal

src/queries/class-goal-dataset.sql
Add JDI query
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2631
=> [TTAHUB-2631] Data Pull - Goals dataset for CLASS analysis

frontend/src/components/GoalForm/index.js
"You are selected an existing goal" <> "You are selecting an existing goal"
Oops.
Language is correct on the goal nudge
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1942
=> Fix grammar error in goal nudge

src/goalServices/getGoalIdsBySimiliarity.test.js
Somehow these changes were left out of my other PR. Not sure what happened there. This is to get CI passing again.
This change in a nutshell: The changes to the rollup logic require these changes to the test.
All tests should pass.
* https://jira.acf.gov/browse/TTAHUB-2128
=> [TTAHUB-2128] Small fix to tests

src/scopes/goals/goalName.ts, src/scopes/goals/index.js, src/scopes/goals/index.test.js
Add a goal name filter to the goal scopes (backend only)
Evaluate the code. You can attach "logging: console.log" to the options passed to the Goal.findAlls added to the test to see the SQL generated if that helps evaluate the correctness. Ensure the test adequately covers the use case.
* https://jira.acf.gov/browse/TTAHUB-2643
=> [TTAHUB-2643] Add goal name filter to goal scopes

src/migrations/20240321002253-create-goals-for-completed-sessions.js
- Sanity check the logic.
- If it looks good, running the migration against recent prod data should result in 57~ new goals.
* https://jira.acf.gov/browse/TTAHUB-2564
=> [TTAHUB-2564] Migration, historical TR goals for completed sessions

.circleci/config.yml, frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
* https://jira.acf.gov/browse/TTAHUB-2751
=> [TTAHUB-2751] Goals and objectives button re-render support issue

src/migrations/20240403000000-reopen-closed-FEI-goals.js
Support request to reopen am merge some goals
run migration, verify on site
* [TTAHUB-2780](https://jira.acf.gov/browse/TTAHUB-2780)
=> [TTAHUB-2780] Reopen region 6 closed FEI goals

.circleci/config.yml, bin/run-owasp-scan, docker-compose.override.yml
Update to supported image/CI machine
DSS passes
=> Fix OWASP image issue

src/goalServices/changeGoalStatus.ts, src/goalServices/closeMultiRecipientGoalsFromAdmin.test.js, src/goalServices/goalUpdate.test.js, src/goalServices/goals.js, src/routes/admin/goal.ts, src/routes/goals/handlers.js
* https://jira.acf.gov/browse/TTAHUB-2682
=> [TTAHUB-2682] Use changeGoalStatus when assigning close suspend reason and context

frontend/src/pages/RegionalDashboard/components/TrainingReportDashboard.js, frontend/src/widgets/TotalHrsAndRecipientGraph.js
- On the graph above, update "Hours reported on training report sessions" to "Hours reported on Training Report sessions"
- Update "Hours" to "Number of hours"
Also, add a filename to the "Total TTA hours" graph on the regional dashboard for activity reports
* https://jira.acf.gov/browse/TTAHUB-2776
=> [TTAHUB-2776] Update labels on TR dashboard

.circleci/config.yml, frontend/package.json, frontend/src/components/GoalCards/GoalCard.js, frontend/src/components/GoalCards/GoalCards.js, frontend/src/components/GoalForm/Form.js, frontend/src/components/GoalForm/index.js, frontend/src/components/ReopenReasonModal.js, frontend/src/components/__tests__/ReopenReasonModal.js, frontend/src/fetchers/goals.js, frontend/yarn.lock, package.json, packages/common/package.json, packages/common/src/constants.js, similarity_api/src/Procfile, src/goalServices/goals.js, src/routes/goals/handlers.js, src/routes/goals/index.js, src/services/recipient.js, tests/api/goals.spec.ts, tests/api/recipient.spec.ts, yarn.lock
* https://jira.acf.gov/browse/TTAHUB-2793
=> [TTAHUB-2793] Reopen goal UI

bin/prod-style-server
- Add messaging to show progress
- change bash flags to fail on any error
Run CI, see new output
* https://jira.acf.gov/browse/TTAHUB-2920
=> [TTAHUB-2920] Dynamic Security Scan: Better error handling to aid in identifying CI issue

.circleci/config.yml
ARM builds are flaky, switch back to AMD
* https://jira.acf.gov/browse/TTAHUB-2922
=> [TTAHUB-2922] Switch DSS arch from ARM to AMD

src/lib/migration.js, src/lib/migration.test.js, src/migrations/20231206210453-update-flags-for-user.js, src/migrations/20231218150056-remove-communication-log-feature-flag.js, src/migrations/20240205192219-remove-goal-source-flag.js, src/migrations/20240215183516-remove-rttapapilot.js, src/migrations/20240215194008-remove-rttapa-form-flag.js, src/migrations/20240426130641-remove-three-flags.js
Change function signature to allow passing the list of feature flags
- load an old backup
- run migrations
* https://jira.acf.gov/browse/TTAHUB-2430
=> [TTAHUB-2430] Fix `updateUsersFlagsEnum`

frontend/src/pages/RecipientRecord/pages/components/ClassReview.js, frontend/src/pages/RecipientRecord/pages/components/__tests__/ClassReview.js
Update monitoring text from "Competetive" to "Competitive"
Go to RTR Profile page, find recipient grant with "below competitive" finding.
* https://jira.acf.gov/browse/TTAHUB-2905
=> [TTAHUB-2905] Update text "Competetive" to "Competitive"

.circleci/config.yml
Finish updating from circleci name spaces to cimg name spaces for containers used during CI
CI jobs run successfully
* https://jira.acf.gov/browse/TTAHUB-2556
=> [TTAHUB-2556] Migrate to cimg Namespace in CircleCI Pipelines

frontend/src/pages/RecipientRecord/pages/components/ClassReview.js, frontend/src/pages/RecipientRecord/pages/components/MonitoringReview.js
Open links to HSES Monitoring & HSES CLASS in new tabs (you can find them on the recipient profile pages)
Confirm links open in new tabs
* https://jira.acf.gov/browse/TTAHUB-2702
=> [TTAHUB-2702] Open monitoring data links in new tabs

README.md, src/lib/programmaticTransaction.test.js, src/lib/programmaticTransaction.ts
Adding a tool to aid in writing tests. It rolls back all modifications to any table in the audit log system from the point of the snapshot until the rollback is called. 
Run the tests, only functional in non-production. Performs the opposite db operations in reverse order.
* https://jira.acf.gov/browse/TTAHUB-3035
=> [TTAHUB-3035] Programmatic Transaction

frontend/src/components/Navigator/ActivityReportNavigator.js, frontend/src/components/Navigator/__tests__/ActivityReportNavigator.js
Fix bug where sometimes we'd skip saving if a goal was removed and no goal replaced it
Confirm cases in Jira are all addressed (from both save and save draft perspectives)
* https://jira.acf.gov/browse/TTAHUB-2982
=> [TTAHUB-2982] Fix removing a goal and objective in draft ARs aren't saving

deployment_config/prod_vars.yml
Add a missing environment variable for production
No tests needed.
* https://jira.acf.gov/browse/TTAHUB-2307
=> [TTAHUB-2307] Fix missing variable for production

.circleci/config.yml, frontend/src/pages/ResourcesDashboard/__tests__/index.js, frontend/src/pages/ResourcesDashboard/index.js, frontend/src/widgets/ResourcesDashboardOverview.js, frontend/src/widgets/__tests__/ResourcesDashboardOverview.js, src/services/dashboards/resource.js, src/services/dashboards/resourceFlat.test.js
Add the iPD courses widget, and the SQL behind it:
* Look at the SQL and make sure it looks correct to you.
* Make sure the widget looks like it does in the figma: https://www.figma.com/design/4ostowet7GTxvqrePDdIWp/Display-iPD-resources-on-resource-dashboard?node-id=218-11366&t=dJNwYDr4jTf4Q8oL-1
* https://jira.acf.gov/browse/TTAHUB-3005
=> [TTAHUB-3005] Resources Dashboard iPD courses widget

.env.example, README.md, docker-compose.debug.yml, docker-compose.dss.yml, docker-compose.override.yml, docker-compose.test.yml
=> Remove references to FONTAWESOME_NPM_AUTH_TOKEN in our setup documentation

.circleci/config.yml, frontend/src/components/GoalCards/GoalCard.js, frontend/src/components/GoalCards/__tests__/GoalCard.js, src/services/recipient.js, src/services/recipient.test.js
For FEI goals on the RTR we want to display the FEI root causes if applicable.
- Ensure we only show root causes for FEI goals.
- Ensure we show blank root causes if the FEI goal is missing them.
- Make sure we properly adjust the view on smaller browser displays.
* https://jira.acf.gov/browse/TTAHUB-2886
=> [TTAHUB-2886] Display FEI root cause on goal card

config/config.js
Increase pool size for production instance
validate that the config now states 30 for max pool size
=> [TTAHUB-3143] Increase the number of connections in the sequelize pool

src/migrations/20240614000000-r10-clear-all-goals-and-objs.js
This changes how the migration selects a user so that it will select an appropriate user within other environments like dev which have been loaded anonymized datasets.
It should still work the same as before, but also in dev, staging, etc.
No Jira
=> NO JIRA bugfix allow migration to work in non-prod environments

src/models/hooks/activityReport.js
The original implementation of the hook I updated would sometimes commit before finishing all it's work. This is a simple refactor to make sure all the promises are awaited.
Using the most recent prod data, confirm that you can approve the specified report for the user in the Jira ticket.
* https://jira.acf.gov/browse/TTAHUB-3172
=> [TTAHUB-3172] Refactor hook to not commit early when approving a large report

frontend/src/components/Header.js, frontend/src/components/SomethingWentWrong.js, frontend/src/components/SomethingWentWrong.scss, frontend/src/components/__tests__/Header.js, frontend/src/components/__tests__/HeaderUserMenu.js
Small change to have the same font class as other <p> tags.
Verify the change.
* https://jira.acf.gov/browse/TTAHUB-2907
=> [TTAHUB-2907] Fix font for "something went wrong"

config/config.js, src/lib/apiErrorHandler.js, src/routes/transactionWrapper.js
We weren't awaiting the result of the call to `sequelize.transaction` in `transactionWrapper`, so we couldn't catch when it threw.
* https://jira.acf.gov/browse/TTAHUB-3144
=> [TTAHUB-3144] Fix transactionWrapper

deployment_config/prod_vars.yml
See https://jira.acf.gov/browse/TTAHUB-3104. This PR increases prod instances from 3GB to 4GB.
* https://jira.acf.gov/browse/TTAHUB-3104
=> [TTAHUB-3104] Increase prod instance mem: 3gb -> 4gb

src/services/activityReports.js
We had put in place a temporary fix for grant programs back in 2022. This ticket revisits it and removes the un needed function.
- Review code.
- Create a report with multi recipients with multiple programs per recipient.
- Make sure programs display correctly at every step of the approval process.
- Make sure the programs display correctly viewing approved reports and exporting to CSV.
* https://jira.acf.gov/browse/TTAHUB-3083
=> [TTAHUB-3083] Integrate programs retrieve into normal sequelize pattern

src/migrations/20240805181157-remove-commlog-4849.js
A support request came in to delete a communication log.
Validate the query.
* https://jira.acf.gov/browse/TTAHUB-4849
=> [TTAHUB-3264] Support case: remove communication log 4849

src/migrations/20240815000000-remove-dup-aros-via-uploadHandler.js
Sort order is not always consistent unless specified, during testing it was working fine, but failed during deployment.
migration completes successfully 
* https://jira.acf.gov/browse/TTAHUB-3309
=> [TTAHUB-3309] Fix migration issue

src/queries/fake-fei-goals.sql
remove ghost goals from fake FEI SSDI
* https://jira.acf.gov/browse/TTAHUB-3288
=> [TTAHUB-3288] Remove ghost goals from fake FEI SSDI

.circleci/config.yml, similarity_api/src/requirements.txt
This PR addresses the issues related to CI warnings and dependency management in the `similarity_api` project. The changes include:
1. **Deprecation Warnings**: Updated the dependencies to remove warnings related to yanked versions and deprecations due to the legacy `setup.py install` method.
2. **Pyproject.toml**: Added a `pyproject.toml` file to modernize the dependency management and ensure compatibility with PEP 517/518 standards.
3. **CI Enhancements**: Adjusted the CI pipeline to eliminate warnings and ensure smooth builds by upgrading dependencies and addressing issues with deprecated methods.
1. **CI Verification**:
- Ensure that the CircleCI pipeline runs successfully without any warnings related to yanked versions, deprecations, or missing `pyproject.toml`.
- Verify that all …
=> [TTAHUB-3110] Fix/Enhance similarity_api CI and Dependency Management

.circleci/config.yml
=> Remove PR_TITLE

.circleci/config.yml
Adds debugging to the deploy step to help troubleshoot recent failures.
Make sure the PR builds
=> Add debugging to the deploy step

.circleci/config.yml
=> Test deployment message

frontend/src/components/GoalForm/index.js
Fix copy-paste type breaking goal source
make an ar with an FEI and set the root cause
* https://jira.acf.gov/browse/TTAHUB-3364
=> [TTAHUB-3364] Fix copy paste typo

src/routes/ssdi/handlers.test.js, src/routes/ssdi/handlers.ts
the route handler needed to have the format of region.in
=> [NO-JIRA]  SSDI QA Dashboard intigration

frontend/src/components/GoalForm/GoalNudge.js, frontend/src/components/GoalForm/__tests__/GoalNudge.js
Label for goal drop down should say "OHS Standard Goals."
* https://jira.acf.gov/browse/TTAHUB-3482
=> [TTAHUB-3482] Change checkbox label on the recipient record/create goals form

src/migrations/20241016000000-cleanup-old-table-referances.js
When tables are removed without using the helper function located in src/lib/migration.js removeTables().
migration passes
The following query should have no results.
```sql
WITH all_tables AS (
SELECT table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE' AND table_schema NOT IN ('information_schema', 'pg_catalog')
),
all_functions AS (
SELECT routine_name
FROM information_schema.routines
WHERE routine_type = 'FUNCTION' AND specific_schema NOT IN ('information_schema', 'pg_catalog')
)
SELECT f.routine_name
FROM all_functions f
LEFT JOIN all_tables t
ON f.routine_name LIKE 'ZALNoTruncateF' || t.table_name
OR f.routine_name LIKE 'ZALNoDeleteF' || t.table_name
OR f.routine_name LIKE 'ZALNoUpdateF' || t.table_name
WHERE t.table_name IS NULL
AND (f.routine_name LIKE …
```
=> [TTAHUB-2591] Cleanup old table references

frontend/src/pages/QADashboard/__tests__/index.js, frontend/src/pages/QADashboard/index.js, src/services/currentUser.js
Fix incorrect number of reports on QA.
Make sure the delivery method header shows the correct number of reports (not 0).
=> Fix incorrect number of reports on QA

src/services/ssdi.ts
=> Debug for QA Dashboard

src/queries/api/dashboards/qa/dashboard.sql
All roles need to be displayed to keep counts correct
view the QA dashboard
* https://jira.acf.gov/browse/TTAHUB-3582
=> [TTAHUB-3582] All roles

frontend/src/fetchers/ssdi.js, frontend/src/pages/QADashboard/__tests__/index.js, frontend/src/pages/QADashboard/index.js, src/queries/api/dashboards/qa/class.sql, src/queries/api/dashboards/qa/dashboard.sql, src/queries/api/dashboards/qa/fei.sql
Public groups did not work prior to this change for SSDI filters
Filter using a group
* https://jira.acf.gov/browse/TTAHUB-3598
=> [TTAHUB-3598] QA Dashboard groups filter not working for public groups

frontend/src/components/AvatarGroup.js, frontend/src/components/FeedArticle.js, frontend/src/components/FileUploader/DeleteFileModal.js, frontend/src/components/FileUploader/FileTable.js, frontend/src/components/HeaderUserMenu.js, frontend/src/pages/AccountManagement/index.js, frontend/src/pages/SessionForm/pages/__tests__/sessionSummary.js
- Change heading level of user name in the avatar dropdown
- Add a screen reader only tag to the Supporting Attachments actions header
- Remove empty list item from semantic tree in avatar menu
- Confirm empty list item in usa-modal footer is not an accessibility issue
- Update aria label on delete file modal to be more succinct
- Remove h4 from drawer component when title is absent
- Confirm that the user menu and the avatars in the header and on the account management page still look and function correctly and that the heading is an appropriate level (h2)
- Confirm that deleting files still works correctly and that there are no empty cells in the file table
- Confirm that the drawers still look correct.
* https://jira.acf.gov/browse/TTAHUB-3436
=> [TTAHUB-3436] Fix assorted markup issues (nesting, empty tags)

frontend/src/fetchers/ssdi.js, src/queries/api/dashboards/qa/class.sql, src/queries/api/dashboards/qa/dashboard.sql, src/queries/api/dashboards/qa/fei.sql, src/queries/api/dashboards/qa/no-tta.sql
Distinct is not working as expected, switching to group by
run qa dashboard
* https://jira.acf.gov/browse/TTAHUB-3597
=> [TTAHUB-3597] QA Dashboard FEI root causes looks to not be counting or filtering correctly

src/migrations/20241108102623-GrantRelationshipToActive.js
This simply add a goal template for the montior goal with the text from the jira. The idea here is once we have an ID it will never change and we can use it in the CRON job query.
- Review the migration.
- Make sure the migration works in both directions.
* https://jira.acf.gov/browse/TTAHUB-3513
=> [TTAHUB-3513] Add goal template for monitor goal so we have an id to use in CRON

src/migrations/20241031203552-GrantRelationshipToActive.js
Deployed environments do not have a postgres user to change ownership too, causing migration and all subsequent migrations to fail.
Migration succeeds on deployed environments 
* https://jira.acf.gov/browse/TTAHUB-3628
=> [TTAHUB-3628] Migration deployment issue

src/scopes/index.test.js
Adds coverage for `src/scopes/index.js`, specifically the `mergeIncludes` function.
* https://jira.acf.gov/browse/TTAHUB-3547
=> [TTAHUB-3547] Coverage >= 90% src/scopes/index.js

src/scopes/goals/index.test.js
Adds coverage for:
- `src/scopes/goals/status`
- `src/scopes/goals/ttaType`
* https://jira.acf.gov/browse/TTAHUB-3549
=> [TTAHUB-3549] Coverage >= 90% scopes/goals: status, ttaType

src/scopes/communicationLog/index.test.js
Adds coverage to `src/scopes/communicationLog/communicationDate`
* https://jira.acf.gov/browse/TTAHUB-3548
=> [TTAHUB-3548] Coverage >= 90% src/scopes/communicationLog/communicationDate

frontend/package.json, frontend/src/pages/RegionalDashboard/__tests__/index.js, frontend/src/pages/RegionalGoalDashboard/__tests__/index.js, frontend/src/widgets/DeliveryMethodGraph.js, frontend/src/widgets/LineGraph.js, frontend/src/widgets/TotalHrsAndRecipientGraph.js, frontend/src/widgets/__tests__/LineGraph.js, frontend/src/widgets/__tests__/TotalHrsAndRecipientGraph.js, frontend/yarn.lock, package.json, packages/common/package.json, packages/common/src/constants.js, src/widgets/totalHrsAndRecipientGraph.js, tests/api/widgets.spec.ts, yarn.lock
There were bugs on the line graph component relating to which line was controlled by which checkbox. I reorganized that code a little to be less dependent on array order.
Confirm that the graphs on the goal dashboard, regional dashboard, and QA dashboard appear, that the lines are labelled correctly compared to the data returned from the backend, and that the checkbox controls manipulate the proper line.
* https://jira.acf.gov/browse/TTAHUB-3609
=> [TTAHUB-3609] Refactor line graph checkbox controls

src/routes/goalTemplates/handlers.test.js
```bash
--------------------------------------------|---------|----------|---------|---------|-------------------
File                                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------------------------------|---------|----------|---------|---------|-------------------
All files                                   |   46.27 |     9.39 |   30.31 |    47.7 |                   
src/routes/goalTemplates                   |     100 |      100 |     100 |     100 |                   
handlers.ts                               |     100 |      100 |     100 |     100 |                   
--------------------------------------------|---------|----------|---------|---------|-------------------
```
* https://jira.acf.gov/browse/TTAHUB-3561
=> [TTAHUB-3561] Coverage >= 90% src/routes/goalTemplates/handlers.js

src/policies/group.test.js
```bash
--------------------|---------|----------|---------|---------|-------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------|---------|----------|---------|---------|-------------------
All files           |     100 |      100 |     100 |     100 |                   
src/policies       |     100 |      100 |     100 |     100 |                   
group.ts          |     100 |      100 |     100 |     100 |                   
--------------------|---------|----------|---------|---------|-------------------
```
* https://jira.acf.gov/browse/TTAHUB-3566
=> [TTAHUB-3566] Coverage >= 90% src/policies/group.js

src/policies/sessionReport.test.js
```bash
--------------------|---------|----------|---------|---------|-------------------
File                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------|---------|----------|---------|---------|-------------------
All files           |     100 |      100 |     100 |     100 |                   
middleware         |     100 |      100 |     100 |     100 |                   
scopeConstants.js |     100 |      100 |     100 |     100 |                   
policies           |     100 |      100 |     100 |     100 |                   
sessionReport.js  |     100 |      100 |     100 |     100 |                   
--------------------|---------|----------|---------|---------|-------------------
```
* https://jira.acf.gov/browse/TTAHUB-3567
=> [TTAHUB-3567] Coverage  >= 90% src/policies/sessionReport.js

src/scopes/trainingReports/index.test.js
```bash
--------------------------------------------------------------|---------|----------|---------|---------|----------------------------------------------------------------
File                                                          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                              
--------------------------------------------------------------|---------|----------|---------|---------|----------------------------------------------------------------
All files                                                     |   27.37 |     4.66 |   16.11 |   28.89 |                                                                
src/scopes/trainingReports                                   |   81.57 |      100 |   81.48 |   81.08 | …
```
=> [TTAHUB-3546] Coverage >= 90%: src/scopes/trainingReports utils.js & startDate.js

src/goalServices/reduceGoals.test.ts
* https://jira.acf.gov/browse/TTAHUB-3439
=> [TTAHUB-3439] Coverage >= 90%: src/goalServices/reduceGoals.js

frontend/src/pages/RecipientRecord/pages/Monitoring/components/CitationCard.css, frontend/src/pages/RecipientRecord/pages/Monitoring/components/DescriptionList.css
Citation tab didn't look correct at max breakpoint
Both cards failed to degrade to one column on small screens
=> Fix some CSS on the new monitoring/citaion tab

src/services/goalTemplates.test.js, src/services/goalTemplates.ts
There was a todo statement about extracting some validation logic into its own function. I did that in this PR because it made things easier to test. The rest of this is just normal code coverage.
* https://jira.acf.gov/browse/TTAHUB-3536
=> [TTAHUB-3536] Coverage >= 90% src/services/goalTemplates.js

src/services/resourceQueue.test.js
* https://jira.acf.gov/browse/TTAHUB-3538
=> [TTAHUB-3538] Coverage >= 90% src/services/resourceQueue.js

.github/pull_request_template.md
Adds QA review checkbox to the PR template
Look at the code
* https://jira.acf.gov/browse/TTAHUB-3716
=> [TTAHUB-3716] Add QA review to the PR template

frontend/src/components/GoalCards/components/GoalStatusDropdown.js, src/tools/createMonitoringGoals.js, src/tools/createMonitoringGoals.test.js
Our DB stores statuses as "Not Started" not as "Not started"
Create monitoring goals, create a report for a monitoring goal, then visit the RTTAPA page. You should not see the app crash.
=> Fix monitoring goals script

frontend/src/pages/RecipientRecord/pages/Monitoring/__tests__/index.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/CitationCard.css, frontend/src/pages/RecipientRecord/pages/Monitoring/components/CitationCard.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/DescriptionList.css, frontend/src/pages/RecipientRecord/pages/Monitoring/components/FindingWithinReview.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/ReviewCard.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/ReviewWithinCitation.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/ToggleTtaActivityButton.js
Things were missed, styles were updated, labels were changed, all in order to better match the mockup
- Correctly nested findings under reviews
- Used relative widths instead of a hardcoded one
- Corrected labels in citation card
- Used a line height of 1.5
- Changed the order of category and due date on the citation card
Verify via this slack thread that all changes requested were completed:
https://adhoc.slack.com/archives/C0492R8BN4Q/p1733423942795029
* https://jira.acf.gov/browse/TTAHUB-3534
* https://jira.acf.gov/browse/TTAHUB-3636
=> Update feature flagged monitoring tab based on UI review

src/lib/importSystem/tests/record.test.js
* https://jira.acf.gov/browse/TTAHUB-3704
=> [TTAHUB-3704] Coverage >= 90% src/lib/importSystem/record.ts

src/scopes/goals/index.test.js, src/scopes/goals/participants.js
* https://jira.acf.gov/browse/TTAHUB-3553
=> [TTAHUB-3553] Coverage >= 90% src/scopes/goals/participants.js

frontend/src/components/GoalCards/GoalCard.js, frontend/src/components/GoalCards/GoalCard.scss, frontend/src/components/GoalCards/__tests__/GoalCard.js, frontend/src/components/GoalCards/components/GoalStatusDropdown.js, frontend/src/components/Tooltip.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/DescriptionItem.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/FindingWithinReview.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/NoTtaProvidedAgainst.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/ReviewCard.js, frontend/src/pages/RecipientRecord/pages/Monitoring/components/SpecialistTags.js
- Make ```<Tag>``` component styles consistent in the recipient record
- Fix the spacing under the objectives in "FindingWithinReview" section
- Rely on grid instead of margin to handle spacing between description lists
- "No TTA..." message is restyled (italics removed, grey border to match objectives section)
Confirm the above are complete 
* https://jira.acf.gov/browse/TTAHUB-3635
=> Update css with design review fixes and consistency changes

src/policies/communicationLog.test.js
* https://jira.acf.gov/browse/TTAHUB-3565
=> [TTAHUB-3565] Coverage >= 90% src/policies/communicationLog.ts

src/models/grantRelationshipToActive.js, src/models/tests/grantRelationshipToActive.test.js
* https://jira.acf.gov/browse/TTAHUB-3576
=> [TTAHUB-3576] Coverage >= 90% src/models/grantRelationshipToActive.js

src/tools/processData.js
Updates seeded users.
* https://jira.acf.gov/browse/TTAHUB-3726
=> [TTAHUB-3736] Update seeded users during the data obfuscation process.

frontend/src/components/ClassScoreBadge.js, frontend/src/components/__tests__/ClassScoreBadge.js, frontend/src/pages/RecipientRecord/pages/components/__tests__/ClassReview.js
Update the following threshold: 
```
2.3 for the Instructional Support domain for CLASS® reviews conducted through July 31, 2025 2027, and 2.5 for those conducted on or after Aug. 1, 2025 2027.
```
Confirm the date has been updated
* https://jira.acf.gov/browse/TTAHUB-3715
=> [TTAHUB-3715] Change date and update tests for how thresholds are met

frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js, frontend/src/pages/ActivityReport/Pages/Review/Submitter/__tests__/index.js, frontend/src/pages/ActivityReport/Pages/Review/Submitter/index.js, frontend/src/pages/ActivityReport/Pages/components/GoalForm.js, frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js, frontend/src/pages/ActivityReport/Pages/components/Objective.js, frontend/src/pages/ActivityReport/Pages/components/Objectives.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js, src/goalServices/reduceGoals.ts, src/services/citations.ts
**NOTE:** Before testing move the citations start date back in the src\services\citaion.js to ensure you get some citations to populate in the drop down.
The primary focus of this PR is to add an alert and error, for grants missing citations when the only goal on the report is a monitoring goal.
1. The warning shows on the goals and objectives page right above the citations drop down and should list any recipients that fit this criterica.
2. The error on the review and submit page and also shows the list of recipients missing citations and prevents submitting until its fixed.
In addition this fixes some other issues I found:
1. Weird case if you had two grants with citations but only saved a citation for one on the objective (server side error that would fail to save any citations).
2. …
=> [TTAHUB-3627] Add citation alerts

src/models/tests/goalTemplateFieldPrompt.test.js
* https://jira.acf.gov/browse/TTAHUB-3574
=> [TTAHUB-3574] Coverage >= 90% src/models/goalTemplateFieldPrompt.js

src/widgets/regionalGoalDashboard/goalsPercentage.test.js
* https://jira.acf.gov/browse/TTAHUB-3579
=> [TTAHUB-3579] Coverage >= 90% src/widgets/regionalGoalDashboard/goalsPercentage.ts

src/scopes/activityReport/deliveryMethod.js, src/scopes/activityReport/index.test.js
* https://jira.acf.gov/browse/TTAHUB-3557
=> [TTAHUB-3557] Coverage >= 90% src/scopes/activityReport/deliveryMethod.js

src/routes/testingOnly/handlers.test.js
* https://jira.acf.gov/browse/TTAHUB-3560
=> [TTAHUB-3560] Coverage >= 90% src/routes/testingOnly/handlers.ts

src/policies/event.test.js
* https://jira.acf.gov/browse/TTAHUB-3568
=> [TTAHUB-3568] Coverage >= 90% src/policies/event.js

src/lib/stream/tests/zip.test.js
* https://jira.acf.gov/browse/TTAHUB-3699
=> [TTAHUB-3699] Coverage >= 90% src/lib/stream/zip.ts

src/models/tests/collaboratorType.test.js
* https://jira.acf.gov/browse/TTAHUB-3573
=> [TTAHUB-3573] Coverage >= 90% src/models/collaboratorType.js

src/lib/maintenance/import.test.js, src/lib/maintenance/import.ts
* https://jira.acf.gov/browse/TTAHUB-3702
=> [TTAHUB-3702] Coverage >= 90% src/lib/maintenance/import.ts

src/queries/dataRequests/internal/monthly-delivery-report.sql
- Add grant replacement logic to ssdi report
* https://jira.acf.gov/browse/TTAHUB-3734
=> [TTAHUB-3734] Data alignment

src/middleware/checkIdParamMiddleware.js, src/middleware/checkIdParamMiddleware.test.js
* https://jira.acf.gov/browse/TTAHUB-3570
=> [TTAHUB-3570] Coverage >= 90% src/middleware/checkIdParamMiddleware.js

src/widgets/regionalGoalDashboard/topicsByGoalStatus.test.js, src/widgets/regionalGoalDashboard/topicsByGoalStatus.ts
* https://jira.acf.gov/browse/TTAHUB-3580
=> [TTAHUB-3580] Coverage >= 90% src/widgets/regionalGoalDashboard/topicsByGoalStatus.ts

src/lib/stream/tests/buffer.test.js
* https://jira.acf.gov/browse/TTAHUB-3696
=> [TTAHUB-3696] Coverage >= 90% src/lib/stream/buffer.ts

src/lib/maintenance/db.nextBlock.test.js, src/lib/maintenance/db.test.js
* https://jira.acf.gov/browse/TTAHUB-3701
=> [TTAHUB-3701] Coverage >= 90% src/lib/maintenance/db.js

src/models/grant.js, src/models/tests/grant.test.js
* https://jira.acf.gov/browse/TTAHUB-3575
=> [TTAHUB-3575] Coverage >= 90% src/models/grant.js

.circleci/config.yml, src/services/s3Queue.test.js, src/services/scanQueue.js, src/services/scanQueue.test.js
* https://jira.acf.gov/browse/TTAHUB-3542
* https://jira.acf.gov/browse/TTAHUB-3544
=> [TTAHUB-3542] [TTAHUB-3544] Coverage >= 90% src/services/s3Queue.js & src/services/scanQueue.js

.circleci/config.yml
missing \
deploy will now work without error
=> Config typo

src/services/sessionReports.test.js, src/services/sessionReports.ts
* https://jira.acf.gov/browse/TTAHUB-3543
=> [TTAHUB-3543] Coverage >= 90% src/services/sessionReports.ts

src/lib/stream/encoding.ts, src/lib/stream/tests/encoding.test.js
* https://jira.acf.gov/browse/TTAHUB-3697
=> [TTAHUB-3697] Coverage >= 90% src/stream/encoding.ts

src/routes/groups/handlers.test.js
test coverage for group/handlers
* https://jira.acf.gov/browse/TTAHUB-3563
=> Add tests for group handlers

src/lib/mailer/logNotifications.test.js
it's all at 100 now
* https://jira.acf.gov/browse/TTAHUB-3736
=> coverage for logNotifications.js

src/routes/courses/handlers.test.js, src/routes/courses/handlers.ts
it's all at 100 now
* https://jira.acf.gov/browse/TTAHUB-3562
=> Add coverage for course handlers

src/lib/mailer/index.js, src/lib/mailer/index.test.js, src/lib/mailer/trainingReportTaskDueNotifications.test.js
Increase code coverage to 90% on src\lib\mailer\index.js.
- Review all code changes.
- Make sure all tests pass and the coverage meets the new standard.
* https://jira.acf.gov/browse/TTAHUB-3250
=> [TTAHUB-3250] Increase code coverage on src\mailer\index.js

src/services/communicationLog.test.js, src/services/communicationLog.ts
- Convert the value from a string to a date before sorting
Use the following URL on a server with production or PII data: /recipient-tta-records/910/region/4/communication
* https://jira.acf.gov/browse/TTAHUB-3761
=> [TTAHUB-3761] Sort by Date not String

deployment_config/dev_vars.yml, deployment_config/prod_vars.yml, deployment_config/sandbox_vars.yml, deployment_config/staging_vars.yml
Scale up storage to prevent crash during deployment
deployments should not crash with the error: No space left on device
* https://jira.acf.gov/browse/TTAHUB-3604
=> [TTAHUB-3604] scale up storage

src/models/index.js
- Remove listeners
- No longer resent in the logs
* https://jira.acf.gov/browse/TTAHUB-3762
=> [TTAHUB-3762] Remove DB listeners

src/migrations/20250205000001-apply-eo-directives.js
staging has a partial deploy blocking the pipeline, this will fix it
* https://jira.acf.gov/browse/TTAHUB-3884
=> [TTAHUB-3884] Update 20250205000001-apply-eo-directives.js

src/widgets/helpers.js, src/widgets/topicFrequencyGraph.js
Resolve error on TTA History graph in recipient record
- Visit graph with large prod dataset and date range
- Confirm that graph loads
=> Fix case where topic missing

src/lib/transform.js
* https://jira.acf.gov/browse/TTAHUB-3901
=> Fix null title

.circleci/config.yml, src/app.js
=> [TTAHUB-3871] OWASP ZAP hidden files issue

.circleci/config.yml, src/services/communicationLog.ts
Communication log uploads were failing due to invalid SQL generated during a permissions check. It's a bit of a mystery why this code was failing as it is used in several other places without issue. Changing the configuration object passed to the ORM resolved the problem.
Confirm that you can upload files to a communication log
* https://jira.acf.gov/browse/TTAHUB-3937
=> [TTAHUB-3937] Fix bug with communication log uploads

src/scopes/activityReport/index.test.js, src/scopes/activityReport/myReports.js
Prevents the syntax error coming from the db. Adds logging to provide more information on the users and roles that trigger this scenario.
Look at the code. Make sure the tests pass.
* https://jira.acf.gov/browse/TTAHUB-3681
=> [TTAHUB-3681] Prevent sql syntax error.

src/services/dashboards/course.js, src/services/dashboards/course.test.js
Data was being duplicated from the backend due to courses being deleted and re-added. To fix, unnecessary logic was removed and courses were grouped by name throughout, not just in the final reducer.
Confirm the visual anomaly is no longer present (to see the bug, visit https://tta-smarthub-staging.app.cloud.gov/dashboards/ipd-courses and scroll the table all the way over to the right.)
* https://jira.acf.gov/browse/TTAHUB-3927
=> [TTAHU-3927] iPD course table display issue

src/migrations/20250312143130-sync-mailerlog-enum.js
Reintroduce the same migration from 2023/10/23 (`20231023204415-enhance-email-enum.js`), because new values have been added to `constants.js` since then.
- Run the migration, and ensure all MailerLog enums exist.
```sql
SELECT unnest(enum_range(NULL::"enum_MailerLogs_action"));
```
should show:
```bash
collaboratorAssigned
changesRequested
approverAssigned
reportApproved
collaboratorDigest
changesRequestedDigest
approverAssignedDigest
reportApprovedDigest
recipientReportApproved
recipientReportApprovedDigest
trainingReportCollaboratorAdded
trainingReportPocComplete
trainingReportPocVisionGoalComplete
trainingReportPocAdded
trainingReportSessionCreated
trainingReportSessionCompleted
trainingReportEventCompleted
trainingReportTaskDueNotifications
trainingReportEventImported
(19 rows)
```
* …
=> [TTAHUB-3679] Sync MailerLog enums with values in constants.js

frontend/src/components/CommunicationLog/constants.js
Missed this when making the field not required.
Thank you @thewatermethod for pointing this out: `the "isPageComplete" function checks to make sure all the keys in that object have truthy values`
=> [NO-TICKET] Remove default value for results so form can be submitted

.circleci/config.yml
=> [NO-TICKET] Unblock the pipeline due to bad node check

frontend/src/__tests__/Routes.js, frontend/src/setupTests.js
Routes was challenging to write tests for, so we didn't do it for a long time.
This increases our average coverage by a good amount.
=> [NO-TICKET] Add Routes tests

.circleci/config.yml, .vscode/settings.json, automation/configs/processed-restore.yml
* Data import job had some env var parsing issues from recent refactor, specifically leftover code based on the idea of using a branch-per-env.  Removed that and now passing through the targeted environment the same way everywhere.
* The automated nightly job to restore db snapshot into staging was disabled during pen tests, this re-enables it.
* Reworked some pipeline flow, to restore the anonymized db snapshot into staging manually you can run the "restore_db" job, and set the target environment to staging (or any other lower env).
* Automated db job now runs off the CircleCI config in `main` branch, not prod.
* Fix certain jobs triggering on push when they should only trigger through schedule.
* Updated logging and Slack notifications, now going to `#acf-head-start-alerts-lower`
* Ran …
=> [TTAHUB-3780] Misc Build and Automated Job Cleanup

frontend/src/components/Navigator/components/SideNav.js, frontend/src/components/ReadOnlyField.js, frontend/src/components/SharedGoalComponents/__tests__/ObjectivesSection.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js
Fixing a few invalid DOM nesting errors where ULs and Divs were being nested within P tags.
Run the app and notice everything works.
* https://jira.acf.gov/browse/TTAHUB-4065
=> TTAHUB-4065 - Fixes for invalid DOM nesting errors

docs/monitoring-tech.md
Updates the monitoring-tech.md file to remove mentions of auto-closing goals.
* https://jira.acf.gov/browse/TTAHUB-4049
=> Update monitoring-tech.md to remove closing goals

.circleci/config.yml
* Fixup handling of both empty results (no new monitoring goals) and new results
* Run all commands as a single task
* Pass through Slack channel explicitly for easier testing
Ran manual job against staging (no new goals), verified result in private Slack channel
Ran manual job against prod (some new goals), verified result in private Slack channel
* [TTAHUB-4121](https://jira.acf.gov/browse/TTAHUB-4121)
=> [TTAHUB-4121] Monitoring data cron result parsing and Slack messaging

.circleci/config.yml, src/lib/queue.js
* Include redis in the docker configuration used during backend tests.
* Rework the env var parsing for configuring redis (used in local and remote environments) to handle the config used in Circle
* This seems to improve reliability of the backend tests in Circle, it also makes the results more readable (no more stream of errors failing to connect to redis), and more closely mimics the configuration used in deployed environments.
_If there was a reason we were intentionally not running redis here, please let me know.  But as all the tests look to be passing this seems like an improvement._
* Ran through CircleCI, verified the tests still passed and that we no longer see redis connection errors in the backend test logs
* Ran local dev setup to verify no regressions (yarn docker:reset && …
=> [NO-TICKET] Set up redis for tests on CircleCI

.github/pull_request_template.md, src/scopes/activityReport/index.js, src/scopes/activityReport/index.test.js, src/scopes/activityReport/topic.js, src/scopes/communicationLog/index.ts, src/scopes/goals/index.js, src/scopes/goals/topics.js, src/scopes/index.js, src/scopes/trainingReports/index.js, src/scopes/utils.ts
Escaped topic names and validated against known topics
to prevent injection via query parameters.
Look at the code. More detailed instructions were included in the Jira ticket.
* https://jira.acf.gov/browse/TTAHUB-4087
=> [TTAHUB-4087] Fix SQL injection vulnerability in topics filter

frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
Fixes the code so that the "Goal summary" heading is correctly displayed on the Approved ARs page.
1. Go to an approved AR
2. Scroll down to the Goals and Objectives section and notice that "Goal summary" now appears.
* https://jira.acf.gov/browse/TTAHUB-4106
=> TTAHUB-4106 - Fix to make "Goal summary" heading reappear in Approved ARs

.circleci/config.yml, src/tools/queryMonitoringData.js
This changes the current monitoring _goal_ notification to a general monitoring notification and prepends the kind of notification for each.
This one isn't really easy to test as it requires new monitoring imports and slack integrations. The updates source query will make results that were once like:
```
recipient              | region | cnt
-------------------------------------+--------+-----
Tri-County Community Action Agency  |      1 |   1
Virgin Island Department of Human S |      2 |   1
Young Men's Christian Association o |      3 |   1
The Middle Georgia Community Action |      4 |   1
Renewal Unlimited, Inc.             |      5 |   1
AVANCE - San Antonio, Inc.          |      6 |   3
```
look like:
```
recipient                    | region | cnt …
```
=> [TTAHUB-4119] add CLASS to monitoring notifications

.circleci/config.yml
Fix pipeline failure caused by outdated Grype vulnerability DB.
Verify pipeline succeeds
* https://jira.acf.gov/browse/TTAHUB-4179
=> [TTAHUB-4179] Update Grype

.circleci/config.yml, .github/workflows/pr-notifications.yml
This PR updates the Slack notification logic to include more context when a pull request is opened. Specifically, it extracts and includes the PR title, author, and content from the following sections of the PR body:
Description of change
How to test
Issues
This approach replaces the previous reliance on Slack's link unfurling, which was unreliable.
This was tested in a separate channel
* https://jira.acf.gov/browse/TTAHUB-4196
- _Sequence: …
=> Test link unfurling

src/tools/processData.js
Updates to the process data script to reflect the team change.
Verify that the hses id and name are correct.
* https://jira.acf.gov/browse/NO-TICKET
=> [NO-TICKET] Offboard and onboard - HSES, lower environments

src/services/citations.test.js
Fixes a broken test that sneaked into `main`
passes CI tests
* https://jira.acf.gov/browse/TTAHUB-4235
=> [TTAHUB-4235] update test for original grant ID

frontend/src/components/SharedGoalComponents/ObjectivesSection.js, frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalPicker.js
=> [TTAHUB-4099] Fix removing objective

frontend/src/Routes.js, frontend/src/components/PaginationCard.js, frontend/src/components/SiteNav.js, frontend/src/components/TableHeader.js, frontend/src/components/__tests__/PaginationCard.test.js, frontend/src/fetchers/collaboratorReports.ts, frontend/src/pages/CollaborationReports/__tests__/CollabReports.test.js, frontend/src/pages/CollaborationReports/__tests__/CollabReportsLanding.test.js, frontend/src/pages/CollaborationReports/__tests__/CollabReportsTable.test.js, frontend/src/pages/CollaborationReports/components/CollabReports.js, frontend/src/pages/CollaborationReports/components/CollabReportsTable.js, frontend/src/pages/CollaborationReports/index.js, frontend/src/pages/CollaborationReports/index.scss, src/routes/apiDirectory.js, src/routes/collaborationReports/handlers.test.ts, src/routes/collaborationReports/handlers.ts, src/routes/collaborationReports/index.ts, src/services/collaborationReports.ts
Creates a new `Sidebar` nav item to access "Collaboration Reports". When clicked on, the Collaboration Reports landing page will render. The acceptance criteria for this ticket only includes the "empty" state, however changes have been added to add a new api route in the backend to retrieve collab reports ( it is not currently pulling from the DB as there is not yet a model for collab reports). However, the frontend & backend are fully wired up in this way.
Some small tweaks have been made to the existing components `<TableHeader />` & `<PaginationCard>`, however this doesn't alter the default state of those components, and as such existing users of them will not be affected. 
Changes will be merged into the [TTAHUB-3473-collab-report-mvp](https://github.com/HHS/Head-Start-TTADP/tree/TTAHU …
=> [TTAHUB-3999] - Create collab report Landing page

src/services/standardGoals.ts
=> Al logs for green testing

src/migrations/20250728000000-undelete_monitoring_goal.js
A user accidentally deleted a system-created monitoring Goal
Check that Goal ID 102169 has a null `deletedAt` after running?
* https://jira.acf.gov/browse/TTAHUB-4332
=> [TTAHUB-4332] Undelete monitoring goals

.githooks/pre-commit
These are the changes I had to make to our pre-commit script to get it to run for me. Unclear why (I am on a fresh apple silicon mac)
Open to other ideas/feedback
=> Adjust pre commit hook

README.md
Updates README
* https://jira.acf.gov/browse/NO-TICKET
=> [NO-TICKET] Update README.md instuctions

frontend/package.json, frontend/src/pages/ActivityReport/Pages/activitySummary.js, frontend/yarn.lock, package.json, packages/common/README.md, packages/common/package.json, packages/common/src/constants.js, yarn.lock
Part of 4133 although not mentioned was to also update the reason values to the below image:
- Make sure the values match
- Test creating and approving an AR with the new values
=> [TTAHUB-4133] Update reasons for activity

.circleci/config.yml, src/tools/createMonitoringGoals.js, src/tools/createMonitoringGoalsCLI.js
[[TTAHUB-4335]](https://github.com/HHS/Head-Start-TTADP/commit/8c04e236353bd37552894a6eb6a9cc966a90fc41) - Clear buildpack cache cron
[[TTAHUB-4553]](https://github.com/HHS/Head-Start-TTADP/commit/c0064e5b2b3a1ef0018526f92f8477c743f67e5e) - Potential fix for import goal creation and debug logging
* https://jira.acf.gov/browse/TTAHUB-4553
* https://jira.acf.gov/browse/TTAHUB-4335
- N/A Meets accessibility standards (WCAG 2.1 Levels A, AA)
- N/A API Documentation updated
- N/A Boundary diagram updated
- N/A Logical Data Model updated
- N/A [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
- N/A UI review complete
- N/A QA review complete
- _Confirm that Slack notification was sent …
=> [PROD] Monitoring Goal Creation Fix & Buildpack Cache Clear
