HHS/Head-Start-TTADP

- .circleci/config.yml
- frontend/package.json
- frontend/yarn.lock
- package.json
Adds two features to the continuous integration pipeline:
- **static security scan via `yarn audit`** - The ternary operator is necessary because `yarn audit` returns a non-zero exit code if issues of any severity level are found. We only want to fail the job though if moderate or higher level vulnerabilities are found. Moderate vulnerabilities return an exit code of 4. More info on this is available in the [yarn docs](https://classic.yarnpkg.com/en/docs/cli/audit/).
- **code coverage threshold** - Adds BE coverage threshold of 60, and FE coverage threshold of 90.  The BE is set at 60 simply because this is the highest threshold that will pass. I think we should add a ticket to the backlog to write tests to increase the coverage to 70%-80%. Writing new tests to …
> CI: Static Security Scan, Code coverage (#37)

- .circleci/config.yml
- frontend/package.json
- frontend/src/__tests__/App.js
- src/index.js
- src/index.test.js
* Serve the static frontend before applying the auth middleware
* The CSP of the backend (via [helmet](https://helmetjs.github.io/)) forces us to set [INLINE_RUNTIME_CHUNK](https://create-react-app.dev/docs/advanced-configuration/) to false.
1) Login to the sandbox env https://tta-smarthub-sandbox.app.cloud.gov/
**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/4
**Checklist**
- API methods
- Boundary and Data Flow Diagrams
- [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
- OSCAL templates completed when security controls are implemented or …
> Fix deployed UI frontend issues (#39)

- .circleci/config.yml
Sorry for the weird commit history here. In 9ff5a0a I accidentally pushed this change directly to main. In 
a7144a1 I undid those changes, but used the wrong git ref in the commit message. 🤦‍♀️   The real changes occur for the final time in 2efc9d4 / PR https://github.com/adhocteam/Head-Start-TTADP/pull/52.
____
We now have access to the permanent cloud.gov organization, so we should move our apps out of the shared prototyping org.
I also updated the cloud.gov sandbox space name, deployer username and password in CircleCI. And @jasalisbury updated the dev space name, username and password. In CircleCI these key names are: CLOUDGOV_DEV_PASSWORD, CLOUDGOV_DEV_SPACE, CLOUDGOV_DEV_USERNAME, CLOUDGOV_SANDBOX_PASSWORD, CLOUDGOV_SANDBOX_SPACE, CLOUDGOV_SANDBOX_USERNAME …
> CD: Deploy to new cloud.gov org (#52)

- .circleci/config.yml
Target the docker image we already pulled
See how [only one docker image is pulled](https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/466/workflows/724e564e-bc1a-429a-9caf-cf87aa6850d4/jobs/1797), vs [earlier](https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/464/workflows/aa08ff8c-2169-4a21-bda1-1b7fa71fb792/jobs/1782), when we were pulling one docker image for the "Pull OWASP ZAP docker image" step and a second image for the "Run OWASP ZAP" step
**Issue(s)**
* closes https://github.com/HHS/Head-Start-TTADP/issues/114
**Checklist**
- [n/a] Documentation updated
- API methods
- Boundary and Data Flow Diagrams
- [Architectural Decision …
> CI: Use one image for dynamic security scan (#54)

- .circleci/config.yml
- .env.example
- README.md
- config/config.js
- cucumber/features/steps/homePageSteps.js
- frontend/yarn.lock
- package.json
- src/index.test.js
- src/middleware/authMiddleware.js
- src/middleware/authMiddleware.test.js
- yarn.lock
Add accessibility scan of all urls to continuous integration pipeline
Accessibility issues were found by the scan and will take some investigation to fix. I created a new issue, https://github.com/HHS/Head-Start-TTADP/issues/159, for this work and to add the `--exit` flag into the axe command. The exit flag will cause the job to fail when an accessibility issue is found.
- See axe accessibility scan run in [recent circle ci job on fork's main](https://app.circleci.com/pipelines/github/adhocteam/Head-Start-TTADP/667/workflows/6a11ff16-119e-4f9b-960e-bc2cd5e25a3c/jobs/2899)
**Issue(s)**
* closes https://github.com/HHS/Head-Start-TTADP/issues/41
**Checklist**
- API methods
- Boundary and …
> CI: Accessibility scan

- package.json
- src/lib/updateGrantsGrantees.js
- src/routes/admin/user.test.js
- src/services/activityReports.test.js
- src/tools/importGrantGranteesCLI.js
* Handle `nil` grant start and end dates
* Add ability to kick off an import via CLI
Production data imports successfully. Ryan tested this on GFE with a production dataset.
**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/380
**Checklist**
- API methods
- Boundary and Data Flow Diagrams
- [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
- OSCAL templates completed when security controls are implemented or modified
> HotFix: Production HSES import failure

- frontend/src/pages/Landing/__tests__/index.js
- frontend/src/pages/Landing/index.js
- frontend/src/setupTests.js
- frontend/src/widgets/Overview.js
- frontend/yarn.lock
- src/app.js
Removes the total grants statistics from the display on the TTA Overview widget. Updates the text for non-grantee statistics to be "Non-grantee entities served". Fixes the export of reports - adding filtering by regions.
- Go to Dev - https://tta-smarthub-dev.app.cloud.gov/
- verify that (of x) is not showing under grants on the TTA overview widget.
- verify that the non-grantee statistic has a changed text.
- the display of the TTA overview widget is now showing for all, admins and non-admins. This can be verified by removing of the  admin permission from yourself in the admin UI, going to activity reports and then refreshing the page. The widget should still be visible. (Please slack me to enable the admin permissions back).
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-143
* …
> Remove total grants statistics from the TTA overview widget (#354)

- frontend/src/pages/ActivityReport/Pages/Review/Approver/Approved.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Approved.js
- src/lib/transform.js
- src/lib/transform.test.js
- src/routes/activityReports/handlers.js
- src/routes/activityReports/handlers.test.js
- src/services/activityReports.js
**TTAHUB-240:**
Updated the column headers for the CSV to be more human-readable
**Admins only** will also now see the goals and objectives with the CSV output.
**TTAHUB-86:**
Always hide the Creator and Manager notes when printing an approved report.
**TTAHUB-240:**
Export a CSV. Confirm the column data has changed. If possible, confirm admins see goals and objectives and non-admins do not.
**TTAHUB-86:**
Print a approved report the Creator and Manager notes section should no longer be visible in the print out.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-240
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-86
- [n/a ] Boundary diagram updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for …
> [TTAHUB-240] Include goals and objectives in CSV download (#360)

- frontend/src/pages/Dashboard/__tests__/index.js
- frontend/src/pages/Dashboard/index.js
- frontend/src/widgets/TopicFrequencyGraph.css
- frontend/src/widgets/TopicFrequencyGraph.js
- frontend/src/widgets/__tests__/TopicFrequencyGraph.js
- src/widgets/topicFrequencyGraph.js
- src/widgets/topicFrequencyGraph.test.js
The dropdown at the top of the Topic/frequency graph was populated with the wrong information. It now extracts roles from the users and collaborators rather than the participant roles.
Feedback from accessibility design review was also incorporated, adding a button to apply the sorting options.
The title was also changed on the page to use the new "analytics" language.
Verify that the topic/frequency graph now contains appropriate values, and that the data can be appropriately filtered.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-258
> [TTAHUB-258]Topic/Frequency Graph filters on specialist roles instead of participants

- frontend/src/components/ButtonSelect.css
- frontend/src/components/ButtonSelect.js
- frontend/src/components/__tests__/ButtonSelect.js
- frontend/src/pages/RegionalDashboard/components/DateRangeSelect.js
- frontend/src/pages/RegionalDashboard/index.js
- frontend/src/widgets/__tests__/TotalHrsAndGranteeGraph.js
- src/policies/activityReport.js
- src/routes/activityReports/handlers.js
- src/routes/activityReports/handlers.test.js
- src/services/activityReports.js
- src/services/activityReports.test.js
Legacy ARs have been imported into the Hub but are not included on CSV downloads. This PR allows admin users to download the CSV's with the legacy data to inspect what was missing in order to decide how to proceed with reconciliation. Non-admin users should experience no change in functionality
The date range select on the dashboard page changed significantly from an earlier, previously unseen mockup. The inputs are spaced apart and function slightly differently, the checkmark behavior has changed, and instructions have been added.
Download CSV's from the Activity Report table (including legacy reports) as an admin. Then, download them as a non-admin. You should see reports included on the CSV as an admin; you should see them not included as a non-admin.
View the regional-dashboard. Use …
> [TTAHUB-322/330] feature flag admin csv export, redo date picker select

- src/services/activityReports.js
- src/services/activityReports.test.js
Due to recent changes, if a user attempts to save a report with first selecting recipient type, they will encounter an error. This is a fix for that.
Start a new report. Jump to "Next Steps" without saving. The report should save.
> fix bug when saving with no AR type selected

- src/lib/transform.js
- src/lib/transform.test.js
- src/routes/activityReports/handlers.test.js
- src/widgets/reasonList.js
- src/widgets/reasonList.test.js
This is a fix where a sorting tie would sometimes cause the Reason List unit test to fail.
Used the calculated "fullName" field on the User model to populate the CSV exports. This field includes abbreviated roles, which are now included on the Creator & Collaborator fields on the CSV.
Run the Reason list unit test.
Export a CSV, preferably one with collaborators. The Creator and Collaborators should be formatted as below.
- In CSV download, the Creator field contains [First Name] [Last Name], [role 1], [role...] 
- In CSV download, the Collaborators field contains [First Name][Last Name], [role 1], [role...] 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-165
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-169
~-[ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)~
~- [ ] API …
> [TTAHUB-165/169] include roles w/author & collaborators on CSV & fix issue where reason list test would sometimes fail. 

- frontend/src/pages/Landing/Filter.js
- frontend/src/pages/Landing/__tests__/Filter.js
We need to make sure that if the filter topic changes that we also clear the condition. The reason is that if they user is switching between date and string filters the previous date filters are NOT valid for strings (BEFORE, IN, AFTER).
Create a report filter for 'Start Date' with the 'before' condition and any date then apply. 
Now switch the topic of the filter to 'Creator'. The condition field should now be cleared as 'before' is not valid for a string field like creator. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-193
~- [ ] Staging smoke test completed~
> TTAHUB-193: Clear Condition on Topic Change (#431)

- frontend/src/components/MultiSelect.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/nextSteps.js
This adds the spellcheck=true attribute to some places it was missing... next steps, goal creation, objective title.
Create a new activity report, and write a misspelled word in the above fields. They should all get the red squiggly line. [The jira has instructions](https://ocio-jira.acf.hhs.gov/browse/TTAHUB-399) on how to turn spell check on in our supported browsers.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-399
> make sure all inputs have spellcheck

- src/widgets/dashboardOverview.js
- src/widgets/index.js
- src/widgets/overview.js
From @jasalisbury on https://github.com/HHS/Head-Start-TTADP/pull/598
> Oh another thing to be aware of, we are removing a widget route. If a user has their browser open when we deploy they will have a broken frontend that asks for a widget that no longer exists. It seems like we have a built in refresh on the frontend with the inactivity timeout. They will have to re-login (and pull in new frontend code) at least every morning (I'm sort of assuming that). We should probably keep the old route around for a couple of deploys so people will have time to pull in the new frontend code.
Also fixed the naming on "dashboardOverview"/"overview" widget handlers
> Leave redundant backend route in place

- frontend/src/pages/ApprovedActivityReport/index.js
Change unlock report button CSS to outline.
View any approved report the "Unlock report" button should now be outline.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-22
~- [ ] Staging smoke test completed~
> TTAHUB-22: Change unlock report button CSS to outline

- frontend/src/pages/Landing/ReportMenu.js
- frontend/src/pages/Landing/__tests__/ReportMenu.js
Changes to the "over-the-limit" export menu 
- Out of accessibility review, we rethought having a disabled button at all, since the user experience for a disabled control like that can be quite poor. Instead of disabling the button, we remove it. In order to give additional context to the menu's functionality that the button was previously providing, we change the dropdown from "Reports" to "Export reports"
- Removed ellipsis on those menu actions, also as per UI/accessibility review
- Reports from users indicate that 5000 might be too high of a limit. We have lowered it to 4000.
Attempt to export more than 5000 reports. Confirm that the error message appears, and the button does not. Attempt to export less and confirm it works as normal.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-160 …
> [TTAHUB-160] final changes to export message from accessibility spec. and lowering limit

- src/routes/activityReports/handlers.js
There is a warning on top of the CSV export that previously said "Reports done before March 1, 2021 may have blank fields. These were done in a SmartSheet, not the TTA Hub." That date has been updated to March 17
Export a CSV and check the date shows March 17
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-436
> change CSV warning start date

- frontend/src/pages/GranteeSearch/components/GranteeResults.css
- frontend/src/widgets/TotalHrsAndGranteeGraph.js
- frontend/src/widgets/__tests__/TotalHrsAndGranteeGraph.js
Remove aria announcements on Total TTA Hrs Graph.
Also updated CSS select for Grantee Results to ensure Program Specialist column is set to white-space 'unset'.
View the Dashboard page the Total TTA Hours should only read the heading, dates and Display Table text.
View the Grantee search results. The Program Specialist column should wrap correctly.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-415
`- [ ] Boundary diagram updated~
> TTAHUB-415: Remove aria announcements on total tta graph and fix CSS select

- deployment_config/prod_vars.yml
- frontend/src/pages/Landing/ReportMenu.js
We don't have enough free-floating memory to give prod 4GB/instance. This PR reinstates the previous memory and export limit cap to give us time to assess and test how our memory should be allocated while unblocking the deployment pipeline.
> Lower prod memory and reinstate export limit

- docker-compose.yml
Recently ran into varying behavior on different versions of minio images. This PR specifies an agreed upon release tag that we know works as expected.
Rebuild docker, check to see that you can view the minio UI and run commands within the container
> Lock minio to a specific version on docker hub

- src/lib/transform.js
- src/lib/transform.test.js
- src/routes/activityReports/handlers.js
- src/services/activityReports.js
Add Program Specialists to CSV output.
Exporting the CSV of approved reports should add all Program Specialist names.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-325
> TTAHUB-325: Add Program Specialists to CSV output

- frontend/src/pages/ActivityReport/Pages/components/GoalPicker.css
- frontend/src/pages/ActivityReport/Pages/components/ObjectivePicker.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
- When creating a new AR the context text field now appears above the goals section.
- Entering a new goal the check box now aligns vertically with the text.
- Create a new AR the Context text field should now appear above the goals.
- When adding a new goal the check box to the left of the text should be aligned vertically.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-474
> TTAHUB-474: Move context text field above goals /w fix for goal check box vertical alignment

- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/reason.js
Create two scopes on the backend that can be applied to activity reports, one to include activity reports on a given reason, one to exclude the same.
This functionality is not implemented on the front end as of yet - read the code and the tests, make sure that the tests are written in a way as to actually test the scope, and that they pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-485
> [TTAHUB-485] Create scopes for reason on Activity Report

- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/targetPopulations.js
Create two scopes on the backend that can be applied to activity reports, one to include activity reports on a given target population, one to exclude the same.
This functionality is not implemented on the front end as of yet - read the code and the tests, make sure that the tests are written in a way as to actually test the scope, and that they pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-490
> [TTAHUB-490] Create scopes for target population on Activity Report

- frontend/package.json
- frontend/src/components/ActivityReportsTable/ReportRow.css
- frontend/src/components/ActivityReportsTable/ReportRow.js
- frontend/src/components/ActivityReportsTable/__tests__/ReportRow.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/__tests__/Filter.js
- frontend/src/widgets/__tests__/FrequencyGraph.js
- frontend/src/widgets/__tests__/TopicFrequencyGraph.js
- frontend/yarn.lock
Previously, if a keyboard user wanted to export selected reports, it would require **a lot** of tabbing if one of those reports were in the middle of the table.
Hidden tab stops were created directly after the selection checkbox. These are "aria-hidden" since a bunch of buttons with identical text would be confusing to screen-reader-only users, and they have additional navigational options.
Select a report and tab through the document. Observe that you can tab to focus one of the hidden buttons (directly after the report checkbox) and hit enter to initiate a download of selected reports.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-417
- [n/a] [Architectural Decision …
> [TTAHUB-417] Keyboard user improvements on Activity Reports table

- frontend/src/components/ActivityReportsTable/index.js
Props passed into the activity reports table sometimes are new objects. Use deep compare use effect to prevent multiple API calls on props that have not changed.
Open the TTA History page on main with your network tab open. Note multiple API calls to `activity-reports`. Now reload the page with this branch, not only a single API call.
> Activity reports table component uses 'useDeepCompareEffect'

- frontend/src/pages/GranteeRecord/components/GrantsList.js
- frontend/src/pages/GranteeRecord/components/__tests__/GrantsList.js
Add program specialist and grant specialist to Grants list on Grantee Record Profile tab
Visit a grantee record and view the grants table. Note the presence of the program specialist and grant specialist.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-494
> [TTAHUB-494] add specialists to grants table

- src/services/goals.js
- src/services/goals.test.js
Right now, the only goals that selectable are goals with a status of Not Started or In Progress. Goals that have been created via the Hub have a status of null - therefore they should also be included.
Create a goal in an AR. Create a second AR for the same Grantee, and confirm that this goal appears in the dropdown.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-501
> include goals with null status

- .circleci/config.yml
- frontend/src/pages/GranteeSearch/__tests__/index.js
- frontend/src/pages/GranteeSearch/components/GranteeResults.js
- frontend/src/pages/GranteeSearch/components/__tests__/GranteeResults.js
- frontend/src/pages/GranteeSearch/index.js
- src/lib/orderGranteesBy.js
- src/lib/orderGranteesBy.test.js
- src/services/grantee.js
- src/services/grantee.test.js
* Single SQL query hits the DB
* Grouping by `regionId` allows recipients to be split on region
* Sorting by region now has a secondary sort on name. Regional office defaults to sorting by region
* Program/Grant specialists are ordered and put in a comma separated string in SQL
* Updated frontend to just display result from the API
View the grantee search page. This branch is deploying to dev so you should be able to search/sort using "real" program specialists.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-478
> Grantee search fixes

- frontend/src/components/filter/FilterMenu.js
The filters panel shouldn't close on blur. The only ways to close it should be to successfully apply or cancel (or clicking the button again)
Go to the Recipient record page, open the filter menu. Click around not on the menu, observe with satisfaction that the menu does not close.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-499
> [TTAHUB-499] filter menu should not close on blur

- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/programType.js
- src/scopes/activityReport/utils.js
Create two scopes on the backend that can be applied to activity reports, one to include activity reports on a given program type, one to exclude the same.
This functionality is not implemented on the front end as of yet - read the code and the tests, make sure that the tests are written in a way as to actually test the scope, and that they pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-484
> [TTAHUB-484] Add program type scope for activity reports

- frontend/src/components/ActivityReportsTable/__tests__/index.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/TableHeader.js
- frontend/src/pages/RegionalDashboard/__tests__/index.js
- frontend/src/pages/RegionalDashboard/index.js
Add Report List to Regional Dashboard page.
View the Regional Dashboard page. At the bottom of the page we should now show the Report List. The report list should respect the filters set at the top of the dashboard page. All existing Report List functionality should work the same as the Report List on the AR landing. This includes sorting, viewing, paging and downloading reports.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-173
> TTAHUB-173: Add Report List to Regional Dashboard

- frontend/src/components/filter/FilterItem.js
- frontend/src/pages/GranteeRecord/components/GrantsList.js
- frontend/src/pages/GranteeRecord/components/__tests__/GrantsList.js
- src/services/grantee.js
On the **Grantee Record Page**,
Profile Tab:
- When the user hovers over a grant number we display text that says "Links to HSES".
- Sort the grant list so that 'Active' grants always appear before 'Inactive' grants.
TTA History Tab:
- Update the filter items so that if a Topic or Condition has not yet been selected we show the text '- Select -'.
NOTE: This text should NOT be select-able.
On the **Grantee Record Page**,
On the Profile Tab:
- Hover over a grant number in the grant list. You should see text telling the user that they will be redirected to HSES.
- The grant list should always show Active grants first.
On the TTA History Tab: 
- Creating a new filter should show the value '- Select -' in both the Topic and Condition column until a value is selected.
* …
> TTAHUB-514: Updates to Grantee Record Page

- .circleci/config.yml
- package.json
- src/tools/updateLegacyPopulations.js
- src/tools/updateLegacyPopulations.test.js
- src/tools/updateLegacyPopulationsCLI.js
Create script to update legacy report target populations
Specifically
- Infant/Toddlers to Infants and Toddlers (ages birth to 3)
- Preschool to Preschool (ages 3-5)
- Affected by Homelessness to Children Experiencing Homelessness
This will remove duplicated values in analytics widgets like on the recipient record page
- (Locally) Verify that you have legacy data that needs updating. Note some reports that you can check after running the script. 
- Run ```yarn updateLegacyPopulations:local```. 
- Check those reports you noted earlier.
- Run the script again. It should find no reports to update.
- All tests pass.
You can also compare the recipient Absaroka Head Start - Region 8 on sandbox and dev to further verify success
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-496
- [n/a] Meets …
> [TTAHUB-496] Update target populations on legacy reports

- src/lib/transform.js
- src/lib/transform.test.js
- src/routes/activityReports/handlers.js
- src/services/activityReports.js
Add Approvers to CSV Output.
Export the report CSV it should now contain a list of Approving managers separated by carriage returns.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-491
> TTAHUB-491: Add Approvers to CSV Output

- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/stateCode.js
- src/scopes/grants/index.test.js
- src/services/grantee.test.js
- src/testUtils.js
Add state code scope.
Some tests were flaky for me locally. The way all resources were getting created in a `promise.all` caused a race condition, where a grant might get created before the grantee was created (at least that is my theory!)
Verify tests pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-482
> Add state code scope

- .circleci/config.yml
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Goal.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js
- frontend/src/pages/ActivityReport/Pages/nextSteps.js
Objectives will now be saved as the other fields are, without the need to explicitly click the "save objective" button. "edit" mode hasn't been removed, if a user clicks "cancel" they will get the value of the objective before they started editing (when the edit mode first was activated). Auto saves, save draft, save and continue will now save the objective as it is being editing.
Save objectives in sandbox in the following ways 
- letting the auto save hit and refreshing
- navigating away using the navigator
- clicking the save draft button
- clicking save and continue
- adding multiple objectives on the same goal
- adding multiple objectives on different goals
- clicking the cancel button on objectives and verifying the previously saved value is used
- updating an objective and then …
> Tweak saving objectives

- frontend/src/components/SiteNav.css
- frontend/src/components/SiteNav.js
Small/rudimentary CSS fixes to make the site nav a bit more responsive (particularly, when zoomed in, the nav is scrollable instead of buttons overlapping each other).
View the UI. Ensure that the experience for most users is preserved. Zoom in, shrink the screen down. Make sure all the buttons and links are usable all the way down.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-338
> Make site nav responsive/usable when zoomed in

- frontend/src/components/Modal.js
- frontend/src/components/__tests__/ExternalResourceModal.js
- frontend/src/components/__tests__/IdleModal.js
- frontend/src/components/__tests__/Modal.js
- frontend/src/pages/ApprovedActivityReport/__tests__/index.js
- frontend/src/pages/Landing/__tests__/MyAlerts.js
When testing with screen reader (I got this result mainly on Safari & Firefox using voice over) I would load up a fresh page load, no time to idle out, and find that while keyboard focus behaved normally, the screen reader would find itself trapped within the "are you still here" modal
I made a change that uses the exported modalRef to aria-hide the containing div.
Test using a screen reader and ensure everything behaves as it should and reads off content as expected. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-532
> remove modal focus trap

- frontend/src/App.js
- frontend/src/components/SiteNav.js
- Remove the feature flag from the frontend
- This leaves the flag in place in the backend for now. I think we'd have to write a migration to 1) alter the enum_Users_flags so that "grantee_record_page" is not an option and 2) remove it from all users that have it. This feels like a separate task (to me).
View the site as a user (who is not an admin or a possessor of the feature flag). You should be able to view the recipient search and the recipient record page
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-552
> Remove feature flag preventing access to the recipient record page

- frontend/src/components/ActivityReportsTable/__tests__/index.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/TableHeader.js
- frontend/src/pages/Landing/MyAlerts.js
- frontend/src/pages/Landing/ReportMenu.js
- frontend/src/pages/Landing/__tests__/index.js
- frontend/src/pages/Landing/index.js
- src/routes/activityReports/handlers.js
Prevent Multiple Download Clicks on both the Alerts and AR grid (for all/selected).
Go to the AR Landing page and attempt to click the download reports button while a download is in progress on both the Alerts and AR grids.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-548
> TTAHUB-548: Prevent Multiple Download Clicks

- .circleci/config.yml
- src/services/recipient.js
- src/services/recipient.test.js
Exclude grants if its inactive and has an end date greater than today.
View a recipient, only ACTIVE grants and INACTIVE grants between '09/01/2020' and today's date should show.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-555
> TTAHUB-555: Exclude grants if its inactive and has an end date greater than today

- frontend/src/pages/RecipientRecord/__tests__/index.js
There was a rogue UI test with 2021 hardcoded into it. I did it. Happy New Year!
Frontend tests pass in the CI
no ticket
> Remove 2021 from frontend UI test

- src/scopes/activityReport/createDate.js
- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/startDate.js
- src/scopes/activityReport/updatedAt.js
- src/scopes/grants/index.js
- src/scopes/grants/startDate.js
- src/scopes/utils.js
The jira explains the behavior but essentially something like ```?startDate.win=2020/10/01-2020/10/02&startDate.win=2021/10/01-2021/11/01``` would cause an error on the backend historically.  Date queries/scopes have been modified to accept such things
The unit tests pass (and make sense). If you add multiple startDate within filters on the activity reports page, the backend handles it gracefully.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-441
> Handle unexpected multiple values in queries

- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/TableHeader.js
- frontend/src/pages/Landing/MyAlerts.js
- frontend/src/pages/Landing/ReportMenu.js
- frontend/src/pages/Landing/index.js
Put focus back on the download buttons once download completes.
Download Alerts or AR's from the landing. Once the download finishes the button should get focus back so the user can click off.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-548
> TTAHUB-548: Put the Focus Back on the Download Buttons

- src/migrations/20220103142419-remove-grantee-record-flag.js
- src/models/user.js
Remove the grantee record page feature flag from the user model, and bulk update all users to remove that feature flag. (It's already been removed from the frontend)
Run the migration. Ensure you have no users with the feature flag, that the feature flag cannot be assigned, and that everything else works as expected
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-553
- [] Staging smoke test completed
> [TTAHUB-553] remove grantee_record_page feature flag from users/backend

- .circleci/config.yml
- frontend/src/pages/RecipientRecord/__tests__/index.js
Uses circleci's slack orb to post a generic failure message in the acf-head-start-engineers channel should the daily scan job fail. The channel name and slack api key are stored in Circle CI in the contexts panel for HHS.
I've created a slack channel (-mb-test-channel) and I've had the messages posted there. Let me know if you want to review and I'll add you to view the sample failure message that's been posted.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-205
> [TTAHUB-205] notify engineers in slack of daily scan failure

- frontend/src/widgets/Overview.css
- frontend/src/widgets/Overview.js
Because the user can now filter dates from the new filter control on the AR Landing page. We should no longer show the static date value of "09/01/2021 to Present".
View the AR landing, the overview widget should no longer show the static dates. If a date filter is applied it should show in the filter pills.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-313
> [TTAHUB-313] Remove Static Dates from Overview Widget

- .circleci/config.yml
- src/routes/activityReports/handlers.js
- src/routes/activityReports/handlers.test.js
Lots of discussion of BOM and if it is good to add to CSV files. See
https://stackoverflow.com/questions/2223882/whats-the-difference-between-utf-8-and-utf-8-without-bom
https://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob/27975629#27975629
The quick explanation is excel doesn't auto detect that our files are UTF-8 without the BOM set. We set the BOM for UTF-16 which node translates to the UTF-8 BOM (didn't work when I tried to directly set the UTF-8 BOM). See the second link above for a possible explanation. BOM can mess with scripts and combining files together, but I don't think there is going to be direct manipulation of our CSV files so I think we are okay setting the BOM.
Download CSVs in dev with single quotes on windows, open in excel. Report ID 12025 …
> Set UTF-8 BOM

- frontend/package.json
- package.json
follow-redirects was updated addressing an "Information Exposure" vulnerability. The packages that require follow-redirects (frontend: axios, backend: http-proxy-middleware -> http-proxy) have not yet been updated to leverage the fixed version of follow-redirects.
https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-2332181
site is still functional.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-591
> Add follow-redirects update to resolutions for frontend and backend

- src/lib/updateGrantsRecipients.js
- src/lib/updateGrantsRecipients.test.js
- src/migrations/20220114214532-add_grant_annual_funding_month.js
- src/models/grant.js
Adds the annual funding month to the database and populates values from the HSES XML
Make sure tests pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-569
> Add annual funding month to the database

- frontend/src/components/filter/FilterSelect.js
- frontend/src/components/filter/FilterStateSelect.js
- frontend/src/components/filter/__tests__/FilterStateSelect.js
Per discussion at standup, change the state names in the state filter to make the type-ahead more robust.
Make sure you can still select states, make sure as best you can that everything is spelled correctly
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-534
> Add full state names to state filter

- frontend/package.json
- frontend/yarn.lock
- package.json
- yarn.lock
- Remove explicit node-fetch dependency on frontend
- Add new version of node-fetch and nanoid to frontend and backend resolutions
- Update puppeteer on backend
Website still works, tests still pass
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-610
> update node fetch

- frontend/src/widgets/FrequencyGraph.js
- frontend/src/widgets/__tests__/FrequencyGraph.js
The frequency graph toggle has been moved outside of the title and is now a button that matches the button that toggles the accessible table.
Use the graph on the regional dashboard, switching between topics/reasons and the graph/accessible table.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-576
> Frequency graph toggle moved outside of title

- frontend/src/widgets/FrequencyGraph.js
After review with Patrice we decided to update the label of the button that switches the graph type.
Before:
After:
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-576
> Change text of graph toggle

- .circleci/config.yml
Removing slack notifications from the circle ci jobs "test_frontend" and "test_backend" for now
We could enable them on for test_frontend & test_backend on every run, but not just for the daily scan, or at least that's how it looks to me
Maybe we want to do so, but I think we should discuss first in case someone is worried about channel spam
Removing them here because I've nerfed the builds to main and prod where a slack credential is not provided, as things are now
> remove slack notification for now

- frontend/src/pages/RecipientRecord/components/GrantsList.css
- frontend/src/pages/RecipientRecord/components/GrantsList.js
- frontend/src/pages/RecipientRecord/components/__tests__/GrantsList.js
- frontend/src/pages/RecipientRecord/index.js
- src/services/recipient.js
- src/services/recipient.test.js
Adding annual funding month to data is returned from API, surfaced it on the grants table in the frontend. Also made some minor CSS changes to the table to make it flow a little more naturally based on the content provided.
View the table, provided you have annualFundingMonth on your grants, and make sure the column appears.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-600
- [n/a] Staging smoke test completed
- [n/a] Update JIRA ticket status
> [TTAHUB-600] Add annual funding month to recipient TTA record page

- frontend/src/pages/RecipientRecord/components/GrantsList.js
- frontend/src/pages/RecipientRecord/components/__tests__/GrantsList.js
I forgot to push my change writing out "Annual Funding Month" from AFM before I closed my previous branch.
Table on recipient record says "Annual Funding Month," not AFM.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-600
> Expand annual funding month label in table

- package.json
- src/tools/updateLegacyParticipants.js
- src/tools/updateLegacyParticipants.test.js
- src/tools/updateLegacyParticipantsCLI.js
24 Activity Reports list "Family Chlid Care" as a participant type, rather than the correctly spelled "Family Chlid Care". This script fixes this spelling error in the database
Run script locally, checking to see if spelling errors have been corrected and the database integrity has otherwise been preserved.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-582
> add script to update participants

- frontend/src/components/filter/FilterPanel.js
- frontend/src/components/filter/props.js
- frontend/src/pages/RegionalDashboard/__tests__/index.js
- frontend/src/pages/RegionalDashboard/index.js
Design feedback has indicated that the heading on the dashboard should not update as we have the filters in place with the pills to indicate what's applied. There are two scenarios: A user has one region, and sees a heading like "Region 1 TTA Activity Dashboard" or a user can view different regions, in which case they'd see "Regional TTA Activity Dashboard"
View the dashboard with each test case. Ensure that everything is working as intended.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-624
- [N/A] API Documentation updated
- [N/A] Boundary diagram updated
- [N/A] Logical Data Model updated
- [N/A] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions
> [TTAHUB-624] dashboard heading should not change

- src/tools/updateLegacyParticipants.js
- src/tools/updateTopicNames.js
- src/tools/updateTopicNames.test.js
Previous already merged PR's contained errors that came up when preparing to demo them. ```updateLegacyParticipants``` was querying a lot of unnecessary data and ```updateTopicNames``` was missing some data mappings/had one in error.
The following query gives you the number of misspelled participants and a list of all topics that aren't currently selectable.
```sql
-- misspelled participants
SELECT COUNT("id") from "ActivityReports" 
WHERE "participants" && ARRAY['Family Chlid Care']::VARCHAR(255)[];
-- reports w/ wrong or strange topics
select unnest(topics) from
"ActivityReports" where "calculatedStatus" not in ('deleted', 'draft')
AND "calculatedStatus" is not null and id not in (
select id from "ActivityReports" where topics && ARRAY[
'Behavioral / Mental Health / Trauma',
'Child …
```
> fix errors in legacy update scripts

- frontend/src/pages/RegionalDashboard/index.js
It has been bothering me since it was pointed out. A quick fix - the regional dashboard now uses the same CSS as the other page headings (less the recipient record page, which is kind of a unique ball of wax)
View the regional dashboard, then the activity reports page. The headings are now in roughly the same spot relative to the top of the page
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-636
> Fix the vertical spacing on the regional dashboard title

- frontend/src/__tests__/utils.js
- frontend/src/utils.js
Certain filter components expect an array from the query, but it wasn't being decoded as such, and the JS app was crashing
[this link should fire with your local machine active](http://localhost:3000/regional-dashboard?startDate.win=2022%2F01%2F05-2022%2F02%2F04&role.in[]=Early%20Childhood%20Specialist&topic.in[]=CLASS%3A%20Emotional%20Support%2CCLASS%3A%20Instructional%20Support&grantNumber.ctn[]=1&programSpecialist.ctn[]=12&programType.in[]=HS&reason.in[]=Change%20in%20Scope&region.in[]=2&recipient.ctn[]=2&reportId.ctn[]=2&stateCode.ctn[]=AK&targetPopulations.in[]=Affected%20by%20Child%20Welfare%20Involvement). It contains all the possible filters and should load a page (not just a blank white screen)
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-632
> [TTAHUB-632] Fix URL sharing

- .circleci/config.yml
- frontend/src/components/RichEditor.js
See https://github.com/jpuri/react-draft-wysiwyg/issues/967. This change should make pasting formatted text behave better, most note-ably stopping random line breaks in bulleted lists.
before
after
We will lose some formatting from the source, background highlights and font family. May be other things we lose. We should gather a list of all the formatting we want to carry over from word docs to verify what we want to work actually does work.
From main, copy bulleted lists from a google doc into the context field. Note the extra newlines. Checkout this branch and copy the same text into the context field.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-644
> Use draft.js paste handler instead of react-draft-wysiwyg

- frontend/src/components/filter/FilterStatus.js
- frontend/src/pages/RecipientRecord/index.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
- frontend/src/widgets/AccessibleWidgetData.js
- frontend/src/widgets/GoalStatusGraph.js
- frontend/src/widgets/__tests__/FrequencyGraph.js
- frontend/src/widgets/__tests__/GoalStatusGraph.js
- src/scopes/goals/index.test.js
- src/scopes/goals/status.js
- src/widgets/goalStatusGraph.js
- src/widgets/goalStatusGraph.test.js
Added goal status visualization to frontend (bar graph showing status/counts for a given recipients goals). It can be found on the goals & objectives tab of the recipient record page.
View the goal status visualization. Confirm that it shows the counts returned from the backend and that filters apply to it. Confirm that the data can be viewing as a simple HTML table rather than a horizontal bar graph.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-456
> [TTAHUB-456] Add goal status visualization to frontend

- src/scopes/grants/index.test.js
- src/scopes/grants/utils.js
Fixes an error on selecting a filter with "Recipient name". 
- On the landing page, create a new filter using "Recipient name contains"
- Verify that the Overview widget loads correctly (On Dev there is an error)
- Verify that the "Does not contain" clause also works
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-673
> Fix error on recipient name filter selection

- package.json
- src/tools/updateChildInvolvementTargetPopulation.js
- src/tools/updateChildInvolvementTargetPopulation.test.js
- src/tools/updateChildInvolvementTargetPopulationCLI.js
There are 32 ARs that list "Affected by Child Welfare involvement" (with a lowercase i), where as the actual text should have a capital I - "Affected by Child Welfare Involvement".
Run this query on your local db to get a list of affected reports:
`SELECT "targetPopulations" FROM "ActivityReports" WHERE 'Affected by Child Welfare involvement'=ANY("targetPopulations");`
Run the new package.json script updateChildInvolvementTargetPopulationCLI or updateChildInvolvementTargetPopulation:local.
Rerun the above query it should return no results.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-617
~- [ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure …
> [TTAHUB-617] Fix Incorrect Target Population Value

- src/scopes/grants/index.test.js
- src/scopes/grants/programType.js
Fix overview widget failing when adding program type filter.
Create a filter on the AR landing that contains program types. The Overview widget at the top should no longer show an error message.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-683
> [TTAHUB-683] Fix overview widget failing when adding program type filter

- package.json
- src/tools/updateChildInvolvementLegacyTargetPopulation.js
- src/tools/updateChildInvolvementLegacyTargetPopulation.test.js
- src/tools/updateChildInvolvementLegacyTargetPopulationCLI.js
This fixes the "Affected by Child Welfare involvement" issue on the imported json (what we display).
Run the script all legacy reports that had "Affected by Child Welfare involvement" should now have ""Affected by Child Welfare Involvement".
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-617
> [TTAHUB-617] Fix legacy imported target population

- frontend/src/widgets/BarGraph.js
- frontend/src/widgets/TopicFrequencyGraph.js
- frontend/src/widgets/TotalHrsAndRecipientGraph.js
Font colors on our graphs weren't passing accessibility scanning. This change darkens the color on the labels on our graph's x & y axis's.
The graphs still render. They all have the same font color (#1b1b1b).
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-711
> Darken graph font colors

- frontend/src/pages/ActivityReport/Pages/Review/Submitter/NeedsAction.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Submitted.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/index.js
- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/index.js
- src/models/activityReport.js
- src/services/currentUser.js
We encountered an issue when deploying the new creator role field to production. If a report was in NEEDS_ACTION state the user has no way of setting the required creator role. This prevented them from resubmitting the report. We also found out that the same issue existed if the user had one role and a report was in the DRAFT state.
All steps needs to be tested with a user that has a single **AND** multiple roles:
**Draft:**
1. Create a report in DRAFT state. 
2. Manually set the creator role to NULL in the DB for that report. 
3. Revisit the DRAFT report. 
4. Saving the report should automatically populate the creator role OR if you have multiple roles fore the user to select the creator role.
**Needs Action:**
1. Create a report and put it in the NEEDS_ACTION state. 
2. Manually set the …
> [TTAHUB-706] Add Creator Role Selection for NEEDS_ACTION

- package.json
- src/models/tests/auditModelGenerator.test.js
- src/scopes/activityReport/index.test.js
- src/testUtils.js
- src/tools/processData.js
- yarn.lock
There is a new **maintained** version of faker js. We were locked onto the last stable version of the [previous maintainer](https://stackoverflow.com/questions/70597019/what-happened-with-faker-js)'s work.
This change updates us to use the new community maintained version of faker.
- [From the faker team](https://fakerjs.dev/update.html)
CI passes, faker still works in tests
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-730
> switch to new, maintained version of faker

- frontend/run-yarn-audit.sh
- run-yarn-audit.sh
Added a little snippet to the bash script for the frontend to match the backend, so that if the ignored dependencies are functionally identical the script is exited without error, stopping the situation where stuff is moved around in the dependency tree and retriggers yarn audit failures
Already added the same snippet to the backend in #825, didn't realize we were running two identical versions of the same script (an issue for another time, perhaps)
CI passes
> update bash script for frontend

- frontend/package.json
- frontend/yarn.lock
- package.json
- yarn.lock
We added minimist v 1.25 to ignored audit vulnerabilities last week given that there was no newer version at the time. There is now a newer version, so let's bump that up a pip.
CI passes
no ticket
> update minimist via resolutions

- src/scopes/grants/activeWithin.js
- src/scopes/grants/index.test.js
Date scopes are transformed for application to the grant/recipient, to determine whether or that recipient had an active grant during the time range filtered in the overview widget. There was a bug in this transformation that I believe has been addressed.
start or end date filters **before** a given date are transformed into the scope **grant start date is less than or equal** to the same given date
start or end date filters **after** a given date are transformed into the scope **grant end date is greater than or equal** to the same given date
This matches the "within" date range implementation, and I think it covers all cases
The date range filters return accurate info on the overview widget, specifically for "total recipients"
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-736
> [TTAHUB-736] wrong number of recipients depending on date scopes

- src/app.js
- src/routes/apiDirectory.js
- src/services/currentUser.js
Sessions now have a unique id. This session id is used by the audit system to uniquely identify sessions. Before this change the `session.sig` value was always the same for the same user, even after logout/login. The session signature is based on the session, which before this change was always `{userId: $userId$}`. Now the session looks like `{userId: $userId$, uuid: $uuid$}`. With the UUID we generate the value of `session.sig` should change every time you log out and back in. 
See https://github.com/expressjs/cookie-session for an explanation how our cookies work.
Log in and out on main and note the `session.sig` value never changes. Checkout this branch and do the same, `session.sig` should now change.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-622
- ~[ ] Meets accessibility …
> Sessions now have a unique id

- frontend/src/components/Modal.js
- frontend/src/components/RegionPermissionModal.css
- frontend/src/components/RegionPermissionModal.js
- frontend/src/components/__tests__/Modal.js
- frontend/src/components/__tests__/RegionPermissionModal.js
- frontend/src/components/filter/FilterPanel.js
- frontend/src/components/filter/FilterPills.js
- frontend/src/components/filter/__tests__/FilterPanel.js
This is a continuation of **TTAHUB-684** to address some issues found by Patrice with the modal language during the demo.
It also contains a fix for **TTTAHUB-751** users who only have access to one region pasting a region URL filter.
Region permission modal language should show when URL filter contains regions that the user cannot access. 
Users with only one region can paste a URL filter with one or many regions without error.
The two modal options should work as they did before. Note that we now display the regions that the user cannot access.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-684
~- [ ] [Architectural Decision Records](https://adr.github.io/) written for major …
> [TTAHUB-684/751] Fix Issues Found with Region Permission Modal

- frontend/src/components/GoalsTable/GoalsTable.js
- frontend/src/pages/RecipientRecord/index.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
After a user creates new goals we redirect back to the Goals page. We want to sort by created on desc to ensure the new goals show at the top.
Create a new goal. When redirected back to the goals page the table should be sorted by Created On in Desc order. If no goals are created the table should have the same sort as it did before.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-740
> [TTAHUB-740] Show new goals after they are created.

- frontend/src/Constants.js
- frontend/src/components/filter/FilterPanel.js
- frontend/src/components/filter/FilterPills.js
- frontend/src/components/filter/__tests__/FilterPanel.js
- frontend/src/components/filter/activityReportFilters.js
- frontend/src/hooks/useSessionFilters.js
- frontend/src/pages/Landing/__tests__/index.js
- frontend/src/pages/Landing/index.js
- frontend/src/pages/RegionalDashboard/__tests__/index.js
- frontend/src/pages/regionHelpers.js
We always want to maintain the region filters in the URL. This will ensure that when a URL filter is shared the user will be correctly notified if they are attempting to view a region they can't access.
Test on both AR Landing and Regional Dashboard pages. 
Test for both a regular and Central Office user.
1. View the landing/dashboard page in a new browser. The URL should show all user regions.
2. Add a custom region filter. The URL should only show the region specified.
3. Remove the region filter. The URL should add back all regions the user can access.
4. Create a URL that has SOME of the regions the user can access. Paste it in a new browser window. You should see pills for the regions in the URL filter. 
5. Create a URL filter that has ALL of the regions the user can access. Paste it …
> [TTAHUB-760] Always Maintain Region Filters in URL

- .circleci/config.yml
- frontend/src/components/RichEditor.js
There is confusion around resizing the textarea & rich text fields. We should force the height of the text box to expand to accommodate long pasted content, or just a particularly verbose report writer.
Checkout this branch (the feature is also on dev). You should be able to paste large amounts of text into any of the Rich Text components in the activity report and watch it grow.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-767
> [TTAHUB-767] WYSIWYG field auto expands to accommodate long pasted text

- src/lib/fileUtils.js
- src/lib/updateGrantsRecipients.js
- src/lib/updateGrantsRecipients.test.js
- src/models/auditModelGenerator.js
Audit log metadata for the nightly download is now set. Since the nightly job has no access to the `httpContext` the audit* variables are only set if they are null. This allows those variables to be set for the transaction before hitting sequelize hooks and without using an `httpContext`.
I also tried moving all DB calls down to the bottom of `processFiles` so we wouldn't have to wrap the whole method in a transaction. Even though I kept the same order of the calls I was seeing foreign key errors. I wasn't able to track down what exactly was happening.
* The user id is set to 0 to distinguish between the "null" case and system user
* Transaction ID is a UUID
* Session signature is the timestamp of the run followed by the sha256 of the zip file processed
* The audit descriptor lets us know …
> Nightly download sets auditlog metadata

- README.md
- docker-compose.yml
- package.json
Having some port confusion with IT management software and our API doc server
https://adhoc.slack.com/archives/C017Z3PC6MS/p1649772705706809
Docker & API server spin up with no problems
> api docs use port 5003 now

- frontend/src/components/Accordion.js
- frontend/src/components/ControlledDatePicker.js
- frontend/src/components/FormItem.js
- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/index.js
- frontend/src/pages/ActivityReport/Pages/Review/index.js
- frontend/src/pages/ActivityReport/Pages/components/GoalInput.js
- frontend/src/pages/Landing/MyAlerts.js
- frontend/src/pages/Landing/index.js
* Landing page still has an error dealing with a `div` inside a `table`. This is the modal that pops up when deleting a report. Will need a closer look to resolve
* Creating an AR should no longer have prop type or other warnings in the console
* Enter an activity report. You should see no errors
* Open the landing page. You should only see the warning mentioned above
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-464
- ~[ ] API Documentation updated~
- ~[ ] Boundary diagram updated~
- ~[ ] Logical Data Model updated~
- ~[ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
> Clean up warnings on the landing and report pages

- src/routes/activityReports/handlers.js
The call to `setStatus` in the report delete handler returns a promise. This promise is not `await'ed` or chained (`.next()`). This means execution immediately flows out of the handler and exits the `transactionWrapper` function causing the transaction started in the wrapper to `commit`. The promise then starts to execute and uses a transaction that has already been committed, causing the app to error out and crash. Express can't catch the exception because it has already finished executing, which causes node to crash on the unhandled exception. I would _assume_ there is a bit of a race here where some SQL calls can execute before the transaction is closed but the audit log and `setStatus` call hit the DB enough to slow the promise down to the point it will probably always fail.
Now we …
> Await "setStatus" call

- src/tools/processData.js
Process data needs to be wrapped in a transaction. Also does no good to truncate audit log tables and then make audit log creating edits. Audit logs are now truncated after all other data has been updated
> Process data tweaks

- src/widgets/overview.js
Legacy reports do not have activity report recipients. By making that association optional we now include legacy reports in the overview widget "activity reports" count.
Open the landing page with no date filter, note overview widget count does not match activity reports table count. Checkout this branch, the overview widget count should now match the table count.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-784
- ~[ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)~
- ~[ ] API Documentation updated~
- ~[ ] Boundary diagram updated~
- ~[ ] Logical Data Model updated~
- ~[ ] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions~
> Overview widget now includes legacy reports

- frontend/src/hooks/__tests__/useSession.js
- frontend/src/hooks/useSession.js
- frontend/src/hooks/useSessionFiltersAndReflectInUrl.js
- frontend/src/pages/RecipientSearch/__tests__/index.js
- frontend/src/pages/RecipientSearch/index.js
Search query, sort config, and active page are all saved in session storage on the recipient record search page. This persists through back button, on site navigation, and back to search link, for the life of a browser tab.
On the RTR search page, sort the data, change the page, and enter a query. Test that it persists through back button, on site navigation, and clicking the back to search link from a record page.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-702
> [TTAHUB-702] Recipient record search settings saved in session storage

- frontend/src/components/GoalsTable/GoalRow.css
- frontend/src/components/GoalsTable/GoalRow.js
- frontend/src/components/GoalsTable/ObjectiveRow.css
- frontend/src/components/GoalsTable/ObjectiveRow.js
- frontend/src/components/GoalsTable/__tests__/GoalsTable.js
We want to avoid nested tables at all costs as they can be a nightmare to navigate with a screen reader. This change replaces the nested Objectives table in Goals with lists.
View the Goals & Objectives tab of the RTR. Upon inspecting the element structure all Objectives info should be shown in unordered lists (un-styled). All behavior of the Goals table should behave as it did before.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-669
> [TTAHUB-669] On Goals Replace Nested Objectives Table

- frontend/src/components/GoalsTable/ObjectiveRow.scss
- frontend/src/widgets/DashboardOverview.js
Fix two issues found in demo with Patrice.
1. Change icon on RTR.
2. Fix border color on expanded objectives.
1. Check vertical bar icon on RTR.
2.  Expand Objectives border color should match.
~* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0~
> demo fixes

- .circleci/config.yml
CircleCI informed us about a potential issue with deprecation and EOL. 
> We are deprecating Ubuntu 14.04-based machine images on CircleCI in preparation for an EOL on Tuesday, May 31, 2022 to ensure your builds remain secure. For more details on why we are deprecating these images and a complete schedule of the timeline, [please see our blog post](https://go.circleci.com/NDg1LVpNSC02MjYAAAGDLWNmOEuTBr6LADLrY7-advdrG8vwtiISQD9hpyayvqcNFIWQsVA2hPdPnlQGIyq5DRbt19g=).
We did specify "circleci/classic", an image that was being deprecated, in our config. I updated that to the image they recommended in their blog post, Ubuntu 20.04, and deployed it to sandbox.
CI specifies the image we use in the the "build and lint" step. Confirm that is not a deprecated 16.x image. 
The new config is deployed …
> [TTAHUB-785] update circle ci ubuntu image

- frontend/src/pages/RecipientRecord/__tests__/index.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
Remove the default date filter from the goals & objectives tab on the RTR
Visit the RTR -> goals & objectives tab
Observe there is no default date
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-821
> [TTAHUB-821] Remove the default date filter from the goals & objectives page

- frontend/src/components/Navigator/components/SideNav.scss
- frontend/src/hooks/useARLocalStorage.js
- frontend/src/pages/ActivityReport/index.js
- frontend/src/pages/Landing/NewReport.js
- frontend/src/pages/Landing/__tests__/NewReport.js
Clear local storage of any previous "new" report data when "Create New Report" is pressed.
Local storage should also be ignored/cleaned up if the report is not in "Draft" status.
Also fixed an inaccessible/wrong color on the submitted tag/badges/whatever.
Start creating a new report, fill out a few fields. Do not save or navigate within the report. Return to the /activity-reports landing page. View local storage. Confirm that you have data in there. Click on "create new report" and confirm that the data is reset to the default state.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-834
> [TTAHUB-834] clear local storage when create new is pressed

- frontend/src/components/ActivityReportsTable/ReportRow.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/ActivityReportsTable/mocks.js
- frontend/src/pages/ActivityReport/Pages/activitySummary.js
- frontend/src/pages/ActivityReport/index.js
- frontend/src/pages/ApprovedActivityReport/__tests__/index.js
- frontend/src/pages/ApprovedActivityReport/index.js
- frontend/src/pages/Landing/MyAlerts.js
- frontend/src/pages/Landing/__tests__/index.js
- frontend/src/pages/Landing/mocks.js
- src/lib/mailer/index.js
- src/lib/transform.js
- src/migrations/20220520133458-add-collaborator-roles.js
- src/models/CollaboratorRole.js
- src/models/activityReport.js
- src/models/activityReportCollaborator.js
- src/policies/activityReport.js
- src/policies/activityReport.test.js
- src/routes/activityReports/handlers.js
- src/routes/activityReports/handlers.test.js
- src/services/activityReports.js
- src/services/activityReports.test.js
When a collaborator is added to an AR we want to save their roles "at that time" with the report.
- Verify landing page correctly shows Alerts and Approved report Collaborators. 
- Create / Update / Reset / Submit / Approve Report
- Should test a case where a collaborator is added without roles. Then the same report is saved when the user has roles added.
- On the AR landing page the Alerts table should show collaborators saved on reports (and export).
- On the AR landing page the Approved AR table should show what's saved on the report else user roles (and export).
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-795
~- [ ] [Architectural Decision Records](https://adr.github.io/) written …
> [TTAHUB-795] Save AR Collaborator Role

- frontend/src/pages/ApprovedActivityReport/__tests__/index.js
- frontend/src/pages/ApprovedActivityReport/index.js
- src/lib/orderGoalsBy.js
- src/lib/orderGoalsBy.test.js
Added secondary sort to goals list. 
- If sorting by status the secondary sort is create date DESC.
- If sorting by create date secondary sort is status ASC.
Also fixed display issue on approved reports where the Recipient vs Other Entity label was displaying incorrectly.
Sort goals list secondary sort should also be applied.
Create a Recipient and Other Entity approved report both should correctly show their labels.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-858
~- [ ] Logical Data Model updated`
> [TTAHUB-858] Added Secondary Sort to Goal List

- src/scopes/goals/index.test.js
- src/scopes/goals/topics.js
- src/services/goalServices/getGoalsByActivityRecipient.test.js
- src/services/recipient.js
~~We need to make sure that we display and filter goals based on the objective topics.~~
For now we will ONLY show AR topics and filter AR topics.
**Note:** Garrett is updating the migration script to move AR topics to the objectives.
~~Create a goal with objective topics. These objective topics should show on the Goals and Objectives page. Filtering on these topics should reflect the goals we display.~~
User should be able to see and filter the Goals and Objective tab using AR topics only.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-858
> [TTAHUB-858] Show and Filter on Objective Topics on Goals and Objective Page

- frontend/src/pages/ActivityReport/index.js
At some point, the collaborators object returned from the API changed shape, and this left collaborators unable to edit reports. I updated the code that identifies a collaborator, and hopefully have resolved the issue.
Collaborators can edit reports.
> fix collaborators are unable to edit bug

- src/models/hooks/activityReport.js
Goals with 'Not Started' Objectives were being set as 'In Progress'.
Create a Goal with a single objective of 'Not Started' status. Viewing this Goal in the RTR should show a status of 'Not Started'.
Create a Goal with at least one Objective of status 'In Progress' or 'Completed'. The RTR should show the goal as 'In Progress'.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-898
> [TTAHUB-898] Fix Goals Being Marked as In Progress

- frontend/src/pages/ActivityReport/Pages/activitySummary.js
For the AR redesign move the context box above TTA provided.
Create a new AR and make sure the context box now appears above the TTA provided. Given the current state of the AR redesign PR you may not be able to save the report.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-825
> [TTAHUB-825] Move AR Summary Context

- frontend/src/components/Navigator/index.js
If we switch form validation to 'onBlur' the date picker components on the Summary and Next Steps fails validation.
For now we will roll this back to 'onChange'.
Create a new AR when all data is filled out on the Summary and Next Steps pages. The page naviagator should show these pages as 'Complete' and NOT 'In Progress'.
~* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-0~
> switch form validation back to onChange

- frontend/src/pages/Landing/ReportMenu.js
Rollback Max Report Export to 2k
User should only be able to max export 2,000 reports.
> Rollback Max Report Export to 2k

- frontend/src/pages/RecipientRecord/components/RecipientTabs.js
- frontend/src/pages/RecipientRecord/index.js
This change removes the feature flag hiding the Goals & Objectives tab. We'll want to merge this into the migration branch or main when we want the feature to go "live."
View the site as a user without the feature flag. Confirm that you can see everything you are supposed to and that you won't see anything you aren't.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-NO
> Remove feature flag from goals & objectives tab

- frontend/src/pages/ActivityReport/Pages/components/ResourceSelector.js
- frontend/src/pages/ActivityReport/index.js
The fix I added yesterday added a bug on new reports where the default value of the ECLKC resources would be a nested JSON string ```{ value: '\{value\:""\}'}``` or thereabouts. Some additional tweaking was made to ensure that 1) a default blank box is always presented, as now, and that there wasn't any weirdness beyond that.
Ensure that adding resources works as you'd expect.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-918
> [TTAHUB-918] Fix newly introduced bug when adding resources to new report

- frontend/src/components/FileUploader.js
Right now, a file with a size of 0 bytes causes the backend to reject the upload, which causes the react app to crash. This change disallows empty file uploads.
Try to upload a file with a file size of 0 bytes. Note that the site errors instead of crashes.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-921
> [TTAHUB-921] Add front end validation for file size

- .circleci/config.yml
- src/migrations/20220725000000-remove-extra-resources-data.js
The migration removes extra data that was saved to the database as a result of a change.
Run the following query before and after the migration.
There should be 139 records before in the 7/25 prod snapshot and 0 after.
```
SELECT count(*) FROM "ActivityReports" where '{"value":""}' = ANY ("nonECLKCResourcesUsed") 
or '{"value":""}' = ANY ("ECLKCResourcesUsed");
```
The code has been deployed to Dev. The query can be run there.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-926
> Add a migration to remove extra data

- src/services/activityReports.js
Database schema change did a little damage to the way the CSV works. Specifically, a report with multiple recipients was only showing the first one - this change fixes that issue.
Export a CSV with multiple recipients. They should all show up in the CSV.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-928
> [TTAHUB-928] Show all recipients on CSV

- src/lib/transform.js
- src/lib/transform.test.js
- src/migrations/20220725000000-remove-erroneous-records.js
A bas assumption was made during the migration that caused addition erroneous records to be created.  This will remove these records.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-925
> [TTAHUB-925]remove-erroneous-records

- src/migrations/20220804175018-add-created-via-to-goals.js
- src/models/goal.js
- src/services/createOrUpdateGoals.test.js
- src/services/goals.js
To make sequelize a little easier and more semantic (as well as for future thinking), we are adding a "createdVia" col to the goals table.
Run the migration. Check that all your goals have a createdVia col in the DB.
Create goals each way (other than importing) - ensure that the db value is accurate.
> [TTAHUB-942] add created via column to goals

- src/lib/transform.js
- src/lib/transform.test.js
- src/models/activityReportObjective.js
- src/routes/activityReports/handlers.js
- src/services/activityReports.js
For this change we move some legacy columns to the end of the CSV. While also adding some new columns from the 'ActivityReportObjective-' tables (roles, topics, resources, files).
Export the CSV it should match the mockup and fields listed in JIRA 765.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-765
> [TTAHUB-765] New CSV for Redesign

- frontend/src/pages/ActivityReport/Pages/__tests__/activitySummary.js
- frontend/src/pages/ActivityReport/Pages/activitySummary.js
- Define `max` prop on duration input so that keyboard uparrow input prevents values of >99.5.
- Input value >= 100 shows a validation error message that reads: "Duration must be less than 100 hours".
- Add a test for two duration validation errors: 1) negative values and 2) >= 100 values
In the duration field of the activity summary form:
- When incrementing by either scrolling with the mousewheel or using the uparrow keys, max value should be clamped to 99.5:
https://user-images.githubusercontent.com/17074357/183146487-fba03025-abcb-4f16-aa87-7bb617d345a8.mov
- When input is by another means set to a value > 99.5, a helpful validation error message should be visible:
https://user-images.githubusercontent.com/17074357/183146686-f021c332-77e0-44a1-b5fb-9149ca208310.mov
* …
> [TTAHUB-828] Activity summary duration input validation

- src/scopes/goals/topics.js
Change the string comparison used by the goal topics filters/scope
To reproduce bug on main:
1) Go to RTR
2) Goals and Objectives tab
3) Select Goals topics is or is not a topic containing a parentheses. Note that the data is not filtered (it helps if you can see a goal with that topic, so you might query the DB first to find an appropriate recipient)
Works on this branch
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-980
> [TTAHUB-980] Change string comparison operator for goal topics filters/scope

- frontend/src/components/GoalsTable/GoalDataController.js
- frontend/src/components/GoalsTable/GoalsTable.js
- frontend/src/components/GoalsTable/GoalsTableHeader.js
- frontend/src/components/GoalsTable/__tests__/GoalsTable.js
- frontend/src/pages/ActivityReport/Pages/components/RecipientReviewSection.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
- frontend/src/pages/RecipientRecord/pages/PrintGoals.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
- frontend/src/pages/RecipientRecord/pages/__tests__/PrintGoals.js
- frontend/src/widgets/GoalStatusGraph.js
- frontend/src/widgets/__tests__/GoalStatusGraph.js
- src/services/recipient.js
- src/widgets/goalStatusGraph.js
Unify DB querying for these two components (the goals table and the goal status chart) so they don't continuously fall out of sync
View the goals and objectives tab and try a few different filter combinations. The goal statuses and the goals table should show the same number for counts, both total and for individual goal statuses.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-975
> [TTAHUB-975] Fix chart and table discrepancy

- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/__tests__/ObjectiveTopics.js
- frontend/src/components/GoalForm/__tests__/ReadOnlyGoal.js
- frontend/src/components/GoalForm/__tests__/ReadOnlyObjective.js
- frontend/src/components/GoalForm/__tests__/ResourceRepeater.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/ObjectiveTitle.js
- frontend/src/pages/ActivityReport/Pages/components/ObjectiveTta.js
- frontend/src/pages/ActivityReport/Pages/components/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/ObjectiveTitle.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objectives.js
- src/services/goals.js
When using existing goals the objective drop down does not correctly reflect the available objectives.
1. From the RTR create a goal  with multiple objectives.
2. Create a new AR
3. On the goal created page select the Goal you created in the first step
4. Select one of the existing objectives you created
5. When you click the objective drop down again it should reflect the available objectives
6. Changing the selected objective should refresh the drop down with the correct available objectives
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-970
> [TTAHUB-970] Correctly Display Available Objectives

- frontend/src/pages/ActivityReport/Pages/components/ObjectiveTitle.js
When creating or adding an existing goal the form is setting focus on the Objective title.
Creating or adding an existing objective should NOT auto focus on the title.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-970
> [TTAHUB-970] Fix Auto Focus Issue on Objective Title

- frontend/src/App.js
- frontend/src/components/AppWrapper.js
- frontend/src/components/HubIdentifier.js
- frontend/src/components/HubIdentifier.scss
- frontend/src/components/RequestPermissions.js
- frontend/src/pages/Unauthenticated/__tests__/index.js
- frontend/src/pages/Unauthenticated/index.js
- Add the identifier to the bottom of the login page.
- Remove sidebar from login page.
- Remove modal styles
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-948
> TTAHUB-948 Hub identifier / vulnerability disclosure policy link

- frontend/src/components/Navigator/__tests__/index.js
- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/OtherEntity.js
- src/services/goals.js
- src/services/objectives.js
- src/services/objectives.test.js
We need to prevent creating duplicate goals and objectives if an auto save occurs when the user is still editing.
We also need to add saving of draft other-entity objectives while preventing the same case.
Create goals and objectives for both **recipient** and **other-entity** reports. Allow auto save to occur at various steps (CRUD) to ensure we are not creating duplicate goals and objectives in the database. You should be able to finalize goal and objective creation and submit the report as before.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-996
> [TTAHUB-996] Prevent Duplicate Goals when Saving Draft

- frontend/src/pages/ActivityReport/index.js
- src/services/goalServices/goals.test.js
- src/services/goalServices/saveGoalForReport.test.js
- src/services/goals.js
This fixes two bugs when a recipient is added to an existing AR report.
- When it attempts to find a existing goal it excludes null template ids.
- If the goal id doesn't match the objective goal id we need to create a new objective.
Create a recipient report and add a goal and objective(s). The go back to the 'Summary' page and add a new recipient. The goals, objectives, and ARO tables should all properly have a new item added for the new recipient.
It should also work as it did before for removing a recipient.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1002
> [TTAHUB-1002] Update Objectives when Recipients Change

- src/models/hooks/activityReport.js
- src/models/hooks/activityReport.test.js
- src/models/hooks/objective.js
- src/models/hooks/objective.test.js
- src/models/objective.js
- src/services/goalServices/getGoalsByActivityRecipient.test.js
- src/services/goalServices/goals.test.js
- src/services/goals.js
Use sequelize's "afterCreate" and "afterUpdate" hooks to automatically move a goal through the statuses based [on this logical diagram](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1647548115774/d89d9477fdc3555b8b39b382311d8f2d1f2bacfc?sender=u775286a3a84f5c5204174211).
This is necessary for MVP since the only way to change the goal status in the UI is via the RTR.
Verify that the following statements are true:
- Create a goal on the Create Goals form by filling out the form and clicking Save Draft but DO NOT submit. The goal status should be "Draft"
- Make sure all the objectives are "Not Started" and click submit. The status should then be "Not Started"
- Repeat the steps above, but set one objective to "In Progress." The goal status should be "In …
> Update goal status based on objective status

- frontend/src/components/FileUploader/FileRejections.js
- frontend/src/components/FileUploader/ObjectiveFileUploader.js
- frontend/src/components/FileUploader/__tests__/ObjectiveFileUploader.js
- frontend/src/components/GoalForm/Form.js
- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/ObjectiveForm.js
- frontend/src/components/GoalForm/index.js
- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/OtherEntity.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
- src/policies/objective.js
- src/routes/files/handlers.js
- src/routes/files/handlers.test.js
- src/routes/files/index.js
- src/services/goals.js
- src/services/objectives.js
Refactor the refactor; since we needed to heavily rewrite the file uploader to conditionally create an objective, we introduced bugs to make uploading multiple files fail or create multiple extra goals and objectives
File uploads on objectives (RTR and AR) should continue to work with single files and now work for uploading multiple files.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1005
> [TTAHUB-1005] Fix objective file uploader not handling multiple file uploads

- frontend/src/components/ActivityReportsTable/ReportRow.js
- src/services/activityReports.js
- src/services/activityReports.test.js
We need to add back the program type to both the approved report and csv export.
Might be related to this: https://github.com/sequelize/sequelize/issues/5193
View an approved report and export the csv the programs should now appear.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1003
> [TTAHUB-1003] put back programs on approved page and csv export

- frontend/src/Constants.js
- src/migrations/20220902172413-ar-reason-grantee-to-recipient.js
In the activity summary stage of the AR form, the reasons dropdown should not include `New Grantee` any longer and instead includes `New Recipient`.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-924
> TTAHUB-924 reword "New Grantee" reason to "New Recipient"

- src/lib/transform.js
- src/lib/transform.test.js
- src/routes/activityReports/handlers.js
Added grant state code's to the csv export.
Export both regular and legacy reports. We should now show a state code column with the distinct state codes for the grant.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-977
> [TTAHUB-977] Add grant state code with test

- frontend/src/components/FileUploader/ObjectiveFileUploader.js
- frontend/src/components/FileUploader/__tests__/ObjectiveFileUploader.js
- frontend/src/components/GoalForm/Form.js
- frontend/src/components/GoalForm/GoalDate.js
- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/index.js
- frontend/src/components/Navigator/index.js
- frontend/src/fetchers/File.js
- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/OtherEntity.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
- frontend/src/pages/ActivityReport/Pages/supportingAttachments.js
- frontend/src/pages/ActivityReport/index.js
- src/models/hooks/activityReport.js
- src/routes/files/handlers.js
- src/routes/files/index.js
- src/services/goals.js
- src/widgets/goalStatusGraph.js
PR fixes the following bugs
- on the create goals form, when editing an existing goal & objective, file uploads would fail
- on the AR, when loading an existing objective, deleting a file from the AR was deleting the objective file and file, where it should only have deleted the ActivityReportObjectiveFile if it exists
- All goals on activity reports should be moved to "in progress" when the report is approved but they were getting stuck in "not started" depending on objective status 
- On the AR, selecting an existing goal would fail to load the date into the "Anticipated date" field
- A recent change caused a bug where AR data would be missing between pages
Confirm that the above bugs are resolved (and, ideally, no additional bugs are introduced)
* …
> [TTAHUB-1015] misc new redesign bugs

- src/lib/transform.js
- src/lib/transform.test.js
We want to show all state codes (even duplicates) in the same order as the grants.
Export the CSV ensure that all state codes show in the same order as the grants.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-977
> [TTAHUB-977] Show all state codes in order of grants

- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.scss
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/ObjectiveTitle.js
- frontend/src/pages/ActivityReport/Pages/components/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/ObjectiveTitle.js
- The spacing around "Add next step" buttons should match the figma prototype:
- The `TTA objective` textarea should be readonly when:
- The objective's parent goal status is 'Closed'.
- The objective's initial status when loaded is 'Completed' or 'Suspended'.
- When the objective is on an approved report.
Possible readonly/writable combinations are tested:
https://github.com/HHS/Head-Start-TTADP/blob/5cc9c442012d36ec868d3179ac6d3a4d6ed9981b/frontend/src/pages/ActivityReport/Pages/components/__tests__/ObjectiveTitle.js#L55-L73
- The CTA buttons on the review and submit stage should be swapped:
.. is now ..
> TTAHUB-992 readonly bug / CTA button order / "add next step"

- frontend/src/components/GoalForm/index.js
Select a recipient from create goals form and edit the top goal
Fill in 9/1/22 for the date
Select top 2 specialist roles
Select top topic
Click "Save and Continue" then "Save Draft"
Note there is an error saving (there is also a draft goal visible on the list)
The server shows - error:   undefined - UNEXPECTED ERROR - Error: WHERE parameter "grantId" has invalid "undefined" value
This change fixes this bug
Test as above
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1019
> [TTAHUB-1019] Fix bug on create goals

- frontend/src/pages/ActivityReport/Pages/components/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objectives.js
If the user removes a goals objective it should return to the list of available objectives.
Create an AR using a goal with some objectives. Add some of the existing objectives. Removing the existing objectives should return them to the drop down list of available objectives.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1011
> [TTAHUB-1011] Fix Available Objectives

- .circleci/config.yml
- bin/run-owasp-scan
Update which owasp docker image bin/run-owasp-scan and circleci/config.yml use to get around incompatibilities between circle CI and the linux distro owasp now uses
CI passes
* ~https://ocio-jira.acf.hhs.gov/browse/TTAHUB~ NO PR
> Fix owasp/docker-stable to an image that works 

- frontend/src/pages/ApprovedActivityReport/index.js
- src/models/hooks/activityReport.js
- src/services/goals.js
- src/services/reportCache.js
On an activity report, the status of the objective display should be derived from the activity report objective. The objective status is changed only on the RTR and at the time of Activity Report approval.
- Create a report (set the end date to sometime in the past) with a new goal & objective, approve it. 
- Create a second report, with a newer end date, using the same goal and objective. The objective should have a different status. Before you submit it, view the database and make sure the values are correct for both the objective and the activity report objective. Leave and come back to the report, refresh and clear local storage. The values shown in the UI and the database should be correct.
- Submit and approve the second report, re-verify in the database. The objective status should …
> [TTAHUB-1040] Update ARO status only via Activity Report

- bin/run-tests
- bin/test-backend-ci
- package.json
- src/models/hooks/activityReport.js
- src/models/tests/objectiveStatus.test.js
- src/services/goalServices/getGoalsByActivityRecipient.test.js
- src/services/goalServices/goals.test.js
- src/services/goalServices/saveGoalForReport.test.js
This PR fixes two bugs with the recent changes to the CI
1) "run-tests.sh" was not executing it's backend test run inside a docker container
2) The CI was not providing the proper exit code if a set of the batched tests had a failure, so as a result some failed tests got merged into this branch from other PRs.
- The CI passes. You can view the CI history of this branch on Circle CI to view the initial behavior ("success" on test-backend despite 20-odd failed tests) and the fix (any test failure is a failure of the test-backend job)
- docker:test backend correctly connects to postgres and runs tests
> "run-tests" runs correctly in docker, new CI script providing correct exit code

- frontend/src/Constants.js
- frontend/src/__tests__/localStorageCleanup.js
- frontend/src/components/ActivityReportsTable/ReportRow.js
- frontend/src/components/ActivityReportsTable/mocks.js
- frontend/src/components/GoalCards/ObjectiveCard.js
- frontend/src/components/GoalCards/__tests__/GoalCards.js
- frontend/src/fetchers/__tests__/activityReports.js
- frontend/src/fetchers/activityReports.js
- frontend/src/pages/Landing/__tests__/index.js
- frontend/src/pages/Landing/mocks.js
- frontend/src/pages/RecipientRecord/__tests__/index.js
- frontend/src/testHelpers.js
- src/models/activityReport.js
- src/services/recipient.js
- src/services/recipient.test.js
Fixes the following bugs:
- Objectives on the RTR page seem to only show one AR under "Activity Reports" even though they have been included on multiple ARs.
- Topics for newly created objectives do not display in the approved reports table, only the "legacy" topics field
Reuse an existing goal and objective (that already has a report) on a new activity report, then approve it. You will see topics in the approved report table for the objective you created. Look up that goal & objective in the RTR. You will see both reports.
> [TTAHUB-1029] Show all AR's on goals & objectives page, show all topics on approved reports table

- src/models/hooks/activityReport.js
- src/models/tests/objectiveStatus.test.js
- src/services/goalServices/goals.test.js
- src/services/goals.js
Fix bug that creates dummy objective.
**Steps to Reproduce:** 
1. Create a Goal from RTR with one Objective
2. Create a AR with the same recipient used above and any other recipient (2 total)
3. Add the Goal and Objective created above
4. Set the objective to 'Complete' and Save
5. Edit the Goal
6. Set the Objective to 'In Progress' and Save
This seems to be when going from 'Complete' > 'In Progress'.
After the fix there should no longer be an extra objective.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1046
> [TTAHUB-1046] Fix bug that creates dummy objective

- src/lib/transform.js
- src/lib/transform.test.js
Add goal created from column to CSV.
Export CSV each goal should have a created from column that reflects were the goal was created 'activityReport', 'rtr', 'imported'.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-944
> [TTAHUB-944] Add created from goal column to csv

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/GoalCards.js
The 'Last TTA' field on goals table was showing as blank if it only had one AR.
Create a goal and objective and use them on a single AR. View the goals table you should now see the last tta field populated.
Note: Draft goals wont have a last tta date.
> [TTAHUB-1029] Fix blank 'Last TTA' field

- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- src/services/goals.js
Sometimes the retrieval of Objectives can be a little slow to smooth things out for the user lets display a loader.
This change also includes a potential speed increase by applying separate to some of the joins.
Create a report, when selecting an existing goal or switching between goals. We should display a "Loading' message until the objectives come back.
Saving loader should work as it did before.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1057
> [TTAHUB-1057] Loading for Objective Retrieve

- frontend/src/components/HeaderUserMenu.js
- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/Pages/__tests__/nextSteps.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js
- frontend/src/pages/ActivityReport/Pages/components/objectiveValidator.js
- frontend/src/pages/ActivityReport/Pages/nextSteps.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.scss
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
- frontend/src/pages/RecipientRecord/pages/__tests__/PrintGoals.js
- frontend/src/pages/RecipientRecord/pages/components/PrintableGoal.js
- frontend/src/pages/RecipientRecord/pages/components/PrintableObjective.js
- frontend/src/pages/RecipientRecord/pages/components/__tests__/PrintableGoal.js
- frontend/src/pages/RecipientRecord/pages/components/__tests__/PrintableObjective.js
- frontend/src/pages/RecipientRecord/pages/components/constants.js
- src/services/goalServices/goals.test.js
- src/services/goals.js
- src/services/objectives.js
- src/services/recipient.js
Solve issues with incomplete goals not saving properly when the autosave is triggered. 
Also cleanup error message on success, so that the "you had a database error" does not persist.
Change 'you' to 'recipient' on next steps for recipient date label 
Make changes to print preview for approved AR's
- 'Activity Summary' should be sentence case
- Remove user first initial from print preview
- Bold the Objective name
- Fix "if Next Steps has two steps the second step is missing the Date (check for both specialist and recipient)"
- Prevent splitting at header onto next page 
Make changes to Print Preview for Goals
- Remove user first initial from print
- Prevent splitting at header (as above)
- The fields 'Activity Report' and 'Grant Numbers' are blank. Removed grant numbers from objectives. …
> [TTAHUB-1029] Fix auto save error conditions

- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/ObjectiveTopics.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/SpecialistRole.js
- frontend/src/components/HeaderUserMenu.js
- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/ObjectiveSelect.js
- frontend/src/pages/ActivityReport/Pages/components/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/OtherEntity.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/OtherEntity.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.scss
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
- frontend/src/pages/RecipientRecord/pages/__tests__/PrintGoals.js
- frontend/src/pages/RecipientRecord/pages/components/PrintableGoal.js
- frontend/src/pages/RecipientRecord/pages/components/PrintableObjective.js
- frontend/src/pages/RecipientRecord/pages/components/__tests__/PrintableGoal.js
- frontend/src/pages/RecipientRecord/pages/components/__tests__/PrintableObjective.js
- frontend/src/pages/RecipientRecord/pages/components/constants.js
- src/services/goalServices/getGoalsByActivityRecipient.test.js
- src/services/recipient.js
- Removed the objective ID from the dropdown, as it "...was never in the design and most likely will have no value to the user"
- Include objectives that aren't on approved reports (fixes the bug described as: When creating goal (G-37481) for the first time, it had 3 topics and 1 objective, but after submitting goal, and going back to the goal table, objective and topics did not display)
- Objectives on the AR load more roles than the collaborator/creator roles; it also loads the roles selected on the RTR. (fixes: "In AR form, Specialist roles is defaulting to Central Office - when a different role was added via Create Goal form in RTR") 
Review the three bugs above and confirm that they are fixed.
> [TTAHUB-1029] Fix bugs reported on ar redesign/create goals

- frontend/src/components/AutomaticResizingTextarea.js
- frontend/src/components/GoalForm/GoalText.js
- frontend/src/components/GoalForm/ObjectiveTitle.js
- frontend/src/pages/ActivityReport/Pages/components/ObjectiveTitle.js
Some of our text area auto-expanded when large amounts of text is pasted in, some did not. This change adds that functionality to the goal name fields and the objective title fields.
Paste a large chunk of text into the objective title and goal name fields. The field will grow. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-854
> [TTAHUB-854] add auto expand functionality to text areas

- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objectives.js
Added a little bit of code to handle the cost of switching branch to branch. Before this, there was a bug with the goals and objectives form where a pre-migration report would have a missing value in the objective selector. Although the title and TTA provided would be preserved, if a user tried to select something in that selector it would potentially lead to data loss.
- Checkout main, make sure DB reflects the schema in main
- Create a draft report, add a goal, objective, and some TTA provided
- Switch to this branch, run the database migrations. Return to the the report and the goals & objectives section. You may have to click edit to reopen the form. The objective selection form field should have a value which matches your objective. All other fields will behave as expected, although …
> [TTAHUB-1029] migration proofing for the goals and objectives form

- src/models/hooks/activityReportApprover.js
This change makes sure we have atleast one approver before setting it to 'approved' status.
Right now this is exposed through a "Race" condition. But it might also prevent any unforeseen slowness issues.
To reproduce the issue do the following:
1. Create new report with a handful of recipients and atleast one goal with two objectives (to buy you some time).
2. Set yourself as the approver and click Submit.
3. As soon as you return to the AR landing **immediately** click the report link in the alert.
4. Notice that you do not receive the standard approve report screen.
5. Click the 'Review and Submit' page notice it says 'Approved' in the top right corner.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1066
> [TTAHUB-1066] Prevent Approving Report with No Approvers

- frontend/src/components/GoalCards/GoalCard.scss
- frontend/src/components/GoalCards/components/Topics.js
Issues found on Goal RTR card.
- We should always maintain row spacing 16px regardless of view port size.
- Topics at the largest break point should show tool tip. Every smaller break point should show CSV.
- Topics should show at one line with ellipsis at largest break point.
Above issues are fixed.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1071
> [TTAHUB-1071] Fix Topics Tooltip and Row Spacing

- .circleci/config.yml
- src/lib/cron.js
The Recipient updates were still happening in non-prod environments. This PR disables it.
- look at the code
- changes were deployed to Sandbox yesterday. Verify that the Recipients and Grants are not real.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1077
> Disable Recipient updates in non-prod environments

- frontend/src/components/GoalCards/GoalDataController.js
- frontend/src/components/GoalCards/GoalsCardsHeader.js
- frontend/src/components/GoalCards/__tests__/GoalCards.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
Sort options are now:
-creation date (newest to oldest) 
-creation date (oldest to newest)
-goal status (drafts first)
-goal status (completed first) 
Ensure that the options appear as above; ensure that they sort as appropriate.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1074
> [TTAHUB-1074] Add sort options to the goal cards/RTR

- src/services/goals.js
Ever since the sort for the goal retrieve has been implemented I have been getting the  following error: 
**SequelizeDatabaseError: column Goal.created does not exist**
Goal retrieve and order should work as it did before.
Core Issue: 
For some reason I'm the only one on the team getting this error but the below query is what's causing the error for me.
SELECT 
ARRAY_AGG(DISTINCT("grant"."id")) AS "_0",
ARRAY_AGG(DISTINCT("Goal"."id")) AS "_1",
ARRAY_AGG(DISTINCT("grant"."oldGrantId")) AS "_2",
MAX(DISTINCT("Goal"."createdAt")) AS "_3",
"Goal"."name",
"Goal"."status",
"Goal"."onApprovedAR",
"Goal"."endDate"
FROM "Goals" AS "Goal"
LEFT OUTER JOIN "Grants" AS "grant" ON "Goal"."grantId" = "grant"."id"
WHERE ("Goal"."status" = 'Not Started'
OR "Goal"."status" = 'In Progress'
OR …
> Fix goals created sort

- src/migrations/20221017000000-missing-objectives.js
This does does the following steps:
1. Make arg records for all goal used on objectives for reports where missing.
2. Identify all reports with disparity between the list of grants linked through recipients and the list of grants linked through either goals and/or objectives->goals.
3. Using the list create goals for each of the grants linked view recipient but not linked through goals or objectives.
4. Create the arg records linking the newly created goals to their corresponding reports matching on grant id and matching hash of the existing linked goals.
5. Using the list to create objectives for each of the grants  linked view recipient but not linked through objectives leveraging the correctly matching hash goal.
6. Create the aro records linking the newly created objectives to their …
> [TTAHUB-1065] Create a script to add missing aro's and objectives also set onApprovedAR

- frontend/src/components/ActivityReportsTable/__tests__/ReportRow.js
- frontend/src/components/GoalForm/GoalDate.js
- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/ObjectiveForm.js
- frontend/src/components/GoalForm/__tests__/ReadOnlyGoal.js
- frontend/src/components/GoalForm/__tests__/UnusedData.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/components/GoalForm/index.js
- frontend/src/components/__tests__/AutomaticResizingTextarea.js
- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/goalValidator.js
- src/services/goals.js
Make a goal's end date an optional field. Also added some tests for front end test coverage.
In addition, fixed a bug that made it unreasonably hard to get read only resources
Add an end date to the create goals form, or not. Try it both ways, then do the same on the Activity Report.
Confirm that resources on the RTR are now read only if a goal is closed OR and objective is completed
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1072
> Goal end date is no longer a required field

- frontend/src/components/GoalForm/Form.js
- frontend/src/components/GoalForm/__tests__/Form.js
Feedback from designers: we had two alerts on the manage goals form, one of which was no longer supposed to be in use. This PR removes the "Field entries that are used on an activity report can no longer be edited" so that any report on an activity report gets this message: "This goal is used on an activity report, so some fields can&apos;t be edited," and there is no other state. 
Verify the above
> [TTAHUB-1029] Remove extra alert from goals form

- frontend/src/components/ActivityReportsTable/ReportRow.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalForm/GoalDate.js
- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/ObjectiveTopics.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/index.js
- frontend/src/components/Tooltip.js
- frontend/src/components/Tooltip.scss
- frontend/src/components/TooltipWithCollection.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- src/services/activityReports.js
- src/services/goals.js
- Editing an existing goal on the RTR now shows different buttons (save and cancel). Save simply saves and returns the user to the RTR, cancel does the same without saving first. 
- The tooltips on the Activity Reports table now open down if they are in the first five rows, the bottom five rows open in the top direction. This prevents tall tooltips being cut off at the top/bottom
- Ensure the above works as expected
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1076
> [TTAHUB-1076] Show correct buttons on form when editing existing goals

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/ObjectiveCard.js
- frontend/src/components/GoalForm/Form.js
- frontend/src/components/GoalForm/GoalDate.js
- frontend/src/components/GoalForm/GoalText.js
- frontend/src/components/GoalForm/GrantSelect.js
- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/ObjectiveForm.js
- frontend/src/components/GoalForm/ObjectiveStatus.js
- frontend/src/components/GoalForm/ObjectiveTitle.js
- frontend/src/components/GoalForm/ObjectiveTopics.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/GrantSelect.js
- frontend/src/components/GoalForm/__tests__/ObjectiveFiles.js
- frontend/src/components/GoalForm/__tests__/ObjectiveForm.js
- frontend/src/components/GoalForm/__tests__/ObjectiveStatus.js
- frontend/src/components/GoalForm/__tests__/ObjectiveTopics.js
- frontend/src/components/GoalForm/__tests__/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/components/GoalForm/index.js
- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
The create goals form is tied to a region. Users with read only permissions will see the create goals form in read only. Users without any regional permissions will see an error message
Verify the above is true, verify that the existing permissions/behavior is uninterrupted. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1076
> [TTAHUB-1076] Use permissions on front end of create goals

- frontend/src/components/GoalForm/ReadOnlyGoal.js
- frontend/src/components/GoalForm/__tests__/ReadOnlyGoal.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/components/GoalForm/index.js
- frontend/src/fetchers/goals.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
- src/routes/goals/handlers.js
- src/routes/goals/handlers.test.js
- src/routes/goals/index.js
- src/services/goalServices/destroyGoal.test.js
- src/services/goals.js
In the distant past, when the manage goals page was constructed, I was asked to disable deleting of goals from the manage goals page so that things couldn't get too wild while we were testing.
It was just a few nights ago that I awoke with the realization that I had never rewired things. I mopped the sweat from my brow, dusted off this code and discovered it was largely still functional, except for needing a few small tweaks. I removed references to the GrantGoals table. I refactored it to remove two goals at once where appropriate. I believe it now functions as intended. 
The only way to access it is by creating a goal from the RTR and then immediately deleting it. There is no "read only" screen for editing goals any longer. This change also effects (mildly) the delete goals function …
> [TTAHUB-1074] fix delete button functionality from edit goals page

- frontend/src/components/GoalForm/index.js
- frontend/src/components/Navigator/__tests__/index.js
- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/index.js
- src/services/goals.js
This PR fixes the bugs below.
**Data lingers in the local storage. Some data stays in the local storage and gives the users an incorrect view of what is in the database (Krys)**
Steps to see one case:
create a new AR (I tried with 2 recipients)
select an existing goal and click "Save Draft"
navigate away from the page through the navigator
come back and remove the goal
select a different existing goal and use "Save Draft"
reload the page
observe that the old removed goal shows instead of the new one.
**Newly refreshed goal disappears when a page is refreshed. (Krys - this might be related to the above)**
Steps:
create an AR (I used 2 different recipients)
select an existing goal and click "Save Draft"
refresh the page to see the goal disappear
**Navigating away from the "Goals and …
> [TTAHUB-1085] Update form state when saving draft on goals and objectives page

- src/services/goals.js
The results from "getGoalsForReport" now sorted by the creation date of the ActivityReportGoal. The deduplication function that is called after the SQL query will handle any weirdness around adding and removing recipients, so that the end result is that the matching sets of goals will be ordered by the earliest ActivityReportGoal.
Validate in the UI that adding, editing and removing goals to an activity report preserves this order.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1082
> [TTAHUB-1082] Sort goals on the Activity Report by the linking ARGoal table

- frontend/src/App.js
- frontend/src/components/HeaderUserMenu.js
- frontend/src/components/SiteNav.js
- frontend/src/components/__tests__/Logout.js
- frontend/src/pages/Logout/index.js
Adds a route handler for `/logout` that mounts a very simple component that basically just calls `logout()`. To prevent split-second sidebar flickering, `SiteNav` is updated to not render when the route is `/logout`.
> TTAHUB-1026 Add `logout` route

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/GoalCards.js
- frontend/src/components/GoalCards/GoalDataController.js
- frontend/src/components/GoalCards/GoalsCardsHeader.js
- frontend/src/components/GoalCards/__tests__/GoalCards.js
- frontend/src/components/SelectPagination.js
- frontend/src/components/__tests__/SelectPagination.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
- Persist 'select all' check box until they unselect it. 
- Always show select all pages alert if 'select all' is checked and all pages aren't selected.
- Paging now has 'per page' selector in 10, 25, 50, and all.
- Changing the rows per page brings you back to the first page.
Make sure the design is matched and the above are working as expected.
https://www.figma.com/proto/WoAULVDXnKuVx5t1y9jgzW/RTTAPA-Goals-Plan?node-id=367%3A38184&scaling=min-zoom&page-id=210%3A18964&starting-point-node-id=367%3A36637&show-proto-sidebar=1
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-857
> [TTAHUB-857] Add new paging to goals and update select

- frontend/src/Constants.js
- frontend/src/pages/ActivityReport/constants.js
- src/constants.js
- src/widgets/topicFrequencyGraph.test.js
#1002 introduced a migration to add new topics to the DB here:
https://github.com/HHS/Head-Start-TTADP/pull/1002/files#diff-5d9b57790fc18cce8428540c42363b5a91eade2b120bbd1bb38ffadead010cd9R37-R39
#1007 was meant to be the FE changes for these new topics. some of them were missed. this PR introduces these missing topics.
> TTAHUB-853 add missing topics to fe constants

- frontend/src/components/Navigator/index.js
When creating an 'Other-Entity' report we were not correctly setting the 'otherEntityId' this problem existed for both the 'Save objective' and 'Save draft' buttons.
Create an 'Other-Entity' report add an objective (of multi) click Save draft. The Objective 'otherEntityId' column should be populated. Repeat the same steps but this time click 'Save objective' the entity id should be populated.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1101
> [TTAHUB-1101] Fix Other-Entity ID Not Saving

- frontend/src/pages/ActivityReport/Pages/__tests__/goalsObjectives.js
- frontend/src/pages/ActivityReport/Pages/components/OtherEntityReviewSection.js
- frontend/src/pages/ActivityReport/Pages/components/RecipientReviewSection.js
- frontend/src/pages/ApprovedActivityReport/__tests__/ApprovedReportV2.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
- frontend/src/pages/ApprovedActivityReport/index.js
This fixes Topics, Files, and Resources on the review screen for both 'Recipient' and 'Other-Entity' reports.
It also fixes resources for 'Other-Entity' on the approved report screen.
NOTE: When testing this its important to note that there is a bug saving OE file attachments that should be fixed by this PR 
https://github.com/HHS/Head-Start-TTADP/pull/1129.
Make sure all items correctly show on the review and approved screens for both 'Recipient' and 'Other-Entity' reports.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1107
> [TTAHUB-1107] Add Missing Fields to AR Review (Recipient and OE)

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/GoalCards.js
There was a bug that if a goal didn't have a previous status and the new status was set to 'Suspended'. We weren't setting the new previous status and it locked the goal status to only be 'Closed'.
Find a goal that has a NULL previousStatus in the DB. Set the status of the goal to 'Suspended'. You should be able to set the goal to one of two options 1. the previous status or 2. closed.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1104
> [TTAHUB-1104] Fix issue when setting new status if previous status was null

- frontend/src/components/GoalCards/GoalsCardsHeader.js
- src/services/recipient.js
Sort description for descending goal status should read "Goal status - closed first" instead of "Goals status - completed first".
Goal sort ascending (drafts first) should be:
1. Draft
2. Not started
3. In progress
4. Suspended
5. Closed
Goal sort descending (closed first) should be:
1. Closed
2. Suspended
3. In progress
4. Not started
5. Draft
Go to RTR -> G&O and sort by goal status desc and asc. Confirm the order aligns with the above spec.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1106
> TTAHUB-1106 Goal status sorting fixes

- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.scss
Per Lauren and Patrice we want to remove the bold status on Objective name in Approved and Approved Print screens.
View an approved report the Objective name should NOT be bold.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1103
> [TTAHUB-1103] Remove bold objective name

- src/models/goal.js
- src/models/goalTemplate.js
- src/models/hooks/activityReport.js
- src/models/hooks/goal.js
- src/models/hooks/goalTemplate.js
- src/models/hooks/objective.js
- src/models/hooks/objective.test.js
- src/models/hooks/objectiveTemplate.js
- src/models/objective.js
- src/models/objectiveTemplate.js
- src/models/tests/goals.test.js
Sequelize beforeValidate and other before hooks to not detect added attributes automatically, 
Goals - On the RTR page, change the status of the goal repeatedly and monitor the time stamps for each status.
Objectives - Edit a goal with objectives, change objective status repeatedly and monitor the time stamps for each status.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-983
> [TTAHUB-983] Before Validate Hooks Not Working on Update

- frontend/src/components/FileUploader/ObjectiveFileUploader.js
- frontend/src/components/FileUploader/__tests__/ObjectiveFileUploader.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- src/policies/objective.js
- src/routes/files/handlers.js
- src/services/files.js
When investigating a bug for Other Entity attachments. I also found another bug that would crash the server if we attempted to add attachments on a recipient AR if the Goal wasn't saved.
**NOTE:** Right now if you attempt to save attachments on a AR were the goal IS NOT saved. It wont save the files unless you are an admin. I'm assuming this is by design. I have another change if we want to check region before we throw a 400.
- Create a Multi Recipient AR and add/remove file attachments on multiple objectives **without** saving the goal 
- Create an Other Entity AR and add/remove file attachments on multiple objectives
Verify database data is correct. Approve both reports (saving goals) and assert data again.
- Create a goal from RTR with multiple objectives add/remove file attachments. …
> [TTAHUB-1105] Fix bug with Recipient and OE attachments

- src/policies/recipient.js
- src/routes/recipient/handlers.js
- src/routes/recipient/handlers.test.js
- src/seeders/20201124160449-users.js
added policy for recipients based on region
1. view recipient profile page
2. edit users permissions to not have access to region of recipient
3. go back to recipients profile page
4. should get a 401 response 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1128
> [Ttahub-1128] Can view RTR page with URL when don't have permission

- frontend/src/components/GoalForm/ObjectiveTopics.js
On other entity reports if an objective has topics and is marked 'suspended' the topics are being hidden. They should be shown as read only.
- Create a Recipient report with Goal and Objective. If the Objective status is suspended and we have topics they should be shown as read only.
- Create a Other Entity report with Goal and Objective. If the Objective status is suspended and we have topics they should be shown as read only.
Should be able to save and edit objectives on both report types.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1146
> [TTAHUB-1146] Topics missing on OE when obj is suspended

- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
We need to show a loading screen when we are retrieving objectives for a goal.
Create an Recipient AR select different goals. When we are retrieving the goals we should show a loader to prevent them from selecting an objecitve not associated with the goal.
> fix for loading on objectives

- src/services/recipient.js
goal status might potentially be null, so sorting logic should account for this
set goal status to null in the DB
> Check for null goal status when sorting

- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
This PR just ensures the correct goal is removed from the array provided to the `ReadOnly` component using `filter` instead of `splice` and relying on the provided index.
1. create an AR with multiple recipients (10)
2. on the Goals and Objectives page create a goal using an exising goal.
3. create an objective and fill in all the fields
4. wait for the auto save
5. right after auto save click save goal
6. select edit
7. note the edit form is shown **and the read only version of the same goal is NOT shown**.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1158
> [TTAHUB-1158] readonly duplicate goals

- frontend/src/pages/ActivityReport/Pages/__tests__/nextSteps.js
- frontend/src/pages/ActivityReport/Pages/nextSteps.js
`isPageComplete` referenced an incorrect variable name: `participantNextSteps`, when it should have been `recipientNextSteps`.
1. Create an AR
2. On the next steps page, don't fill out the date
3. Click "Save and continue"
4. Notice next steps on Navigator are still "In progress".
5. Return to next steps, fill out dates and click "Save and continue"
6. Next steps in Navigator should now be "Completed"
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1164
> [TTAHUB-1164] nextSteps isPageComplete bug

- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalPicker.js
This issue came up in the demo when an auto load triggered the app loader. The core issue here is that the auto save is triggering a useEffect that calls the objective retrieve (which does show the app loader).
- Set you auto save interval to 10 seconds
- Create a new recipient report 
- Select an existing goal 
- You should see the initial app loader when the objectives are retrieved
- The next auto save should NOT trigger the auto loader
- Subsequent changes to the goal SHOULD trigger the loader
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1191
> [TTAHUB-1191] Auto save triggers fetch of goal objectives

- frontend/src/components/GoalForm/ObjectiveFiles.js
- frontend/src/components/GoalForm/ObjectiveTopics.js
- frontend/src/components/GoalForm/ReadOnlyGoal.js
- frontend/src/components/GoalForm/ReadOnlyObjective.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/ObjectiveFiles.js
- frontend/src/components/GoalForm/__tests__/ObjectiveForm.js
- frontend/src/components/GoalForm/__tests__/ObjectiveTopics.js
- frontend/src/components/GoalForm/__tests__/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
- frontend/src/pages/ActivityReport/Pages/supportingAttachments.js
from https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1116:
- The field label for "Topics" should always be "Topics" - please remove the label that is changing to "Add more topics"
- "Resource links" should be "Link to TTA resource used" when in edit mode 
- "Attach any available non-link resources" should be "Attach any non-link resources"
This label should be closer to the "Select and upload" button than to the radio button above
- remove *indicates required field from below Goals and Objectives
- "Goal" should be Recipient's goal
- "Objective" should be "TTA objective"
- "Resources" should be "Resource links" (links)
- "Resources" should be "Resource attachments" (attachments)
- "Status" should be "Objective status"
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1116
> [TTAHUB-1116] AR content wording changes

- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js
- src/services/goalServices/saveGoalForReport.test.js
- src/services/goals.js
Previously, an objective would need to have a title in order to be saved. With this change, if any part of the form is filled out, an objective will be saved.
To reproduce bug on main ar redesign:
- create an AR with one recipient
- use an existing goal with an objective
- select the objective, but don't save
- click "Yes" under file upload
- change your mind and select "Create a new objective"
-  note uploading message appears which is correct
- enter TTa provided and "Save draft"
- note the TTA provided is saved leading someone to believe that they saved their TTA provided.
- click "Save draft" again
- the TTA provided is gone
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1188
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1197
> [TTAHUB-1188] Fix issue where objectives with some data weren't being saved

- frontend/src/components/FileUploader/FileTable.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
Store the objective ID in the form data so it is findable when using an existing objective
Also add some verbiage, hopefully temporarily, to cover the case when the file is successfully uploaded but not scanned.
To recreate bug:
Create a Goal and Objective from RTR. Then while using both on a recipient report, you should be unable to add a file attachment.
> [TTAHUB-1195] store ID in form data & add stopgap file upload label

- frontend/src/pages/ActivityReport/Pages/Review/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/index.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js
Reviewing a report and uploading a file to the AR Objective are two additional areas of the site where you might have a multi-second wait with no feedback. This change adds the application loading screen to those two areas.
Review a submitted AR. Note the loading screen.
Upload a file to an objective on the AR. Note the loading screen.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1168
> [TTAHUB-1168] add loaders to file upload and AR review

- frontend/src/components/RichEditor.js
If the user enters TTA Provided that's larger than the default height of the text box we need to maintain the new height.
Create an RTR add a goal with several objectives who's TTA Provided is larger than the default text box height.
- Save draft should maintain the heights
- Save goal and editing the goal should still maintain the heights
- Leaving the page and coming back should maintain heights
- Reducing the text height should still auto adjust
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1192
> [TTAHUB-1192] Fix TTA Provided to keep auto grow height

- frontend/src/components/GoalForm/__tests__/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/components/GoalForm/index.js
This change fixes the bugs described in 
- https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1203 (ids were being tracked and used to overwrite the first goal when adding multiple goals on the RTR)
- https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1204 (save draft when editing multiple goals automatically uses first goal's objectives)
Add a new goal to the RTR, 2 objectives with topics, resources, attachments. Save draft then save and continue.
Add another goal with distinct data, then save draft. All should be well (second goal's info all visible)
Save and continue, review info, then submit. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1203
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1204
> [TTAHUB-1203] Fix issues with saving multiple goals/save draft on the RTR

- frontend/src/pages/ActivityReport/Pages/components/GoalForm.js
- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalPicker.js
this fixes the following bug on main-ar-redesign:
1. create recipient form
2. create new goal, fill it out
3. create new objective, fill it out
4. click save draft and notice you are still not able to upload attachments
do the above steps on this branch, notice that after you save draft, you are able to add attachments
ensure that the `Objective` component is receiving a valid `id` for its `objective` prop:
previously, after saving draft:
> Set objectives

- src/routes/goals/handlers.js
An incorrect parameter was making it way to the SQL for destroy goals, and so the handler was never getting called
Create a goal on the RTR. Delete it. You should be able to do so without error.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1213
> [TTAHUB-1213] Fix unable to delete goal from the RTR

- src/migrations/20221122125923-update-aro-completed-status.js
- src/models/hooks/objective.js
If a report was submitted before the update. But was approved after the update. The ARO status will still have 'completed' status. This is causing an issue in an objective hook.
Using main restore the latest DB from **11/17** and use the **user 195** to approve report **25040**. Notice that the approve fails with a server error in the hook. Pull this branch and run migrations. Now attempt to approve the report again you shouldn't get any errors.
In addition the ARO table should have all 'Completed' statues update to 'Complete'.
As a final test create a new report and approve it.
> Update ARO status from 'Completed' to 'Complete'

- src/migrations/20221122125923-update-aro-completed-status.js
- src/services/goals.js
Bug was found were users are unable to delete objectives.
You should be able to delete an objective (aro) from a report then revisit and see it still deleted.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1223
> [TTAHUB-1223] Users unable to delete objectives

- frontend/src/components/ControlledDatePicker.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js
Remove min date from next step. Still noticed strange validation behavior, further investigation revealed double validations happening - one on the form level, one inside the react component. Removed the react component "extra" validation so we weren't doubling up. 
Use the next steps repeater with a combination of valid and invalid info. Delete and add steps. Check the validation behaves as expected.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1224
> [TTAHUB-1224] Remove min date and improve validation on next steps

- .circleci/config.yml
- src/routes/files/handlers.js
- src/services/scanQueue.js
This change
- fixes a bug with the file handler where express was trying to send an already-sent response
- [properly passes options to the bull queue.add function](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueadd)
Confirm file uploads still work, other jobs are still being fired
> Issues with queue and upload service

- frontend/src/components/Container.js
- frontend/src/widgets/TopicFrequencyGraph.css
- frontend/src/widgets/TopicFrequencyGraph.js
The controls on the Topic Frequency graph scroll with the graph, which makes it easy to lose the title or the ability to switch to a table.
View the Topic/Frequency graph and scroll it. Notice the controls & title stay in place while only the graph scrolls
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1246
> [TTAHUB-1246] fix controls regardless of scroll on topic freq graph

- src/services/createOrUpdateGoalsForActivityReport.test.js
There is a test failing on the BE but doesn't fail when running locally. It looks like its just an ordering thing with the contents of the array. This is a fix for the order.
Verify code change and make sure tests pass.
> Fix BE test for PROD PR

- src/services/goals.js
A bug was found that will display two objectives with the same text if one of them ends with a blank space ' '.
Right now when we attempt to check if an objective exists on the BE we trim the title. When we retrieve the Objectives for the FE we should do the same.
**NOTE:** If the objectives have different statuses we will show two of them regardless of text.
Find or create a goal that has two objectives with the same text except one of them has a trailing white space. Create a report using this Goal we should only show the objective once in the list. Creating and updating the objective on the report should yield the correct objective id in the ARO table.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1240
> [TTAHUB-1240] Prevent showing duplicate objectives with trailing spaces

- src/services/createOrUpdateGoals.test.js
- src/services/goals.js
It looks like we erroneously started sorting the RTR goals by the AR column when we merged the AR order PR. 
RTR objectives maintain their order
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1202
> [TTAHUB-1202] Sort RTR goals by the correct column

- package.json
see: https://github.com/HHS/Head-Start-TTADP/pull/1209#discussion_r1040050147
changes to frontend files should not trigger nodemon
> fix nodemon ignores

- frontend/src/Constants.js
- frontend/src/components/filter/FilterPills.js
- frontend/src/components/filter/__tests__/FilterMenu.js
- frontend/src/components/filter/__tests__/FilterPills.js
- frontend/src/components/filter/activityReportFilters.js
We want to show two different conditions for the 'My reports' filter.
- 'where I'm the'
- 'where I'm not the'
Create a new filter using the 'My reports' filter. The condition choices should be updated and when applied we should show the correct case for "I'm" in the filter pills.
> Show correct condition text for 'My reports' filter

- frontend/src/components/Navigator/__tests__/index.js
- frontend/src/components/Navigator/index.js
- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/index.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
- frontend/src/pages/RecipientRecord/pages/TTAHistory.js
- playwright.config.js
- tests/other-entity-report.spec.ts
Fixes two bugs with other entity reports, one of which was introduced by #1209, the other I'm not sure. Add an e2e test to validate the fix. 
You can see these bugs on main
- First bug: Start an other entity report. On the activity summary, select only the other entities, then proceed to cycle through the links in the activity report side navigation. You should find yourself stuck by a syntax error.
- Second bug: Complete an other entity report. You'll find that you cannot get the "goals and objectives" side nav label to show complete if you proceed through the report in order (it shows complete when you save and continue onto "supporting attachments," but if you proceed to next steps it reverts to "Not started")
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1254
> [TTAHUB-1254] Fix bug with other entity reports

- src/services/goals.js
Force slow query to run in parts to reduce intermediate data set. Users report had an intermediate data set with 59,535 rows.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1277
> [TTAHUB-1277] PD type events are unusable

- package.json
- tests/README.md
- tests/common.ts
- yarn.lock
It would be nice to be able to write e2e tests for things that depend on the order of certain time-based operations, like the autosave.
Since playwright doesn't support advancing timers (yet), this PR adds `sinon` as a devDependency and a helper in `tests/common.ts` that injects a `__clock` method into the `window` of our tests so that we can do this:
```typescript
import { test, expect } from '@playwright/test';
import { useClock } from './common';
useClock(test);
test('advance time', async ({ page }) => {
await page.evaluate(() => (window as any).__clock.tick(120_000));
});
```
> playwright improvements: ability to advance timers

- .circleci/config.yml
- .gitignore
- playwright.config.js
Changes to artifacts:
* Storage directory changed to /playwright
* Reports at /playwright/reports
* Test results at /playwright/test-results
* Reports and test results are now always generated (and stored in CI), even on success
Other things:
* CI config updated to respect the new storage path
* gitignore updated to ignore new storage path
Check CI artifacts stored for this branch's most recent commit.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1292
> [TTAHUB-1292] Playwright artifacts

- playwright.config.js
We're seeing e2e test failures in CI that are related to poor CI performance, causing the test to timeout when it normally would have passed.
This PR just increases the timeouts to something more reasonable to prevent these flaky failures.
> Playwright - increase timeouts

- src/policies/objective.js
- src/policies/objective.test.js
- src/routes/files/handlers.js
- src/routes/files/handlers.test.js
- tests/activity-report.spec.ts
Based on a user support request, we identified that the logic for checking if an objective allows file uploads to be faulty. This change allows uploads to an objective if the objective is on an approved AR. It also adds a check to see if the objective is complete OR if the goal is closed.
Test objective file uploads
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1301
> [TTAHUB-1301] Allow adding files to objectives on approved AR

- frontend/src/pages/ActivityReport/__tests__/formDataHelpers.js
- frontend/src/pages/ActivityReport/formDataHelpers.js
- src/routes/activityReports/handlers.js
This PR fixes a recent bug where the back end was tracking which goals were actively being edited and which were not.
Essentially, a goal would still be marked as being edited even though the report was submitted, and the review section was not being populated. This fix makes two changes. 1) It prevents the goals being sorted by the "activelyEditedGoal" attribute on the frontend if the goal is not draft or needs action and 2) updates all activity report goals associated with a report on submission so that they are all set to isActivelyEdited: false, and so any weird states where a report is somehow submitted without closing the goal form are handled.
I am unsure of how to reproduce the bug through the UI - it may be a result of reports created before this improvement was released and …
> [TTAHUB-1307] fix bug with review and actively edited goals

- package.json
- yarn.lock
main build fails because of:
```
Security vulnerabilities were found that were not ignored:
[
{
"name": "jsonwebtoken",
"version": "8.5.1"
}
]
```
the latest non-vulnerable version appears to be `9.0.0` according to https://security.snyk.io/package/npm/jsonwebtoken/8.5.1
> bump jsonwebtoken to `9.0.0`

- src/models/hooks/activityReport.js
- src/models/tests/objectiveStatus.test.js
- src/services/goals.js
- src/services/goals.test.js
- src/services/recipient.js
This solves a bug that I introduced as part of the fix for [TTAHUB-1240](https://github.com/HHS/Head-Start-TTADP/pull/1204/files).
In attempt to prevent showing duplicate objectives with leading or trailing spaces we perform a trim on the returned objective title. We cannot do this as it flags the title as changed in the Sequelize instance. This causes a validation error to be thrown if the goal is on an approved report (user case).
For now we will see if a non-trailing version of the objective title exists. Else we will return the title as is with spaces.
You can edit recipient 'Blueprints' for G-20778, G-12658 and attempt to change all statuses to complete and save.
OR
Create a goal with a few objectives on an approved report. Make sure one of the Objective titles has trailing spaces. …
> [TTAHUB-1317] Only find matching objectives based on trim

- frontend/src/Constants.js
- frontend/src/components/__tests__/CloseSuspendReasonModal.js
Add an additional reason to the modal that pops up when a goal is closed or suspended.
Close a goal from the recipient record. Note that "Regional office request" now appears as a reason. Select it and note that the 1) the goal is closed and 2) the database shows the correct reason.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1289
> [TTAHUB-1289] Add "regional office request" as a goal closed reason

- tests/recipient-search-page.spec.ts
Add a simple playwright test to validate the recipient search page
CI passes. Review test and make sure it makes sense
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-716
> [TTAHUB-716] add playwright test for recipient search page

- src/tools/createAwsElasticSearchIndexes.js
- src/tools/createAwsElasticSearchIndexesCli.js
The "bulk" index for OpenSearch seems to have a limit to how big a request can be. This change makes the job process each request in a batch of any size.
**Note:** I added a prompt that allows you to specify the number of reports to process in batch.
- Make sure the test passes.
- Run the script against a db.
> Update index job to run in batch

- src/tools/createAwsElasticSearchIndexes.js
It seems that the issue we are having might have to do with overloading the ES queue.
This attempts to fix it by awaiting each batch call in the loop.
```
Write rejections
A 429 error message as a write rejection indicates a bulk queue error. The es_rejected_execution_exception[bulk] indicates that your queue is full and that any new requests are rejected. This bulk queue error occurs when the number of requests to the cluster exceeds the bulk queue size (threadpool.bulk.queue_size). A bulk queue on each node can hold between 50 and 200 requests, depending on which Elasticsearch version you are using.
```
https://aws.amazon.com/premiumsupport/knowledge-center/opensearch-resolve-429-error/
> Await each bulk before starting a new one

- src/routes/search/index.js
Because we are going to be populating Elasticsearch data shortly we need to remove this unused endpoint for now.
Make sure this endpoint is NOT accessible: 
http://localhost:3000/api/search?index=activityreports&fields=context&fields=specialistNextSteps&query=zero
> Remove search endpoint (for now)

- src/routes/transactionWrapper.js
in order to minimize db interaction move the setting of audit log variables to the transaction wrapper.
preform any modifying action via the web site. notice that only a single instance of setting the audit log is done per transaction.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1186
> [Ttahub-1186] single auditlog db interaction per request

- src/services/recipient.js
Creating a goal with two grants would show incorrect grant number and status on the RTR.
1.     Create a common goal for a recipient with 2 grants
2.     Create a draft report for the first grant and use the common goal
3.     Create a second draft report for the second grant and use the common goal
4.     Note that on the RTR page, one of the objectives for the recipient show an incorrect grant numbert and status (screeshot)
5.     Complete and approve the first AR
6.     On the RTR page the goals are separated and the grant numbers and statuses are correct
7.     Complete and approve the second AR
8.     Note that the goals are now combined and display an incorrect grant numbert and status (screeshot)
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1368
> [TTAHUB-1368] RTR showing incorrect grant number and status on objective

- frontend/src/components/GoalCards/icons.js
The title says it all.
Began here: https://adhoc.slack.com/archives/C0492R8BN4Q/p1674590379426339
before
after
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1391
> [TTAHUB-1391] Use `faPenCircle` instead of `faPencilAlt` as the draft icon

- frontend/src/components/ActivityReportsTable/__tests__/index.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/components/MediaCaptureButton.js
- frontend/src/components/Navigator/index.js
- frontend/src/components/PrintToPDF.js
- frontend/src/components/TableHeader.js
- frontend/src/components/__tests__/MediaCaptureButton.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js
- frontend/src/pages/ApprovedActivityReport/index.js
- frontend/src/pages/Landing/MyAlerts.js
- frontend/src/pages/Landing/ReportMenu.js
- frontend/src/pages/Landing/index.js
- frontend/src/pages/RecipientRecord/pages/PrintGoals.js
- frontend/src/pages/RecipientRecord/pages/TTAHistory.js
- frontend/src/pages/RecipientSearch/components/RecipientResults.js
- frontend/src/pages/RegionalDashboard/index.js
- frontend/src/widgets/TopicFrequencyGraph.js
- frontend/src/widgets/TotalHrsAndRecipientGraph.js
Following the request in the Jira, unique ids were added to assorted buttons on assorted pages. This is for the easy attachment of handlers in Google Tag Manager.
Compare the rendered DOM with the list in the Jira ticket. Note the comments where I've explained changes I made to the original request
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1327
> [TTAHUB-1327] Add unique ids to buttons across the applications for analytics

- tests/activity-report-text-search-filter.spec.ts
On the e2e test for text search, playwright tries to click a button that doesn't exist, now that we're in February. This PR types the relevant date in instead.
CI passes
> fix search e2e test

- frontend/src/components/GoalForm/ObjectiveForm.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/ObjectiveForm.js
- frontend/src/components/GoalForm/__tests__/ResourceRepeater.js
Update to goal resource link labels and tool tip text for AR vs RTR.
It should be "Link to TTA resource"
The tooltip should be corrected to: "Copy & paste web address of TTA resource used for this objective. Usually an ECLKC page."
For RTR tooltip: "Copy & paste web address of TTA resource you'll use for this objective. Usually an ECLKC page."
Currently reads: "Copy and paste web addresses of TTA resource describing used for this objective. Usually this is an ECLKC page.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1153
> [TTAHUB-1153] Change goal resource link label and tool tip text

- src/services/mailerLog.js
- src/services/mailerLog.test.js
This fixes an error where a email subjects longer than 255 characters were trying to be inserted into a varchar255 column in the mailer logs table.
> prevent long insertions into the mailer log

- frontend/src/widgets/TotalHrsAndRecipientGraph.js
- src/widgets/totalHrsAndRecipientGraph.js
- src/widgets/totalHrsAndRecipientGraph.test.js
before:
after (same date range, same data set):
when you have a date range of about a 30 days, covering the end of the month and the beginning of another, you end up with an x-axis of day numbers that might look like: `[26, 27, 28, 29, 30, 1, 2, 3, 4, ...]`
when plotly renders this, it will draw that sixth number in position 1, the next in position 2, etc. that's why we're seeing that weird line reversal.
this PR just makes sure the x-axis values can be parsed in the correct order by using a date in MMM-DD format.
change the date range, ensuring:
- the range in total is less than 31 days
- the range overlaps the end of one month and the beginning of another
- make sure there's no wonky lines
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1393
> [TTAHUB-1393] wonky chart lines

- .production.sequelizerc
We were missing a quotation in a config file that was preventing the migrations from running.
CI passes, migrations run
> Fix typo in .production.sequelizerc

- docker-compose.yml
my migrations were failing because the docker container runs out of shared memory (by default 64mb), so this PR just increases shared memory for this container to 1gb
before:
after:
> Increase db container's shared memory

- .circleci/config.yml
- src/lib/awsElasticSearch/index.js
- src/lib/awsElasticSearch/index.test.js
- src/lib/awsElasticSearch/returnsAllResults.test.js
- src/tools/createAwsElasticSearchIndexes.test.js
Per Patrice we can keep phrase matching and limit results (2k).
Searching for phrase like "lead water" should only return reports that contain those terms in that order.
Searching for a single word like 'water' will use a wild card match to find anything that contains 'water'.
We need to make sure that staging no longer hangs and returns only 2k results.
> Hook up phrase matching with limit

- frontend/src/components/ActivityReportsTable/__tests__/index.js
- frontend/src/components/ActivityReportsTable/index.js
- frontend/src/pages/Landing/index.js
- frontend/src/pages/RecipientRecord/pages/TTAHistory.js
- frontend/src/pages/RegionalDashboard/index.js
The request was - when a filter is changed, reset the table's pagination elements to page 1. This change was only made to the activity report tables.
Add a filter - change the page on the AR table. Change the filter, the page should revert to the first.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1444
> [TTAHUB-1444] Reset AR table when the filters change

- frontend/src/components/GoalCards/components/StatusDropdown.js
- frontend/src/components/GoalCards/components/__tests__/StatusDropdown.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
- src/routes/goals/handlers.js
- src/routes/goals/handlers.test.js
- src/services/goalServices/goalUpdate.test.js
- src/services/goals.js
Remove the option to set a "not started" goal to "in progress" from the RTR.
Confirm that the option is no longer present
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1419
> [TTAHUB-1419] Remove "in progress" from "not started" dropdown

- frontend/src/App.js
- frontend/src/components/AppWrapper.js
- frontend/src/pages/RecipientRecord/index.js
This fixes a visual bug with the site alerts. The bug appears only the recipient record pages that have the sub navigation at the top.
Before:
After:
> fix visual bug with alerts

- frontend/src/components/filter/FilterMenu.js
- frontend/src/components/filter/__tests__/FilterMenu.js
Opening the filter menu and triggering the onBlur validation then cancelling leaves the filter in a bad state.
- Go to AR landing (with no preexisting filters)
- Click the filter menu to trigger the 'blur' validation
- Click cancel
- Reopen the filter menu 
- You should still see the original filter with the validation
> fix issue when cancelling filter

- frontend/src/pages/ActivityReport/Pages/Review/FileReviewItem.js
- frontend/src/pages/ActivityReport/Pages/Review/__tests__/FileReviewItem.js
If virus scanning fails for a supporting attachments, a "not approved" message is displayed in the review page for supporting attachments. The failure does not indicate that the file is not uploaded, or that it has failed the virus scan. It simply means that the virus scan was not yet successful. This "not approved" message is causing confusion as it does not clearly communicate the situation to the end user. 
This PR removes that message and simply shows nothing if the file is not approved.
Upload a file to supporting attachments. Manually set the file to one of the statuses besides approved in your database. Review the report. You should see nothing.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1503
> [TTAHUB-1503] remove "not approved" from review attachments section

- frontend/src/components/GoalForm/ObjectiveStatus.js
- frontend/src/components/GoalForm/__tests__/ObjectiveStatus.js
- src/services/goals.js
Removes the objective status dropdown from the the create goals from if the goal is "not started," show the read only value instead. 
Confirm that the dropdown has been removed.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1422
> [TTAHUB-1422] Remove objective status dropdown from create goal form when goal is not started

- frontend/src/components/filter/FilterGoalType.js
- frontend/src/components/filter/__tests__/FilterGoalType.js
- frontend/src/components/filter/__tests__/goalFilters.js
- frontend/src/components/filter/goalFilters.js
- frontend/src/pages/RecipientRecord/pages/constants.js
- src/models/goal.js
- src/scopes/goals/goalType.ts
- src/scopes/goals/index.js
- src/scopes/goals/index.test.js
Add an RTTAPA filter to the goals & objectives page. Filter by "RTTAPA" or "Non-RTTAPA" goals
Check the filter on the page within the recipient record
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1137
> [TTAHUB-1137] Add RTTAPA filter to goals & objectives page

- src/services/users.js
This is a re-write for Sequelize to raw SQL to fix the perf issue of users who have ONLY read only access to all regions.
- Make sure all tests pass.
- Using a user that has ONLY read-only access to ALL regions should return data within a few seconds (ie NOT 30 seconds).
> Anniversary Statistics Performance Fix for Read-only Users

- src/lib/transform.js
- src/lib/transform.test.js
The csv export was skipping objectives that contained goals for other recipients. This change makes sure if the goal number already exists we add the additional ids.
- Export a report that contains one or many goals for multiple recipient's (ID: 13091). 
The goal Id column should contain and ID for each recipient.
- Make sure the export behaves the same as before when exporting multiple reports.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1552
> [TTAHUB-1552] Fix csv to include other recipient goal ids

- src/scopes/activityReport/index.test.js
- src/scopes/grants/index.test.js
- src/services/activityReports.js
Not sure [this branch](https://github.com/HHS/Head-Start-TTADP/pull/1350) was passing CI before I merged it, but I guess there was an errant console log hanging out. This PR removes the console.log so that the CI can pass.
I also added some additional stuff to make sure we don't get duplicate group names
CI passes
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1380
> remove console log from backend service and make groups test less flaky

- frontend/src/pages/RecipientSearch/index.js
- src/scopes/activityReport/group.ts
- src/scopes/grants/group.ts
This PR addresses an issue revealed by some flaky unit tests where commas would disrupt the "my groups" filter. Upon further investigation, I had added some "cleverness" that isn't needed. (I knew how the backend expects query parameters but I misunderstood how they'd be coming from the frontend.)
CI passes. You can add a group with a comma in it.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1380
> Fix flaky tests on the groups scope

- frontend/src/pages/ActivityReport/Pages/Review/Approver/Review.js
- frontend/src/pages/ActivityReport/Pages/Review/Approver/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/Approver/index.js
When reviewing a report for approval. We want the approver to see the submitted date if its available.
Submit a report for approval. When reviewing the report the they should see the submission date.
If there is no submission date we hide it.
**Mockup:**
https://www.figma.com/file/7lFZynR1T97cfJbCIgBHD4/AR-date-submitted?node-id=1%3A2124&t=W6NMP4c5QWXV4G6S-0
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1487
> [TTAHUB-1487] Add submitted date for approvers to see

- src/widgets/topicFrequencyGraph.js
- src/widgets/topicFrequencyGraph.test.js
On the regional dashboard the topics and frequency graph only shows topics from AR's. We want to include topics from objectives on the AR.
Topic counts should reflect both AR's and AR objective topics.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1543
> [TTAHUB-1543] Include objective topics in topics frequency graph

- frontend/src/pages/RegionalGoalDashboard/__tests__/GoalsPercentage.js
- frontend/src/pages/RegionalGoalDashboard/__tests__/index.js
- frontend/src/pages/RegionalGoalDashboard/index.js
- frontend/src/widgets/GoalStatusGraph.js
- frontend/src/widgets/RegionalGoalDashboard/GoalsPercentage.js
- Only show the percentage of goals in the percentage widget.
- Change the default date filter to 7/1/2022 - current day.
> Goal dashboard - default filter and only show percentage of regional goals

- frontend/src/components/GoalCards/__tests__/GoalCards.js
- frontend/src/components/GoalCards/components/ObjectiveButton.js
- tests/activity-report.spec.ts
On the recipient record/goals and objectives, when the objectives is shown, the button says "hide." When the objectives are hidden, the button says "view."
Visit the recipient record page and confirm the above behavior
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1413
> [TTAHUB-1413] Toggle button language depending on whether objectives are expanded

- frontend/src/fetchers/activityReports.js
- src/services/activityReports.js
Incorrect topic data was being fetched for the Activity Reports table. Based on some of the changed models, the logic had to be rearranged, which allowed work to be delegated away from the frontend and into the service.
Removal of topics from objectives on an unlocked activity report, is not reflected in the activity report table.
Steps:
The bug as reported in the jira is below. Follow the steps and ensure that only one topic is listed.
- Create an AR with an objective that has topic A
- Submit and approve
- Unlock the report
- Select B for a topic instead of A
- Submit and approve
- Note in the AR table both topics are listed
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1566
> [TTAHUB-1566] simplify logic for fetching topics, exclude unused topics

- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/formDataHelpers.js
- src/services/activityReports.js
Adding additional recipients to an activity report after creating a goal would clear the goal. This change fixes that bug.
These are the steps from the original Jira. Follow them and ensure the bug is no longer present.
- create a new AR
- add one recipient
- create a new goal with one objective having resource links and tta
- instead of clicking "Save goal", navigate to the activity summary using the navigator's link
- use the navigator to enter the "Goals and Objectives" section
- confirm that the goal is there (write mode)
- navigate to the activity summary using the navigator's link
- add a second recipient
- use the navigator to enter the "Goals and Objectives" section
- note the goal is no longer there
- select the goal from the dropdown
- note the objective is gone along with the …
> [TTAHUB-1560] fix parsing of goals when activityRecipients are updated

- frontend/src/pages/ResourcesDashboard/__tests__/index.js
- frontend/src/pages/ResourcesDashboard/index.js
Add a default filter to the resources dashboard from 07/01/2022 to today.
When you go to the resources dashboard there should be default date filter applied.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1586
> [TTAHUB-1586] Add default date filter to resources dashboard

- src/services/goals.js
"separate: true" is causing queries to behave unexpectedly
Most recent prod dump:
On branch main: load report 29122 as user 10
Try to delete first objective from second goal
Notice that it is impossible
Load this branch and refresh
Note that the objective disappears.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1598
> [TTAHUB-1598] remove separate: true from goal/objectives query

- src/widgets/overview.js
The recipient total count on the regional dashboard was not matching the sum when running for the individual regions.
Make sure the total recipient count for all regions matches the count for the individual regions.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1529
> [TTAHUB-1529] Fix recipient count for all regions

- src/services/dashboards/resource.js
exclude reports with null startDate
Some reports have a null startDate, these need to be excluded as they result in the tables converting the null startDate to Dec 1969 which appears as a column to the right of the total column.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1590
> [TTAHUB-1590] Resource page issue with reports with null startDate

- frontend/src/components/Navigator/components/SideNav.scss
- Updated border-width of side-nav active link from 2px to 4px to match design library
- Added hover state to side-nav links to match design library (background-color and text color)
Create an activity report, then navigate to different sections of the report using the form navigator. When hovering over one of the list items in the navigator, the background will turn grey. The active state of the list item will have a 4px blue border, and the link text will not have a text underline and the text will be bold.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1286
> Fixed border width and added hover styles

- src/lib/updateGrantsRecipients.js
- src/lib/updateGrantsRecipients.test.js
- src/migrations/20230327203917-impersonation-audit-log.js
- src/models/auditModelGenerator.js
- src/models/tests/auditModelGenerator.test.js
- src/services/currentUser.js
- src/tools/processData.test.js
Adds the `dml_as` column to audit log tables. This column allows us to track actions performed during an active impersonation session.
Impersonate a user, perform an action and verify that the `dml_as` field is populated.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1324
> [TTAHUB-1324] Impersonation audit log support

- src/services/goalServices/getGoalsForReport.test.js
- tests/activity-report.spec.ts
Added two tests:
- Unit test to verify correct number of objectives are returned.
- E2e test to verify user can remove objective.
Test1: 
Adding a separate to the goals function caused extra objectives to be returned that were not in the ARO table.
The unit test aims to prevent this from occurring in the future.
In goals service **getGoalsForReport()** add a separate to the ActivityReportObjectives join the test should fail. Uncomment the separate the test should pass.
Test2: 
E2e to ensure we can successfully remove an objective.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1607
> [TTAHUB-1607] Test to verify correct number of objectives are returned and objective remove e2e

- src/migrations/20230328124028-remove-orphan-goals.js
- src/services/goalServices/goals.test.js
- src/services/goalServices/saveGoalForReport.test.js
- src/services/goals.js
This PR does two things:
- Adds a script to cleanup orphan goals and objectives along with associated tables.
- Deletes goals created via AR if they are not being used.
- Review all code and SQL.
- Run the migration make sure it competes successfully. 
**NOTE:** A script Garrett wrote should give you an idea of what we can expect to be deleted on the JIRA TTAHUB-1130.
- Create a goal on a report and remove the Goal from the report and save. The goal should be removed from the DB.
- Create a goal on another report then use the same goal on a new report and remove it and save. The goal should NOT be removed from the db.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1130
> [TTAHUB-1130] Orphaned goal cleanup

- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportSection.scss
The first column side of the Approved AR didn't match the mockup, per the ticket
Create and approve a report, you'll see the width of the first column has tightened.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1133
> [TTAHUB-1133] Update layout on approved AR to match mockup

- src/routes/files/handlers.js
- src/services/deleteSpecificActivityReportObjectiveFile.test.js
- src/services/files.js
A bug was found when ARO files from other reports are being deleted.
1. Create a ARO with a new goal and objective with a file attachment.
2. Approve the first report (or don't).
3. Create a new Report use the same goal created in step 1.
4. Delete the file attachment and submit the report.
5. Check the database (or the first report) you should still see an entry for the ActivityReportObjectiveFile linked to the first report.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1639
> [TTAHUB-1639] Get ARO files first then delete

- frontend/src/pages/Admin/PermissionHelpers.js
Discovered an issue when using certain seeded users. Essentially, some of the users have permissions for region 14, which isn't a region. This would cause javascript errors when exploring the app as a seeded user. I didn't want to remove or change the seed data because I'm not sure how it might be used in tests, so I wrote a line of code to prevent the issue on the frontend.
Load the test/seed db (you can probably do this with the script bin/load-test-db). In the admin interface, view user 1. You should not get a white screen of death.
> [TTAHUB-NO-TICKET] Fix permissions helper with seeded data

- src/routes/externalApi/activityReports/handlers.js
- src/serializers/activityReports.js
- src/services/activityReports.test.js
- tests/api/externalapi.spec.ts
validates the `/v1/activity-reports/display/:reportDisplay` endpoint
while writing this test I discovered that this handler just didn't work at all, so this PR also fixes that
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1355
> [TTAHUB-1262] [TTAHUB-1357] API validation: /v1/

- src/scopes/activityReport/reportText.js
- src/scopes/index.js
- tests/activity-report-text-search-filter.spec.ts
We were previously using Elastic Search to find report IDs that match some query. This PR removes that functionality in favor of using the filter pattern that we've created. It still matches on the same things that ES was indexed on, so results should be basically the same.
Apply the report text filter and check your backend logs. Validate that the generated query looks correct to you.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1694
> [TTAHUB-1694] Use filter pattern for reportText instead of ElasticSearch

- src/migrations/20230424000000-correct-model-db-misalignment.js
The existing `down` is a vestigial cut-and-paste error and we definitely don't want it to accidentally remove that column because `down` ran.
> remove erroneous down

- src/services/goalTemplates.ts
I let VS Code generate some inferred type notations from the JSDoc comments, which seem to sometimes (but weirdly, not always) spike the CI. They violate the no-implicit any tslint rule.
I'm sure it would be better to just write accurate type notation but given how poorly it interacts with sequelize, I'm not sure that's a priority right at the moment.
CI passes
There's no ticket for this.
> remove auto generated type notations

- frontend/src/fetchers/Admin.js
- frontend/src/fetchers/__tests__/Admin.js
- frontend/src/pages/Admin/Redis.js
- frontend/src/pages/Admin/__tests__/Redis.js
- frontend/src/pages/Admin/index.js
- src/routes/admin/index.js
- src/routes/admin/redis.test.js
- src/routes/admin/redis.ts
Creates an admin page where we can view basic redis info and run the "flush all" queue.
Log in as an admin with an active redis client. Confirm you can see the stats and that you can run "flush cache."
> [NO-TICKET] Create redis admin page

- src/scopes/activityReport/deliveryMethod.js
The title kind of says it all. `in person` matches nothing, because in the database it's stored as `in-person`.
Apply the delivery method filter and ensure results come back, whereas before nothing is found.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1719
> [TTAHUB-1719] delivery method filter bug: "in person" should be "in-person"

- frontend/src/pages/Landing/MyAlerts.js
- frontend/src/pages/Landing/__tests__/MyAlerts.js
- frontend/src/pages/Landing/__tests__/ReportsRow.js
- frontend/src/pages/Landing/mocks.js
On the MyAlerts table, we should not show the "Delete" context menu item if the user is not the creator or collaborator on the AR. If the are neither, and are just the approver, the delete operation silently fails with a 403. This PR only adds this menu item if the user is creator/collaborator.
- Be a user that has alerts for an AR that they are ONLY an approver on
- Notice you only see "View"
- Be a user that has alerts for an AR that they are creator/collaborator of
- Notice that you additionally see "Delete"
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1709
> [TTAHUB-1709] Don't show 'Delete' if user is not creator or collaborator on AR

- frontend/src/pages/ApprovedActivityReport/__tests__/ApprovedReportV2.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
We found a bug that was using a display value that could be 'Recipient' OR 'Recipient's' for a IF check. This was causing recipient steps to show under the Other-Entity heading.
We shouldn't see the OE header on an approved Recipient report.
1. Create a single recipient report with next steps.
2. Approve the report.
3. View the approved report we should only recipient next steps.
--
1. Create a single other entity report with next steps.
2. Approve the report.
3. View the approved report we should only other entity next steps.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1737
> [TTAHUB-1737] Correct display recipient vs oe next steps

- src/services/files.js
There's a typo in `createActivityReportObjectiveFileMetaData`. We try to create an `ActivityReportObjectiveFile` with an `objectiveId`, but there is no `objectiveId` column on this table. This fails with an error:
`null value in column "activityReportObjectiveId" violates not-null constraint`
This should be `activityReportObjectiveId`, as suggested by the name of the method. 
This is tested here (not mocked):
https://github.com/HHS/Head-Start-TTADP/blob/02ac41d44b59ad55c26ca02fc81a0d2514594046/src/scopes/activityReport/index.test.js#L2426-L2432
You can test by validating this usage.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1736
> [TTAHUB-1736] Bug (typo) in `createActivityReportObjectiveFileMetaData`

- frontend/src/pages/ApprovedActivityReport/__tests__/ApprovedReportV2.js
- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
Added anticipated goal close date to the approved AR screen for V2 reports.
Set a anticipated close date on an approved report you should see it when viewing the approved report.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1681
> [TTAHUB-168]1 Anticipated close date on approved AR's (v2)

- .gitignore
- README.md
- src/services/goals.js
- src/services/goals.test.js
Apply whitespace trim during goal creation to prevent duplicate goal templates from being created due to prefix and suffix adds.  
Create a goal with excess whitespace. From both AR Goals & recipient-tta. Check db for trimmed goals
```
<---There are 5 spaces--->     
```
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1721
> TTAHUB-1721 Trim Goals and Objectives prior to creating in db

- src/widgets/topicFrequencyGraph.js
- src/widgets/topicFrequencyGraph.test.js
Topics that appeared multiple times on a report were being counted multiple times on the topic frequency graph, so that the count was showing a topic's total usage on all filtered reports, not a count of said reports.
- Visit regional dashboard
- Filter by a single topic
- Confirm that the number in the tooltip on the topic frequency graph and the total number of activity reports all agree
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1770
> [TTAHUB-1770] only count topics once

- frontend/src/components/GoalForm/ObjectiveTopics.js
- frontend/src/components/GoalForm/__tests__/ObjectiveForm.js
- frontend/src/components/GoalForm/__tests__/ObjectiveTopics.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objective.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/Objectives.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/OtherEntity.js
We need to use a more generic tag for fetching data from confluence.
Check the objective topics guidance drawer. Make sure that it contains the correct information.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1775
> [TTAHUB-1775]Update tag for fetching from confluence

- frontend/src/pages/AccountManagement/components/Groups.js
- frontend/src/pages/AccountManagement/components/__tests__/Groups.js
- frontend/src/pages/Landing/constants.js
- frontend/src/pages/RecipientRecord/pages/constants.js
- frontend/src/pages/RecipientSearch/constants.js
- frontend/src/pages/RegionalDashboard/constants.js
- frontend/src/pages/RegionalGoalDashboard/constants.js
- frontend/src/pages/ResourcesDashboard/constants.js
- Change the default language for when there are no public groups created yet
- Auto-alphabetize all the filter options throughout the site.
Confirm that the my groups section says "No one in your region has created a public group." when there are no public groups in your region yet.
Confirm that the filters on the landing page & the regional dashboard are alphabetized.
> [TTAHUB-1779] update some text & alphabetize filter configs

- frontend/src/pages/ApprovedActivityReport/__tests__/index.js
- frontend/src/pages/ApprovedActivityReport/index.js
- src/policies/activityReport.js
- src/policies/activityReport.test.js
- src/policies/goals.test.js
In a support case it was brought to my attention that an admin user should always be able to read/view an approved activity report.
`regionId` normally exists on `this.activityReport.regionId`, but only when the scope is constructed with a `raw` `ActivityReport` model instance. If a `not raw` instance is given, then `regionId` is at `this.activityReport.dataValues.regionId`. the helpers that check for `this.activityReport.regionId` have been updated to support both possibilities and tests have been written to verify this behavior.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1817
> [TTAHUB-1817] Admins should be able to read approved reports

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/GoalCard.js
- src/services/goalServices/goals.test.js
- src/services/goals.js
- tests/api/activityReport.spec.ts
- tests/api/users.spec.ts
There are two bugs with the goal source.
- Goal source should be on the goals cards view of the RTR instead of topics. 
- When you've picked a grant and first visit the goals & objectives page, if you select an existing goal with a goal source, it should populate the already selected goal source. Goal source was missing from the "goalForGrants" api response.
Confirm the two issues above are fixed.
> [NO-TICKET] Fix bugs with goal source

- frontend/src/components/Navigator/ActivityReportNavigator.js
- frontend/src/pages/ActivityReport/__tests__/index.js
a useEffect was removed that needed to be there. We keep the activity report form data in two places: react state and the useForm context. At some point, we should refactor that - the react state is unnecessary - but for now, I've reverted the useEffect change I made previously
This issue was exposed because saving a goal wasn't sufficient to remove the "Add a TTA objective and save as draft to upload resources" message. To confirm that this is resolved, create a recipient report, add a new goal and objective, save goal, then edit the goal. The warning message should be gone and you should be able to upload a file
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1818
> [TTAHUB-1818] Update form data properly on save

- frontend/src/components/GoalForm/__tests__/constants.js
- frontend/src/components/GoalForm/constants.js
- frontend/src/components/Navigator/__tests__/ActivityReportNavigator.oe.js
- frontend/src/components/Navigator/__tests__/ActivityReportNavigator.recipient.js
An error in the way we validated URLs is fixed - a trailing spaces on an objective URL resource meant that it would be marked invalid and disappear on users. This fixes that by trimming the string before validating it and sending it to the backend, meaning that a trimmed string will be return and the user will never notice the disappearing string
On an AR, enter an otherwise valid URL with a space at the end and hit "save goal." On this branch, you will see the URL persist as you might expect. On main, the URL disappears.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1863
> [TTAHUB-1863] Fix url validation

- frontend/src/components/filter/activityReportFilters.js
- tests/e2e/activity-reports.spec.ts
This was a fix that @thewatermethod had applied for the start date. We just need it also for the end date.
On the regional dashboard add a filter for 'end date' 'is' 'ytd' paste it in slack and click the link. Notice the date filter is applied incorrectly.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1693
> [TTAHUB-1693] Apply fix for end date

- frontend/src/pages/TrainingReportForm/pages/completeEvent.js
- frontend/src/pages/TrainingReports/components/EventCard.scss
- src/policies/event.js
- src/routes/sessionReports/handlers.js
- src/seeders/20230718123611-tr-report.js
- src/services/event.test.js
- Putting the event status in a read-only field under certain circumstances meant the submit error message was hidden. This shows it.
- Breakpoints for the event card weren't quite reflecting the content, they have been updated
- There was a possibility for a newly created event to throw an error saving if there was no POC ID set
- getSessionById was missing a variable assignment that threw an error
- Created a seeder (forking this branch to work on an e2e test)
Confirm the errors listed above have been resolved.
> Training report cleanup for testing party

- frontend/src/hooks/useSocket.js
- frontend/src/pages/SessionForm/index.js
- frontend/src/pages/TrainingReportForm/index.js
This change applies only to the training report form and the session form. Because of the single column storage approach, multiple people working on the form at the same time is worse than on the activity report.
This change:
- Shortens the websocket interval to 10 seconds from 30
- Publishes the warning if any user is inside ANY page of the form, rather than just the same page
Websocket event still fires, behaves as above (you can test solo by removing the logic that excludes the active user from displaying in the SocketAlert component)
> Shorten websocket interval, display websockets on all pages of form

- src/services/recipient.js
- src/services/recipient.test.js
This is the second attempt at a fix for this. The bug involves how we were creating a list of topics. Right now, the UI expect topics from the activity reports (an array of strings) and the topics table (objects like ```{ id: 1, name: "A topic"}```. 
When we de-duplicate a goal, we also de-duplicate the objectives within that goal (each time a goal is added). We were iterating over the topics and standardizing them to a matching array of strings. However, with rolled-up goals, the second time we iterated over an objective's topics, we were iterating over an array of strings and essentially wiping it out.
This change fixes it. I also adjusted the test to ensure the fidelity of the topics returned to the UI.
With a recent data extract from prod loaded up, visit the following link: …
> [TTAHUB-1865] Fix bug with rolling up objective topics

- frontend/src/pages/AccountManagement/components/MyGroup.js
- src/routes/groups/handlers.test.js
- src/routes/groups/handlers.ts
I was able to reproduce the exact error message locally if the group being deleted no longer existed. The thinking is that Patrice  might have already deleted the group in another tab. Then when she attempted to delete it from the old tab it no longer existed and threw an error. The code has been updated to first verify the group exists before deleting it.
- Attempt to delete a group that no longer exists (via db delete). You should no longer get an error message.
- Deleting groups should work as it did before.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1927
> [TTAHUB-1927] Check if group exists before deleting

- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
We are not currently handling the IN case for endDate filter. I have updated the code to behave the same way as start date.
View the AR landing with no filters. Apply the last thirty days filter for end date. The number should change based on your filter.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1651
> [TTAHUB-1936] End date filter not filtering

- frontend/src/pages/SessionForm/__tests__/index.js
- frontend/src/pages/SessionForm/pages/__tests__/sessionSummary.js
- frontend/src/pages/SessionForm/pages/nextSteps.js
- frontend/src/pages/SessionForm/pages/participants.js
- frontend/src/pages/SessionForm/pages/sessionSummary.js
From the Jira "There is inconsistency on the "Save draft" buttons in the Session form. In the design, they had said "Save session", but it's better to be consistent and use "Save draft" on both forms."
Updated the session form to use "save draft" instead of "save session" for the appropriate button text.
Ensure that the session form still works as expected (save draft, etc)
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1923
> [TTAHUB-1923] update "save session" to "save draft"

- frontend/src/pages/TrainingReports/components/EventCards.js
- frontend/src/pages/TrainingReports/components/__tests__/EventCards.js
During a demo with Patrice, she asked if we could change the "empty" state messaging for the training reports landing. 
Confirm that all statuses say "There are no events."
> [No ticket] Update "empty" events messaging

- src/policies/event.js
- src/policies/event.test.js
- src/routes/files/handlers.js
- src/routes/files/handlers.test.js
It looks like I missed a permission rename when they were revamped a few weeks ago. Events now have an explicit "can upload files" permission used in the file uploader
Confirm that you can upload a file to a session
> Fix session file upload permissions

- frontend/src/pages/ActivityReport/Pages/components/GoalPicker.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/GoalPicker.js
- tests/e2e/activity-report.spec.ts
If you've entered an objective under one goal on an AR and go to change the goal, you'd previously lose that objective automatically. This PR adds a modal that prompts "are you sure you'd like to Lose Everything?" You may then choose whether or not you'd like to lose everything.
Consult Jira for details w/mockup. Confirm that you can change goals on an AR given three different cases.
1) You haven't entered any objectives. You change the goal without seeing the modal.
2) You've entered an objective. You want to keep it, so you change the goal and select "Keep objective." The objective should be kept.
3)  You've entered an objective. You want it out of here, so you change the goal and select "Remove objective." The objective should be gone.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1910
> [TTAHUB-1910] Warn about losing objective

- src/policies/event.js
- src/routes/events/handlers.js
- src/routes/events/handlers.test.js
- src/services/event.test.js
- src/services/event.ts
With this change, admins will be able to **view** all training reports, regardless of status. 
Note that they will still need to a regional permission (READ_REPORTS, READ_WRITE_REPORTS, READ_TRAINING_REPORTS, or READ_WRITE_TRAINING_REPORTS) to see the reports. This differs from the acceptance criteria but I didn't want to worry about the interaction with the filters, etc
Import fresh events, of which you are not the owner. Log in as an admin. You should see the not started events.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1981
> [TTAHUB-1981] Admins should be able to see all training reports

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/GoalCard.js
We expect to see the latest objective's end date displayed under the 'Last TTA' column.
View one of the goals from the JIRA or any goal with multiple objectives and make sure we correctly display the date.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1918
> [TTAHUB-1918] Fix for last tta date

- .circleci/config.yml
- src/lib/mailer/index.js
While the test messages worked, the actual messages were not being sent because nodemailer requires booleans for the `ignoreTLS `configuration. This PR ensures that it is set correctly.
Verify that email is sent and received on Dev
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1745
> Address AWS SES STARTTLS message

- frontend/src/pages/RecipientRecord/components/RecipientTabs.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
- tests/e2e/activity-report.spec.ts
- tests/e2e/recipient-record.spec.ts
Rename the "Goals & Objectives" tab on the Recipient Record to "RTTAPA"
Confirm that the change has been made
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1887
> [TTAHUB-1887] Rename RTTAPA tab

- src/services/activeUsers.js
Add 6 new columns to the "download users" button in Admin > Users
- READ_WRITE_TRAINING_REPORTS - Yes or blank
- READ_WRITE_TRAINING_REPORTS regions - List of regions with permission
- READ_TRAINING_REPORTS - Yes or blank
- READ_TRAINING_REPORTS regions - List of regions with permission
- POC_TRAINING_REPORTS - Yes or blank
- POC_TRAINING_REPORTS regions - List of regions with permission{}
Make sure you have users with those new permissions. Download the CSV of users from the Admin section and confirm that the information is correct.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1850
> [TTAHUB-1850] Add new permissions to users export

- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/formDataHelpers.js
- src/models/hooks/activityReportGoalFieldResponse.js
We saw this bug in standup yesterday. To duplicate in main: 1)On a new AR, add a recipient 2) pick the FEI goal, no need to fill out any fields 3) click activity summary in the left nav to go back and add a second recipient 4) save and continue, you'll get a 500 error.
This PR fixes it. **I understand that the goal does not stay open**. I'd like to fix this bug and log a ticket to fix that one, as it seems to be something in the backend goal service that I don't want to untangle and write a test for before having this fix out there. 
See description
No ticket for this
> Fix bug with removing recipients

- frontend/src/pages/TrainingReportForm/pages/__tests__/completeEvent.js
- frontend/src/pages/TrainingReportForm/pages/completeEvent.js
- frontend/src/pages/TrainingReports/components/EventCard.js
Training reports did not allow statuses to be changed if in the "not started" status. The ask is now to allow you to "suspend" them from the "not started" state.
Confirm that you can move a "not started" TR to "suspended"
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2064
> [TTAHUB-2064] Show not started and suspended as options for TR when TR is not started

- frontend/src/components/GoalForm/index.js
We renamed the RTR "Goals & objectives" page to "RTTAPA" but I missed renaming the link back to that page that displays at the top of the RTR goal form.
Ensure that the link at the top of the RTR goals form says "Back to RTTAPA" and not back "Back to Goals & Objectives"
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2066
> [TTAHUB-2066] Update stray hyperlink on the "create goals" form

- frontend/src/components/GoalForm/Form.js
- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/components/GoalForm/index.js
- frontend/src/pages/ActivityReport/Pages/Review/SomeGoalsHaveNoPromptResponse.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/__tests__/index.js
- frontend/src/pages/ActivityReport/__tests__/formDataHelpers.js
- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/formDataHelpers.js
- src/services/goalServices/getGoalsByActivityRecipient.test.js
- src/services/goals.js
- src/services/recipient.js
- src/services/recipient.test.js
- For a single recipient report, adding a root cause to the FEI goal can be done as before, uninterrupted on an AR.
- Multiple recipient reports now allow the editing of the FEI goal from the RTR as soon as it is added to a report and that report is saved. If you've added an FEI goal to an multi-recipient AR, and you attempt to submit that report before you've added root causes to all the goals, you'll see a message alongside the "incomplete pages" alert telling you to go to the RTR for these recipients
- Create a single recipient report for a user without the FEI goal.  You should be able to set a root cause without issue.
- For a multi-grant report: Attempt to do the same. Confirm that you can't set a root cause on a multi-grant report, that you can't submit until you've set those root …
> [TTAHUB-2053] Add ability to edit root cause on RTR for goals on draft reports

- frontend/src/components/filter/FilterProgramType.js
We want to temporarily remove the EHC-CCP from the program types filter.
This should no longer be an option on the Activity Report, Regional Dashboard, Regional Goal Dashboard, Resources Dashboard.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2031
> [TTAHUB-2031] Remove EHS-CCP from filters

- .circleci/config.yml
- config/config.js
- docker-compose.dss.yml
- docker-compose.test.yml
- docker-compose.yml
- src/app.js
- src/middleware/testingOnlyMiddleware.ts
See acf-head-start-eng slack channel for details, but essentially we now need to force postgres to use SSL. This change makes that happen.
CI & deploy passes. Change is deployed to sandbox, so site functionality can be tested there
> [No-ticket] Change to force SSL on environments with newer versions of Postgres

- src/migrations/20230920131223-fix-other-ece-fei-root-cause.js
The last script to update the FEI root cause for a handful of region 6 goals changed the name to an invalid value. This sets it to the correct value.
'**Other ECE Options**' should be '**Other ECE Care Options**'.
1. Run the migration
2. Verify that for the recipient '**Rolling Plains Management Corporation**' the FEI goal has the root cause: '**Other ECE Care Options**'.
3. Verify that for the recipient '**Washita Valley Community Action Council**' the FEI goal has the root cause: '**Workforce, Other ECE Care Options**'.
both should be region 6.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2119
> [TTAHUB-2119] Fix FEI root cause name

- src/services/goals.js
I'm unsure if it's due to recent changes or has always been an issue, but "Save Draft" on the goals & objectives page does not actually update the Activity Report but only the goals, objectives, and associated join tables and metadata tables. This leads to a quandary on the front end. 
When a report is loaded, the local storage data is compared to the "updatedAt" timestamp returned from the model. If the local storage timestamp is newer, then it overwrites fields from the database, and vice versa. 
However, given this case, the AR is never going to be newer if you save, add a goal and objective, save draft and then leave the AR entirely, since you never updated the report data after saving draft goals. This PR updates the "updatedAt" column on the AR every time the goals and objectives …
> [TTAHUB-2017] fix form data loading

- .circleci/config.yml
- src/lib/mailer/index.js
- src/lib/mailer/index.test.js
- src/tools/processData.js
- src/tools/processData.test.js
This PR allows to enable AWS SES in the non-production environments by eliminating bounces to fake email addresses. It flags the generated emails with a "no-send_" prefix and filters out these addresses. It also prevents sending to duplicate emails.
Verify on locally (while having the latest transformed db snapshot) or on Dev that notifications work as expected, e.g. by adding yourself as a collaborator.
Extra check: Verify there is no record of sending an email to a fake address by looking at the MailerLogs table.
e.g.
`SELECT * FROM "MailerLogs" order by "createdAt" desc LIMIT 10;`
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2100
- [n/a] Logical Data Model …
> Implement Amazon SES integration for non-production environments

- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/topic.js
We are currently doing partial matches on Topics for both the AR and ARO. I don't think we need this as the topics are selected from a set list and not a text field. This seems to speed up the overall filter, when testing locally for all topics both in and nin went from 9 sec to 3 sec. Although perf will vary from env to env.
Test the topics filter and make sure it still works as expected with a perf increase.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1632
> [TTAHUB-1632] Topics performance increase using IN

- frontend/src/pages/Admin/index.js
Added secondary headings and sub-grouped the admin buttons. Declined to remove the h1 as skipping straight to h2 produces non-semantic HTML, which we do not like.
Headings and buttons on the Admin panel appear as the ticket requests
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2122
> [TTAHUB-2122] distinguish between support and engineer admin functions

- frontend/src/pages/TrainingReports/components/EventCards.js
Fix the filter menu appearing behind the event cards on the TR landing page
Confirm the filters no longer overlap
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2159
> [TTAHUB-2159] Fix overlapping filters on the TR page

- frontend/src/components/RegionPermissionModal.js
- frontend/src/components/__tests__/RegionPermissionModal.js
Reorder regions in regional permission modal numerically instead of treating them as strings
Log in as or impersonate a user who is missing access to a region 10 or greater as well as one other (10 & 7 in my example above) 
Visit a link like:
/activity-reports?region.in[]=1&region.in[]=2&region.in[]=3&region.in[]=4&region.in[]=5&region.in[]=6&region.in[]=7&region.in[]=8&region.in[]=9&region.in[]=10&region.in[]=11&region.in[]=12
The regions in the modal should be ordered correctly
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1345
> [TTAHUB-1345] properly sort regions in regional permission modal

- frontend/src/widgets/HorizontalTableWidget.js
- frontend/src/widgets/ResourceUse.js
- frontend/src/widgets/__tests__/ResourceUse.js
- frontend/src/widgets/__tests__/ResourcesAssociatedWithTopics.js
The resource dashboard will display the title of an ECLKC resource if it's been fetched by the API. There was an error in the markup that was putting the title as both the text content of the link and as the `href`, which means dead links in the table.
Confirm with recent prod data on the Resource Dashboard -> Resource Use table that resources with human readable titles also have valid link destinations.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2145
> [TTAHUB-2145] Fix links in resource table

- docker-compose.yml
- src/lib/awsElasticSearch/index.js
- src/models/hooks/activityReport.js
This attempts to clean up the ES exception handling to allow for throwing of exceptions (handled by the queue). It also attempts to lesson the possibility of accessing a undefined value (in regard to status codes).
**Note:** This is pending the rate limiter PR (https://github.com/HHS/Head-Start-TTADP/pull/1750).
- Run the 'yarn createAwsElasticSearchIndexes'
- Create submit a report verify the operation was indexed
- Delete a report make sure the index was removed
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2146
> [TTAHUB-2146] Clean up ES error handling

- frontend/src/pages/ViewTrainingReport/__tests__/index.js
- frontend/src/pages/ViewTrainingReport/index.js
- src/policies/event.js
- src/routes/events/handlers.js
"View training reports" had a bug - if you have permissions to view the training reports **or**  activity reports in a given region, you should be able to see the read only view of a TR. The landing page was displaying the correct reports, but clicking on the report to view it generated an error.
Confirm that a user who can read activity reports in a given region, has the TR feature flag, but does not have the READ_TRAINING_REPORTS permission in that same region can view a TR in that region. 
For example:
User X has
- READ_REPORTS in region 3
- training_reports feature flag
But does not have READ_TRAINING_REPORTS in region 3
They should be see a Region 3 TR report on their landing page AND have the permissions to view it
> Make sure permissions match across TRs

- frontend/src/pages/SessionForm/__tests__/index.js
- frontend/src/pages/SessionForm/index.js
- frontend/src/pages/TrainingReports/components/SessionCard.js
- frontend/src/pages/TrainingReports/components/__tests__/SessionCard.js
- tests/e2e/training-report.spec.ts
**When the session is complete** 
- Hide the "edit" and "delete" buttons from the interface
- Prevent access to the session form
These changes should prevent editing or deleting sessions once it has been completed. I am not locking the backend down at this time at Garrett's (sensible) request, as he is in the middle of rewriting things.
- Confirm the above is true
- Confirm regular session operations are good to go
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2164
> [TTAHUB-2164] Updates to session form when session is completed

- frontend/src/components/GoalCards/GoalDataController.js
- frontend/src/components/filter/__tests__/goalFilters.js
- frontend/src/components/filter/goalFilters.js
- frontend/src/pages/RecipientRecord/index.js
- frontend/src/pages/RecipientRecord/pages/GoalsObjectives.js
- frontend/src/pages/RecipientRecord/pages/__tests__/PrintGoals.js
- frontend/src/pages/RecipientRecord/pages/constants.js
Fixes a bug where a filtering a recipient's data by a grant number that either doesn't exist for them or hasn't been loaded yet returns a white screen of death.
Also fixed the key used by session storage - since it wasn't recipient specific, a grant for one recipient could be loaded for another, which I believe is how the bug happens.
On your local machine, visit a URL like this, with nonsense in the grantNumber.in filter:
http://localhost:3000/recipient-tta-records/564/region/3/goals-objectives?grantNumber.in[]=ASDF
It should not white screen. Select a grant for that recipient that does exist, and, as long as that works, visit another recipient's RTTAPA page that you haven't visited in the session yet. Confirm that no out-of-scope grant number filters are loaded
* …
> [TTAHUB-2086] Fix bug with grant number filter on RTR

- src/migrations/20231017230000-merge-pseudo-fei-goals.js
Merges some goals created by users who wanted FEI goals and kinda sorta made their own copies, but without the proper template and the root cause questions
results:
```
op_order |          operation           | cnt
----------+------------------------------+-----
1 | corrected_goals              |   9
2 | updated_target_objectives    |   4
3 | relinked_objective_topics    |   0
4 | relinked_objective_resources |   0
5 | relinked_objective_files     |   0
6 | deleted_objective_topics     |   7
7 | deleted_objective_resources  |   2
8 | deleted_objective_files      |   0
9 | relinked_objectives          | 105
10 | updated_target_goals         |   9
11 | relinked_args                |  65
12 | deleted_args                 |  13
13 | deleted_goals                |  45
```
Run the migration
* …
> Merge pseudo-fei goals into real fei goals and template

- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/index.js
Start and end dates were being doubled parsed in some circumstances.
On main, steps are basically:
- New report. No need to touch anything other than start or end date.
- Enter 10/04/2023 for start date (or use calendar)
- Enter 10/20/2023 for end date (or use calendar)
- Save and continue
- Without touching anything else, use the side navigation (activity summary in progress) to go back to the activity summary
- You'll see some weird stuff.
But not on this branch
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2217
> [TTAHUB-2217] Fix bug with parsing dates on an unchanged report

- frontend/src/pages/ResourcesDashboard/__tests__/index.js
- frontend/src/pages/ResourcesDashboard/index.js
- src/services/dashboards/resource.js
- src/services/dashboards/resource.test.js
Two changes here:
- Add back topics resource table.
- Remove unwanted tables and filter reports to speed up performance.
Testing locally saw a increase of 50% from 18 seconds to 9 seconds. Although this still isn't ideal we will move forward with this increase for now. Keep in mind this test was with no date filter and all regions.
- Review all code.
- Make sure the resource topics table now shows.
- Run the change before and after note the time diff (comment out the cache.ts)
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1952
> [TTAHUB-1952] Performance enhancement and add back table

- frontend/src/components/Navigator/ActivityReportNavigator.js
- frontend/src/pages/ActivityReport/Pages/__tests__/goalsObjectives.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/goalValidator.js
- frontend/src/pages/ActivityReport/Pages/components/goalValidator.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
Trigger FEI goal validation before saving a goal, even if the blur event has not fired
Attempt to save an FEI goal with three root causes. You should not be able to.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2253
> [TTAHUB-2253] Make sure to re-trigger prompt validation

- config/config.js
By default, sql queries are logged to the terminal. when the query contains a new line the log aggregator treats newlines as separate logs. This change makes queries a single line
click around on the site and see that all queries in the log are a single line
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2255
> [TTAHUB-2255] Multi-line SQL queries mess up logging aggregator Kibana and NewRelic

- src/lib/apiErrorHandler.js
Log the callstack in Kibana so we see what line the error occured on.
**NOTE:** I tried the solution in this thread without any luck.
https://stackoverflow.com/questions/51630896/winston-not-displaying-error-details
Throw an exception on the BE handler and check the server log to see the error message and callstack.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2265
> [TTAHUB-2265] Log the callstack in Kibana

- src/services/event.test.js
- src/services/event.ts
- src/services/sessionReports.test.js
- src/services/sessionReports.ts
This changes the session sort in 3 locations.
1. TR landing (startDate, sessionName, createdAt)
2. Edit TR > Complete Event > Session List (startDate)
3. TR Landing > View Report (startDate, sessionName, createdAt)
See sort specified on TTAHUB-2150.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2150
> [TTAHUB-2150] Sorting sessions

- .circleci/config.yml
- .env.example
- deployment_config/dev_vars.yml
- deployment_config/prod_vars.yml
- deployment_config/sandbox_vars.yml
- deployment_config/staging_vars.yml
- manifest.yml
- src/lib/apiErrorHandler.js
- src/lib/apiErrorHandler.test.js
- src/routes/activityReports/handlers.js
- src/routes/externalApi/activityReports/handlers.js
- src/routes/files/handlers.js
- src/routes/widgets/handlers.js
Now all unknown errors will log to the Request Errors table unless the env SUPPRESS_ERROR_LOGGING is set to true
This should result in missing/lost ttaProvided or similar to be recoverable more often
Trigger an error, look in the RequestErrors DB or the admin UI for the logged data
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2268
> [TTAHUB-2268] log all unknown errors

- src/services/goalServices/getGoalsByActivityRecipient.test.js
- src/services/goalServices/saveGoalForReport.test.js
- src/services/goals.js
- tests/e2e/activity-report.spec.ts
This change checks that we have a goal name before we trim it.
**Steps to reproduce, e.g. on Staging:**
**NOTE:** Use the network tab to see the error before the code change.
1. create a new report
2. select a recipient
3. click "Save and Continue"
4. navigate back to the Activity Report Summary by clicking the navigator link
5. click "Save draft"
6. note the error appears
7. Also check completing, submitting, and approving the report
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2155
> [TTAHUB-2155] Check goal name before we attempt to trim()

- src/models/hooks/goalFieldResponse.js
- src/models/hooks/goalFieldResponse.test.js
We found an awesome bug that updates all values in 'ActivityReportGoalFieldResponse'. This occurs when a FEI Root cause is changed on a goal that is not on an approved report. This updates all values in the 'ActivityReportGoalFieldResponse' (for every goal).
Apparently sequelize doesn't support joins on updates so it updates everything 🤷‍♂️ (it also doesn't complain)
- Review code.
- Update an FEI Goal's root cause that is linked to a non-approved report. Check the database and make sure the GoalFieldResponse and ActivityReportGoalFieldResponse are ONLY changed for your goal and ar.
Steps to Reproduce:
1. Edit any FEI goal that is not on a approved report
2. Change the FEI root causes and save
3. Verify the GoalFieldResponse  and ActivityReportGoalFieldResponse  are in sync and no other …
> [TTAHUB-2288] Fix ActivityReportGoalFieldResponse update bug

- src/lib/mailer/index.js
- src/lib/mailer/index.test.js
Check for "no-send" prefix before sending a TR notification
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2296
> Honor no send with TR notifications

- src/migrations/20231027150000-remove-test-fei-goals.js
Marks some test FEI Goals and associated Objectives to be 'deletedAt' the time of migration so they drop out of visibility
The goals and objectives should disappear. E.g. on grant 06CH012163, there should no longer be an FEI goal visible. There should also be no Objectives left visible with the title `hghgh`
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2120
> [TTAHUB-2120] Mark test FEI goals deleted

- src/goalServices/getGoalIdsBySimiliarity.test.js
- src/goalServices/goals.js
- Only allow goals that don't appear on the same activity report to be eligible for merge
- Only allow goals that would have less than 3 goal field responses to be merged
- Don't double create goal resource links
Check that the code accomplishes these three things
> update strictness of goal merge eligibility

- .circleci/config.yml
- src/goalServices/goals.js
- src/goalServices/mergeGoals.test.js
- src/routes/goals/handlers.js
For merge goals, we want to preserve the value in "originalGoalId" and "originalObjectiveId" in the case where a merged ActivityReportGoal or ActivityReportObjective is merged again.
This preserves the lineage more directly.
Merge a merged goal and verify in the database that the ARG and ARO have their original values for the columns above. You probably want to record the value before merging for ease of verification.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2337
> Handle nth level merging

- frontend/src/fetchers/__tests__/goals.js
- frontend/src/fetchers/goals.js
- frontend/src/pages/RecipientRecord/pages/MergeGoals/__tests__/index.js
- frontend/src/pages/RecipientRecord/pages/MergeGoals/index.js
- similarity_api/src/settings.py
- src/routes/admin/helpers.js
- src/routes/admin/trainingReport.js
- src/routes/admin/trainingReport.test.js
- src/routes/goals/handlers.js
- src/routes/goals/handlers.test.js
- src/routes/goals/index.js
- src/routes/recipient/handlers.js
Use the same permissions for the merge goals handler as we use for showing the alert with the merge goal candidates on the RTR. As below:
```js
// can view in region and is a TTAC
if (this.canView() && this.user.roles.map((r) => r.name).includes('TTAC')) {
return true;
}
// or on recipient reports
if (this.isOnRecipientsReports) {
return true;
}
return false;
```
(or is an admin)
If you can see an alert, you can merge goals.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2336
> [TTAHUB-2336] Unify merge goals permissions

- frontend/src/components/SocketAlert.js
- frontend/src/components/__tests__/SocketAlert.js
- frontend/src/pages/RecipientRecord/pages/MergeGoals/index.js
Add a websocket alert to the goal merge page
For testing it may be helpful to comment out the code that excludes the current user from the list.
In ```frontend/src/components/SocketAlert.js``` I change line 26 from:
``` users.map((user) => (user.name)).filter((user) => user !== currentUser),```
to 
```  users.map((user) => (user.name)) ```
Visit the goal merge and your location should be published 2500 ms after you arrive. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2236
> [TTAHUB-2236] Add websocket to goal merge

- src/services/activityReports.js
Switch getDownloadableActivityReports to use a left join for Goals because Other entities have objectives but not Goals. Currently it's an inner join that makes the title blank, which in turn throws an error at https://github.com/HHS/Head-Start-TTADP/blob/main/src/lib/transform.js#L223 if the CSV export contains an AR with Other entities in it.
Export a CSV containing an AR with an Other entity in it to see if it generates and error.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2352
> switch goals to left join

- src/lib/migration.js
- src/lib/migration.test.js
enum can not be created and add values to on the same transaction, it must be created with the values.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2370
> [TTAHUB-2370] dropAndRecreateEnum

- frontend/src/components/ApprovedReportSpecialButtons.js
- frontend/src/components/BackLink.js
- frontend/src/pages/ApprovedActivityReport/index.js
- frontend/src/pages/ViewTrainingReport/__tests__/index.js
- frontend/src/pages/ViewTrainingReport/index.css
- frontend/src/pages/ViewTrainingReport/index.js
Add the "Copy URL Link" and "Print to PDF" buttons to the TR.
I added only rudimentary print stylings here since there was no mock-up provided or special view requested.
Confirm the buttons appear on the "completed" TR view and that they function as expected. 
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2143
> [TTAHUB-2143] Add copy URL and print to PDF buttons to TR

- frontend/src/components/ControlledDatePicker.js
- frontend/src/hooks/useCompleteSectionOnVisit.js
- frontend/src/pages/ActivityReport/Pages/components/NextStepsRepeater.js
- frontend/src/pages/RecipientRecord/pages/CommunicationLogForm/__tests__/index.js
- frontend/src/pages/RecipientRecord/pages/CommunicationLogForm/constants.js
- frontend/src/pages/RecipientRecord/pages/CommunicationLogForm/pages/log.js
- frontend/src/pages/RecipientRecord/pages/CommunicationLogForm/pages/nextSteps.js
- frontend/src/pages/RecipientRecord/pages/CommunicationLogForm/pages/supportingAttachments.js
- frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/components/DisplayNextSteps.js
- frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/components/__tests__/DisplayNextSteps.js
- frontend/src/pages/RecipientRecord/pages/ViewCommunicationLog/index.js
- frontend/src/widgets/RttapaUpdates.js
- Result and next steps should not be required. (This means the next steps component, also used in other forms, should accept a "required" parameter)
- The RTTAPA updates table should link to the log entry in the same way the communication log does
Confirm the above are resolved. Note I left the validation "onBlur" for the dates just in case someone tries to type "cactus" or "never" in there, but the form can be saved with any value.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2379
> [TTAHUB-2379] Update required fields on communication log

- src/routes/activityReports/handlers.js
- src/services/groups.test.js
- src/services/groups.ts
We need to limit what groups are returned to the AR (public vs private) not just region.
**NOTE:** This code will be replaced by Garrett's re-write and is a place holder for now.
Make sure when you are creating a recipient AR and use the 'use group' check box. You can ONLY see groups that are public or created by the user and private.
> Limit AR Groups

- frontend/src/pages/ActivityReport/Pages/activitySummary.js
- frontend/src/pages/ActivityReport/Pages/activitySummary.scss
Kelly pointed out we want 8px above the use group check box not 16px.
Visually inspect the activity summary page make sure we only have 8px above the checkbox.
> Use Group UX Change

- src/models/hooks/goalFieldResponse.js
- src/models/hooks/goalFieldResponse.test.js
A bug was found during the demo of TTAHUB-23767. When updating FEI root cause on an activity report, we would properly 
propagate the root cause to all other reports and goals. However because the AR '**updatedAt**' was NOT changed. The local storage thought it had a more recent copy of the report and overwrote it.
**AR Test:**
1. Create two AR's using the same FEI goal.
2. Update the FEI on one of the AR's and save.
3. Verify both AR's have the set FEI.
4. Verify the Goal in RTR has the set FEI from the AR.
5. Check both AR's in the db to make sure they have the same **updatedAt** date.
**RTR Test:**
1. Create two AR's using the same FEI goal.
2. Update the FEI from the RTR.
3. Verify both AR's have the RTR set FEI.
4. Verify the RTR FEI value stuck on the goal.
5. …
> [TTAHUB-2367] Fix FEI Root Cause local storage bug

- src/widgets/helpers.js
- src/widgets/helpers.test.js
- src/widgets/topicFrequencyGraph.js
- src/widgets/topicFrequencyGraph.test.js
- src/widgets/totalHrsAndRecipientGraph.js
- src/widgets/totalHrsAndRecipientGraph.test.js
Not a lot of information to go off of with this one, so just coalescing wherever I see a `forEach` in the scope of `SERVICE:WIDGETS`.
Unclear! Use any and all widgets and ensure the error doesn't appear in the server logs:
`SERVICE:WIDGETS - UNEXPECTED ERROR - TypeError: Cannot read properties of null (reading 'forEach')`
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2172
> [TTAHUB-2172] SERVICE:WIDGETS -TypeError: (reading 'forEach')

- frontend/src/pages/ActivityReport/Pages/Review/Submitter/NeedsAction.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/index.js
- frontend/src/pages/ActivityReport/index.js
Allow adding approvers when report is needs action
Use user impersonation to create a report, then set the report as needs action as the approver.
As the creator, confirm you can add an additional user.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1677
> [TTAHUB-1677] Allow adding approvers when report is "needs action"

- src/goalServices/goals.js
It looks like there is code in the "saveGoalsForReport" which silently failed to update the anticipated close date on a reused goal (if that goal was already on an approved AR)
Since the UI allows it, we should allow it to change (closed and suspended goals don't appear on the AR)
Test that you can update the anticipated close date **on an AR** for a reused goal that's been on an approved report.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2275
> [TTAHUB-2275] Allow changing of end date

- frontend/src/fetchers/__tests__/event.js
- frontend/src/fetchers/event.js
- frontend/src/pages/ViewTrainingReport/__tests__/index.js
- frontend/src/pages/ViewTrainingReport/index.js
- src/routes/events/handlers.js
- src/routes/events/handlers.test.js
Allow query param to be passed into the route fetching events, making it more chill.
Reference associated Jira for test case. After the change, specialist in question should be able to view pertinent training report.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2316
> [TTAHUB-2316] POC should be able to view training report

- src/workers/files.js
- src/workers/files.test.js
This one is more straight forward. It seems like we access dataValues in only one spot in this pipeline. We should check the return of `findOne` before accessing `dataValues`. If it is `null`, throw an error to short circuit the `processFile` operation.
`files.test.js` has been updated to check for this
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2170
> [TTAHUB-2170] Update Files: cannot read properties of null (dataValues)

- frontend/src/pages/ApprovedActivityReport/components/ApprovedReportV2.js
- src/models/hooks/goalFieldResponse.js
- src/models/hooks/goalFieldResponse.test.js
- src/services/goalTemplates.ts
Currently we do NOT update FEI responses if its linked to an approved AR. 
This code change does two things:
1. **GoalFieldResponses** are ALWAYS updated regardless of onApproved report status.
2. **ActivityReportGoalFieldResponses** are ONLY updated if they are not linked to an approved report (cached as of the time of approval) all others are updated.
**Test:** 
1. Create a approved report using an FEI goal
2. Create an unapproved report using an FEI goal (using a different response than step 1)
3. Check the approved report is should still have its unique response
4. Edit the FEI goal make sure its set to the response of the unapproved goal
5. Update the response from the fei goal to something new
6. verify it was changed on the unapproved and goal
7. verify it was …
> [TTAHUB-2367] Change logic for updating fei responses on approved reports

- src/migrations/20240104110924-remove-unwanted-aro-topics.js
When exporting an older report (id: 10558), we noticed that both the ARO and AR (legacy) level topics were populated. This should not be the case as this report was created and approved before the introduction of ARO's. After some investigation it turns out that the creation of these topics was from a migration file '20220802000000-goal-objective-metadata-caching'. The attached script will delete any ARO topics that were created as a result of this migration on version 1 reports.
- Review the migration.
- Make sure you agree with the cleanup (criteria used to determine what we delete).
- Export report 10558 and see the 'Objective 1.1 Topics' field populated in addition to the 'Legacy Topics covered'.
- Run the migration and export the report csv only the legacy topics should be populated. …
> [TTAHUB-2124] Remove aro topics from version 1 reports

- .github/pull_request_template.md
```md
```
For discussion: every once in a great while, the CD part of our CI/CD is blocked because something is merged into main before it's ready to be deployed.
This is one _possible_ solution: ensure all ducks are aligned before clicking the button, despite how nice it feels.
Pros: Staging is truly staging, and main and production never drift. Pipeline is never blocked by minor change requests or simple bugs.
Cons: Sometimes we catch bugs in staging because code sits there.
> Pull request template changes for discussion

- frontend/src/pages/ApprovedActivityReport/helpers.js
- frontend/src/pages/ApprovedActivityReport/index.js
We found a bug where the formatSimpleArray() function on approved reports wasn't checking for null value.
This fixes the issue by adding a check.
View any approved v2 report that doesn't have language set.
> Fix language issue on approved reports on prod

- frontend/src/pages/ActivityReport/Pages/activitySummary.js
Another bug found for reports in draft failing the isPageComplete check.
This fixes the isPageComplete by first checking if language is set.
> Check for null language on isPageComplete

- src/models/programPersonnel.js
- src/models/tests/programPersonnel.test.js
Display the program type if leadership is CFO on the recipient profile/leadership widget
- Load a prod dataset and visit /recipient-tta-records/4707/region/5/profile
- You will see that the CFO now says "CFO for early head start" or "CFO for head start" depending on the associated program
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2300
> [TTAHUB-2300] Display which program a CFO belongs to on the leadership widget

- src/goalServices/goals.js
This issue had to do with a required file.url param missing from the returned report. We simply put it back the way it was before.
Edit any existing report with objective file attachments there should be no error.
Or edit the report from the JIRA.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2483
> [TTAHUB-2483] Add back url to files

- src/goalServices/goals.js
Another error introduced by my recent refactor; resource links reduced for an objective don't have a "id" but instead use a value
Add two resource links to an activity report objective, leave, and then return. Both resource links should be present.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2494
> [TTAHUB-2494] Fix resource links reducer error

- src/models/hooks/activityReportApprover.js
- src/policies/activityReport.js
- src/services/activityReportApprovers.js
We (I) removed the upserts from the approval process (big mistake?)
In doing so, there was one straight up mistake and one thing that we missed.
1/25/24 prod dataset is on keybase. Impersonate the user listed in the Jira ticket and submit report 39409.
Clear local storage; refresh the page
You will see that the report is **actually submitted**
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2494
> [TTAHUB-2494] Fix for activity report approvers

- frontend/src/pages/SessionForm/__tests__/index.js
- frontend/src/pages/SessionForm/pages/__tests__/completeSession.js
- frontend/src/pages/SessionForm/pages/completeSession.js
- src/goalServices/goals.js
When testing #1947, I found two bugs that I think should be fixed.
1) Draft TR goals were available for selection on the AR. I adjusted the goalsForGrants query to meet the original criteria.
2) I thought of a problematic scenario where a session was completed before the goal was, locking the UI. A support ticket waiting to happen. I added an error state to our session completion so that such a thing would be disallowed.
- Confirm that draft TR goals can't be selected on an AR, only "In Progress" goals
- Attempt to complete a session when the "goal" isn't filled out on the parent training report. You should be unable to.
There's no ticket for this
> Fix 2 bugs with TR goal

- src/models/hooks/sessionReportPilot.js
- src/models/hooks/sessionReportPilot.test.js
This was supposed to be in the last PR, but I forgot to push it. It's a pretty small change and the logic should be simple enough to verify by just looking at it, but please go ahead and test using the steps below if you'd like.
The change:
Don't delete the goal if it is currently in use by another session. In other words, only delete the goal if the session removing this recipient is the ONLY session using this recipient/goal pair.
Useful query:
```sql
SELECT e.id AS "ERPG id",
erp.data->>'goal' as "EventReportPilot.data->>'goal'",
g.id AS "Goal.id",
g.name AS "Goal.name",
g."grantId" AS "Goal.grantId",
g.status AS "Goal.status",
g."previousStatus" AS "Goal.previousStatus",
s.data->>'status' AS "SessionReportPilot.data->>'status'"
FROM "EventReportPilotGoals" as e
LEFT JOIN …
```
> [TTAHUB-2546] Small changes to TR goal deletion - missed from previous PR

- src/lib/apiErrorHandler.js
Not seeing the connection pool logged given errors similar to those we were attempting to debug. It looks like we may be checking against the wrong error type.
> Add additional case for logging connection pool

- src/migrations/20240129221712-change-training-event-goal-source.js
The migration modified by this PR has not run successfully on prod. The issue is because we already have goals and arg's using the source we are changing. This PR updates the way we handle this to first add the new ENUM switch it over and remove the old value.
**NOTE:** Verified that this migration has NOT run yet by querying SequelizeMeta table on latest prod db.
SELECT * FROM "SequelizeMeta" where "name" = '20240129221712-change-training-event-goal-source.js'
- We should have the same number of Goals and Activity Report goals set with a  source value before and after.
- On a prod database run the migration make sure any goal source in the Goals or ActivityReportGoals that was using 'Training event follow-up' is now using 'Training event'. 
> Fix bug when updating existing goal sources

- src/goalServices/goals.alt.test.js
- src/goalServices/goals.js
Helping with a support request, I learned the message displayed on the admin when bulk creating a goal is unhelpful. It displays the _grant id_ but what is needed is the **grant number**.
Using prod or transformed data, attempt to create a multi-recipient goal via the admin. If you pick any substantial group and then pick the FEI goal, it is likely you will see an error message. This message will say "Goal name already exists for grants" and then list the numbers not the ID
No ticket
> Update create goals error message

- frontend/src/pages/Admin/Goals/Create.js
- frontend/src/pages/Admin/Goals/__tests__/Create.js
- src/goalServices/goals.alt.test.js
- src/goalServices/goals.js
- Add a checkbox to the form to allow bypassing existing goals
- Alter the backend handler to optionally skip creating existing goals
- Create a group
- Using the create goals form, create an FEI goal
- Add an additional grant to the group
- Attempt to do the same thing again (create an FEI goal for that group)
- You should see an error
- Check the "Skip creating goals for recipients who already have them" box
- Resubmit. It should work without an error and create another FEI goal only for the missing grants.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2567
> [TTAHUB-2567] Allow admin users to skip existing goals when creating multi-recipient goals from the admin

- frontend/src/__tests__/permissions.js
- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/GoalCard.js
- frontend/src/components/GoalCards/constants.js
- frontend/src/permissions.js
- src/goalServices/getGoalsByActivityRecipient.test.js
- src/services/recipient.js
Add a delete button to the goal cards in the RTR under certain circumstances
- User is an admin or has approve reports
- Goal is "Draft" or "Not Started"
- Goal is not on a report
- Find a goal that meets the above criteria, and delete it
- Confirm that a goal on a report or a goal in a more "advanced" status can't be deleted
- Confirm that a user without those permissions does not see the delete button either
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2157
> [TTAHUB-2157] Allow admins & approvers to delete certain goals

- frontend/src/components/GoalForm/ObjectiveForm.js
- frontend/src/components/GoalForm/index.js
- src/goalServices/createOrUpdateGoals.test.js
- src/goalServices/goals.js
Two additional bugs found while reviewing code in main
- Objective support type was not able to be set on existing objectives
- Creating a new goal created double goals (one draft, one not started)
Both of these cases are strictly on the RTR goal form:
- Confirm that support type can be set on existing objectives where none existed
- Create a new goal and confirm that "submitting" that new goal makes just one goal (a not started)
> [TTAHUB-1942] Fix bugs found during review of goal nudge

- frontend/src/components/GoalForm/__tests__/index.js
- frontend/src/components/GoalForm/index.js
Stop duplicate goal creation (one draft, one not started)
Create a goal on the RTR form, moving through the whole process including submission.
At the end of the process you should not have created any duplicate goals
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-1942
> [TTAHUB-1942] Close off another avenue for duplicating a goal

- .circleci/config.yml
Ignore the name of this branch.
This PR just changes the tag for `setup_remote_docker` to `default` because the current one was removed.
This has no effect on deployments to cloud.gov AFAIK.
CI passes.
> Use default docker image

- src/policies/event.js
- src/policies/event.test.js
Training reports should only be able to be deleted if the report is either "Not Started" or "Suspended".
Pen test revealed a vulnerability where requests could be intercepted, the event ID changed, and an event in another status deleted.
This PR adds code to check the event status in the canDelete provision in the policy.
You can use a tool like Burpsuite or Postman (I used postman) to observe the vulnerability. Don't ask me to explain how to use Burpsuite, I have no idea. Otherwise, confirm that the tests pass and that reports/status will be checked to have the correct result.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2578
> [TTAHUB-2578] Check status in event policy before deleting

- src/lib/importSystem/record.ts
- src/lib/importSystem/tests/record.test.js
- src/migrations/20240306000000-monitoring-nonbulkcreate.js
There is an issue in sequelize bulkCreate where it does not update the sequence used for the primary key. This prevents additional inserts into the table as any insert will have a key conflict.
Run monitoring, add a file to the sftp, run monitoring again. The new file should be handle correctly.
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2661
> [TTAHUB-2661] Monitoring issue found when using bulkCreate

- src/lib/importSystem/record.ts
- src/lib/importSystem/tests/record.test.js
The filter by status was not valid, as we need to not attempt to redownload if the file has already been downloaded and processed.
Fully process a file, then try to download more files. should not attempt to download again.
* https://jira.acf.gov/browse/TTAHUB-2679
> [TTAHUB-2679] Monitoring data, attempting to redownload after already processing

- frontend/src/pages/ActivityReport/Pages/Review/Approver/Review.js
- frontend/src/pages/ActivityReport/Pages/Review/Approver/__tests__/Review.js
- frontend/src/pages/ActivityReport/Pages/Review/Approver/index.js
- frontend/src/pages/ActivityReport/Pages/Review/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/index.js
- frontend/src/pages/ActivityReport/Pages/components/ApproverStatusList.js
- tests/e2e/activity-report.spec.ts
Reset to draft was not available for creator-approvers (users who were creators and approvers on the same report)
This change allows creator-approvers to reset a report to draft
Create a report. Set yourself as an approver. Submit it. You should be reset to draft, as well as be able to resubmit.
* https://jira.acf.gov/browse/TTAHUB-2677
> [TTAHUB-2677] Allow creator-approvers to reset to draft

- src/routes/groups/handlers.ts
- src/services/groups.ts
Group query had a small bug: when creating a new group, grants that were already in a group would be excluded
Using prod data, impersonate the user named here -> https://jira.acf.gov/browse/TTAHUB-2678
As that user, create a new group and confirm the grants named in the ticket appear as options
* https://jira.acf.gov/browse/TTAHUB-2678
> [TTAHUB-2678] Fix error in group query

- src/models/hooks/eventReportPilot.js
- src/models/hooks/sessionReportPilot.js
- src/models/hooks/sessionReportPilot.test.js
Augment the hook in SessionReportPilot that is responsible for creating a Goal for each session recipient. The hook now also updates the GoalCollaborators table.
- Create an event with goal text.
- Create a session with any number of recipients.
- Check the GoalCollaborators table and ensure there are two rows per goalId. One for Creator (POC) and one for Linked (logged in user).
- Change the POC to a different value. It should update the GoalCollaborators entries with the new value.
- Change the POC to an empty value. It should update the GoalCollaborators entries by setting userId to your logged in userId where collaboratorTypeId = 1 (creator).
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-2220
> [TTAHUB-2220] TR goal: POC credited for "entered by", current user credited for "linker"

- frontend/src/pages/AccountManagement/MyGroups.js
- frontend/src/pages/AccountManagement/__tests__/MyGroups.js
If a co-owner edits a group they can't change the 'is private' checkbox this can only be updated by the creator.
1. Create a group and add a co-owner
2. Edit the group as the co-owner 
3. Verify they cannot see the is private checkbox
4. Edit the group as the creator
5. Verify they can see and change the is private checkbox.
* https://jira.acf.gov/browse/TTAHUB-2659
> [TTAHUB-2659] Co-owners can't change public/private setting

- frontend/src/components/GroupAlert.js
- frontend/src/components/RecipientsWithGroups.js
- frontend/src/fetchers/__tests__/session.js
- frontend/src/fetchers/session.js
- frontend/src/pages/ActivityReport/Pages/activitySummary.js
- frontend/src/pages/ActivityReport/index.js
- frontend/src/pages/SessionForm/pages/__tests__/participants.js
- frontend/src/pages/SessionForm/pages/participants.js
- src/routes/sessionReports/handlers.js
- src/routes/sessionReports/handlers.test.js
- src/routes/sessionReports/index.js
This change add the ability to select groups on the **TR > session > participants** page. This follows the same logic as the AR group selection. This serves to simply auto populate the recipients. If the group recipents are altered a information message is shown asking if they want to start over.
- Review all code
- Create a group for a select region add some recipients.
- Find and Event for the same region and select the group
Verify: All recipients populate and you can save the report
- Do the same thing as the above two steps but modify (add/remove) recipients.
Verify: You should get an information message saying group recipients have been modified and you can reset.
- You should still be able to edit an existing TR session participants without issue.
* …
> [TTAHUB-2572] Add groups to TR participants

- src/migrations/20240313000002-delete_comlog_entry.js
A customer created a couple 'test' communication logs to demo the feature and wants them removed. There's no `CommunicationLogs.deletedAt` so it's a hard delete, and there's currently a lot of different ways to connect files to things so it's a little more complicated than it would otherwise be.
Neither https://ttahub.ohs.acf.hhs.gov/recipient-tta-records/1839/region/10/communication/888/view
nor https://ttahub.ohs.acf.hhs.gov/recipient-tta-records/1839/region/10/communication/788/view should turn up anything, and the comlog page for that recipient should be clear of the test comlogs. You can also reference the `before_count` and `after_count` temp tables to see the removals.
* https://jira.acf.gov/browse/TTAHUB-2703
> [TTAHUB-2703] delete test communication log

- frontend/src/pages/ActivityReport/Pages/Review/Approver/Review.js
- frontend/src/pages/ActivityReport/Pages/Review/Approver/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/Approver/index.js
- frontend/src/pages/ActivityReport/Pages/Review/index.js
Per user request - if a user is an approver and the creator, and the report is in "needs action", allow that user to reset the report to draft.
- Load prod data
- Impersonate user 160
- open report 40979
- reset report to draft
- remove yourself (user160) as an approver
- Add a different approver and resubmit
Or, with your own database and environment, set yourself as an approver and creators on a report and then reset that report to draft. Remove yourself as an approver, choose a different approver, and resubmit. 
Confirm that the functionality doesn't exist for approvers who aren't creators, or creators who aren't approvers (on a given report)
* https://jira.acf.gov/browse/TTAHUB-2725
> [TTAHUB-2725] Fix behavior when approver is creator and report is in draft

- src/scopes/activityReport/goalName.ts
- src/scopes/activityReport/index.js
- src/scopes/activityReport/index.test.js
- src/scopes/activityReport/reportText.js
- src/scopes/activityReport/utils.js
This change just puts the backend code in place for the goal name filter. There will be several of these PRs incoming; they are all prerequisite for the frontend ticket, which will come last.
Evaluate the code. You can attach "logging: console.log" to the options passed to the ActivityReport.findAlls added to the test to see the SQL generated if that helps evaluate the correctness. Ensure the test adequately covers the use case.
* https://jira.acf.gov/browse/TTAHUB-2647
> [TTAHUB-2647] Add filter to the activity report scopes for goal name

- src/goalServices/getGoalIdsBySimiliarity.test.js
- src/goalServices/goals.js
- src/routes/goals/handlers.js
- src/routes/recipient/handlers.js
- src/routes/recipient/handlers.test.js
- src/services/goalSimilarityGroup.test.js
- src/services/goalSimilarityGroup.ts
An approach to solving the present user issue detailed in #2043 that wouldn't involve any DB schema updates or having to invalidate any existing similarity groups. Reasons why we might want an alternate approach are detailed in the discussion on that PR.
- Load prod data
- Visit /recipient-tta-records/1411/region/5/rttapa. Note the number of similarity goals. Visit each goal; none should take you to blank pages
- Visit /recipient-tta-records/1411/region/9/rttapa. Note the number of similarity goals. The groups should be different than the previous page. Visit each goal; none should take you to blank pages
* https://jira.acf.gov/browse/TTAHUB-2736
> [TTAHUB-2736] Alternate solution for filtering similarity response by region ID

- frontend/src/pages/TrainingReportForm/index.js
User was unable to save event due to the fact the the payload became too large. After some investigation it turns out we were saving nested session reports with each save in the blob.
This fix removes the session reports from the event save data.
-Review the code
-Impersonate the user from the JIRA ticket you should be able to save the event without issue.
* https://jira.acf.gov/browse/TTAHUB-2745
> [TTAHUB-2745] Prevent saving of session reports in data blob

- .circleci/config.yml
- frontend/src/pages/SessionForm/__tests__/index.js
- frontend/src/pages/SessionForm/components/ParticipantsNumberOfParticipants.js
- frontend/src/pages/SessionForm/components/ParticipantsReadOnly.js
- frontend/src/pages/SessionForm/constants.js
- frontend/src/pages/SessionForm/pages/__tests__/participants.js
- frontend/src/pages/SessionForm/pages/participants.js
- frontend/src/pages/SessionForm/pages/sessionSummary.js
- tests/e2e/training-report.spec.ts
Add drop down for IST visit and add audience of TTA/RO
- Session form, participants section
- New field: "is this an IST visit?" 
- If no, you can choose recipients
- If yes, you choose from a list of roles
Confirm that the above works and matches the design. Note: this is deployed to sandbox currently.
* https://jira.acf.gov/browse/TTAHUB-2510
> [TTAHUB-2510] Add IST visit dropdown to session form

- frontend/src/components/GoalForm/GoalNudge.js
- frontend/src/components/GoalForm/GoalNudgeInitiativePicker.js
- frontend/src/components/GoalForm/index.js
- When picking an OHS initiative goal on the goal nudge via keyboard, automatically shift focus **up** from the checkbox to the selector
- Also made some changes to the loading text, and to the labeling so that it was clearer what was happening
> Accessibility improvements for the goal nudge

- src/policies/event.js
- src/policies/event.test.js
- src/routes/sessionReports/handlers.js
- src/routes/sessionReports/handlers.test.js
Update the group permissions so that POC can get a list of groups
To recreate support issue:
- Use the most recent production data
- Impersonate the user from the ticket, using the report noted. 
- Edit sessions using a group (participants page > is ist report? no. > checkbox should appear)
To recreate in a vanilla setup
- Create a TR and a group in the matching region. Add a poc user as co-owner
- As a POC user without read/write permissions, access the session report as above and confirm the behavior
* https://jira.acf.gov/browse/TTAHUB-2828
> [TTAHUB-2828] Group permissions update for session report

- frontend/src/components/GoalForm/ObjectiveForm.js
- frontend/src/components/GoalForm/ResourceRepeater.js
- frontend/src/components/GoalForm/__tests__/ResourceRepeater.js
This fixes a bug when an invalid resource is added to the AR or RTR objective. We then remove the bad resource URL but the validation message persists. 
This issue occurs on both the AR and RTR pages:
- For the AR fix we call the validation on remove via the controller onBlur().
- For the RTR we pass a separate function to validate on removal. 
_NOTE: This is because the new setState resources have not yet been updated in react at the time of validation._
To test enter an invalid URL on the AR and RTR. Removing the bad URL should clear the invalid URL message.
* https://jira.acf.gov/browse/TTAHUB-1144
> [TTAHUB-1144] Fix resource validation

- src/migrations/20240503000000-merge_to_fei_goal.js
The user had an old non-FEI goal they wanted merged into their textually dissimilar FEI goal.
There's a result set at the end that should look like:
```
op_order |            operation             | cnt
----------+----------------------------------+-----
1 | deleted_gfrs                     |   0
2 | updated_target_objectives        |   0
3 | relinked_objective_topics        |   0
4 | relinked_objective_resources     |   0
5 | relinked_objective_files         |   0
6 | deleted_objective_topics         |   0
7 | deleted_objective_resources      |   0
8 | deleted_objective_files          |   0
9 | relinked_objectives              |   1
10 | updated_target_goals             |   1
11 | relinked_args                    |   2
12 | deleted_args                     |   0
13 | deleted_goals …
```
> [TTAHUB-2880] merge non-fei goal to fei goal

- frontend/src/components/Navigator/ActivityReportNavigator.js
- frontend/src/components/Navigator/__tests__/ActivityReportNavigator.js
- frontend/src/pages/ActivityReport/Pages/components/OtherEntity.js
- frontend/src/pages/ActivityReport/Pages/components/__tests__/OtherEntity.js
- tests/e2e/activity-report.spec.ts
Logic for "shouldAutoUpdate" is exactly backwards. The function was intended to catch autosaves when a user was in the middle of updating TTA provided. If we are _not_ auto-saving, it's fine to update form data, since that means a user has manually initiated a save.
This PR fixes this logic, as well as adds an e2e test to verify this behavior. It also fixes a perceivable loss of data that I encountered while testing; you need to enter other entities before entering objectives.
- Create an other-entity report
- Add required data, including objectives
- Delete objectives
- Note the form state is updated in the side nav and you can no longer submit a report
* https://jira.acf.gov/browse/TTAHUB-2899
> [TTAHUB-2899] Close loophole when removing objectives from OE report

- frontend/package.json
- frontend/src/pages/Admin/components/CsvImport.js
- frontend/src/pages/Admin/components/__tests__/CsvImport.js
- frontend/yarn.lock
The default encoding of CSV files in Excel is [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252). This is an outdated encoding and as far as I can tell is being replaced by UTF-8. This change ensures that the user is creating their CSV as CSV UTF-8.
**NOTE:** This historical data cleanup for this will be a different ticket.
Import the CSV with the default windows csv encoding you should see an error. Then import a CSV with the CSV UTF-8 **attached to the JIRA**. It should import 113 records and all Spanish chars should show up correctly.
* https://jira.acf.gov/browse/TTAHUB-2830
> [TTAHUB-2830] Require that CSV is in UTF-8 encoding

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/GoalCards.js
- frontend/src/components/GoalForm/Form.js
- frontend/src/components/GoalForm/ObjectiveForm.js
- frontend/src/components/GoalForm/__tests__/Form.js
- frontend/src/components/GoalForm/__tests__/ObjectiveForm.js
1. If a user doesn't have permission to create reports in a region they shouldn't be able to edit a RTR goal in that region. That being said they should be able to view the goal with read only permissions.
2. If a user is read only they shouldn't be able to change the goal source OR support type when viewing the goal.
_Note: Confirmed with Angela even if the user is an admin but doesn't have the permission hide the option._
1. Visit the RTR without the write permission for that region. You should not be able to edit the goal (but should be able to view). Add the permission for that region you now should be able to edit.
2. Viewing a goal with read only permissions shouldn't allow the user to change the goal source OR support type. 
* https://jira.acf.gov/browse/TTAHUB-2895
> [TTAHUB-2895] Hide edit button if the user has incorrect permissions

- frontend/src/components/SiteNav.js
- frontend/src/pages/ResourcesDashboard/__tests__/index.js
Changed instances of "Resources Dashboard" to "Resource Dashboard"
Look at name in left navigation bar
* https://jira.acf.gov/browse/TTAHUB-2918
> [TTAHUB-2918] Change "Resources Dashboard" to "Resource Dashboard" in left sidebar

- automation/common/scripts/awscli_install.sh
- automation/common/scripts/postgrescli_install.sh
awscli is actively under development, so new versions are released often. This makes hash verification of the latest version fail as soon as the next version is released. This change locks to a specific version.
Run db backup script, awscli should download and install without failing the hash verification.
* https://jira.acf.gov/browse/TTAHUB-3003
> [TTAHUB-3003] Update awscli_install.sh to version lock awscli

- .circleci/config.yml
Add step in circleci to auto-backup production as part of the deployment process, So that any failed deployment can be reverted back to a known good state.
It runs the same DB backup function that the scheduled backup does, just as part of the production deployment job. Only the production deployment job.
* https://jira.acf.gov/browse/TTAHUB-3022
> [TTAHUB-3022] Backup production DB on each deploy

- frontend/src/components/Navigator/ActivityReportNavigator.js
- frontend/src/components/Navigator/__tests__/ActivityReportNavigator.js
- frontend/src/pages/ActivityReport/Pages/Review/SomeGoalsHaveNoPromptResponse.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/Draft.js
- frontend/src/pages/ActivityReport/Pages/Review/Submitter/__tests__/index.js
- frontend/src/pages/ActivityReport/Pages/Review/__tests__/SomeGoalsHaveNoPromptResponse.js
- frontend/src/pages/ActivityReport/index.js
- src/goalServices/getGoalsMissingDataForActivityReportSubmission.test.js
- src/goalServices/getGoalsMissingDataForActivityReportSubmission.ts
Fix bug reported where 1 recipient with no root cause was not showing up in the alert we show in the activity report for this very purpose.
1. RTR: Create FEI goal for two different recipients. Add root cause for one recipient. The second recipient does not have a root cause for the FEI goal.
2. Create AR with both recipients and fill in all mandatory fields. 
3. You will see an error message that root cause is missing, and a hyperlink to link to the goal page
4. Using the link, edit the goal in the RTR
5. Returning to the AR (it should still be open in an existing tab), click "refresh goal data" on the alert
6. If there are no goals missing data, the alert should disappear.
* https://jira.acf.gov/browse/TTAHUB-2787
> [TTAHUB-2787] Improve missing goal response experience somewhat

- src/migrations/20240607000000-fix-timeseries.js
This replaces the existing create_timeseries_from_audit_log with a new one capable of creating timeseries tables when a column is an array of enums. It's basically the same function with an extra case in the switch to handle that one column type.
Try to create a timeseries of the `Users` table: `SELECT create_timeseries_from_audit_log('Users');`
N/A
> [No Jira] Bugfix: handle arrays of enums when creating timeseries

- src/migrations/20240610110823-remove-unwanted-objectives.js
There are ten 'Not started' objectives associated with **goal 66089** . This migrations removes them from the db.
Verified all objectives are linked to reports in draft status.
- Using the latest prod db you should see ten objectives for this goal not started. After running the migration they should be removed.
* https://jira.acf.gov/browse/TTAHUB-3057
> [TTAHUB-3057] Migration to remove unwanted objectives

- frontend/src/components/ReadOnlyContent.scss
Looks like this is a known issue in windows where @media print doesn't respect the css unless we use !important.
https://stackoverflow.com/questions/17942969/css-media-print-not-working-at-all
https://www.smashingmagazine.com/2013/03/tips-and-tricks-for-print-style-sheets/
After Fix:
- Review the change
- Make sure there is no unwanted space after 'Activity date' in the 'Print to PDF' when destination is 'Save as PDF'.
* https://jira.acf.gov/browse/TTAHUB-2667
> [TTAHUIB-2667] Fix unwanted space after activity date

- frontend/src/components/filter/__tests__/goalFilters.js
- frontend/src/components/filter/goalFilters.js
This small PR appends the grant's status to its label in the filter selection:
This is on the RTR -> RTTAPA tab.
The existing test which tests the filter label was updated.
* https://jira.acf.gov/browse/TTAHUB-2132
> [TTAHUB-2132] Add grant status to filter select

- src/routes/courses/index.ts
`GET /:id` was registered before `GET /dashboard`, which is not good, so a `GET /dashboard` actually hits `GET /:id`, and there's no course with an id of "dashboard".
Whoops.
Maybe we merge this so it makes its way to staging, so we can verify this indeed does not cause the app to crash when visiting the course dashboard.
> [NO-TICKET] Hotfix: course route registration order

- src/migrations/20240627000000-uncomplete_trs_and_remove_goals.js
Two TRs have incorrect goal text but sessions have been completed and goals created. This PR resets the Event Reports and Session Reports back to `In progress` and deletes all the erroneous goals.
It does not reset values of the session reports that are embedded inside the event report's JSONB blob, but testing indicates that this is not necessary; everything works properly as long as the session report itself is updated.
The goals on both event reports should now be editable. On prod they're at:
https://ttahub.ohs.acf.hhs.gov/training-report/view/5017
https://ttahub.ohs.acf.hhs.gov/training-report/view/5019
* https://jira.acf.gov/browse/TTAHUB-3140
> [TTAHUB-3140]reset two TRs so goals can be fixed

- src/models/hooks/sessionReportPilot.js
- src/models/hooks/sessionReportPilot.test.js
It was possible that `nextSessionRecipients` never became an array, so the `map` operation threw. It's the only `map` operation in the function, so I think we can be sure it's the culprit of the error seen in the ticket.
This small change just makes sure it's an array.
One of the tests was updated to not provide an array value to `data.recipients`, which probably does a good enough job of testing this.
* https://jira.acf.gov/browse/TTAHUB-3114
> [TTAHUB-3114] removeGoalsForSessionRecipientsIfNecessary bugfix

- src/lib/cron.js
- src/models/activityReportCollaborator.js
- src/models/tests/activityReportCollaborator.test.js
Issue TTAHUB-3146 shows up in production at 16:00 EST which is the current time to run the digest notifications. Unfortunately, this issue does not show up locally. This PR changes the run time of the different digest notifications as well as adds logging in a place that looks like it could be causing the error.
Verify the tests pass.
* https://jira.acf.gov/browse/TTAHUB-3147
> [TTAHUB-3147] Adjust cron start times

- src/policies/goals.js
- src/policies/goals.test.js
It looks like we don't gracefully handle the case where when checking goal.canView(), we pass in an ID that doesn't return a record. This adds an "if" statement and some tests to confirm.
Confirm the unit tests resolve the problem listed in the Jira, I think those should be sufficient.
* https://jira.acf.gov/browse/TTAHUB-3117
> [TTAHUB-3117] handle exceptions in goal policy

- src/policies/goals.js
- src/policies/goals.test.js
- src/routes/goals/handlers.js
In addition to read/write reports and approve reports, admins should be able to delete goals regardless of region.
Load the prod dataset and confirm that you, as an admin user, can delete the goals listed in the Jira ticket
* https://jira.acf.gov/browse/TTAHUB-3134
> [TTAHUB-3134] Allow admins to delete goals 

- src/lib/importSystem/record.ts
- src/lib/importSystem/tests/record.test.js
- src/migrations/20240702000000-monitoring-config-correction.js
- src/testUtils.js
- `MonitoringFindings `field `ReportedDate `was misconfigured as `ReportDate`
- Duplicate file name entries in `ImportFiles` would cause an error, removing duplicate entries
- Add a unique index on the `name `atttibues of the `ftpFileInfo `in `ImportFiles `to aid in preventing duplicates
Testing is quite difficult to test, to requires concurrent execution of schedule job to be triggered. Which the lockManager prevents a majority of the time. But there is apparently a small window where the race condition was still happening. Adding the unique index constraint should close the window for race conditions even further.
* https://jira.acf.gov/browse/TTAHUB-3125
> [TTAHUB-3125] Monitoring Data Issue

- src/models/hooks/goal.js
- src/models/hooks/goal.test.js
This PR addresses a Foreign Key constraint error that occurs when a goal similarity group can't be deleted due to a goalSimilarityGroupGoal still referencing it. With this fix, we are now looking for all goalSimilarityGroupGoal entries that are associated with the groups being deleted.
Look at the code and verify that the tests pass
* https://jira.acf.gov/browse/TTAHUB-3165
> [TTAHUB-3165] Fix FK error during goal similarity groups invalidation after goal update

- frontend/src/components/RecipientsWithGroups.js
- frontend/src/pages/SessionForm/pages/participants.js
Just in case a session doesn't have a region ID, check the blob for the event. This way, recipients will be fetched in both cases.
You can check this by checking out prod data and taking a look at the support case in the ticket. On this branch, there will be no issue.
You could also manually set a session to have a region ID of "" locally. On main, this would prevent session recipients from being fetched. On this branch, they will still be fetched.
* https://jira.acf.gov/browse/TTAHUB-3187
> Fix for recipient groups component

- src/migrations/20240715000000-fix-old-session-regions.js
The very first Session record ever created back in August 2023 didn't get the regionId (`data->'regionId'`) value populated for some reason. This resulted in not being able to select participants from the region (because there wasn't one) for that session. There's a separate PR to make this selection more robust by using the Event's region if it isn't populated for the session, but this PR fixes the data so that it won't be a problem in any other contexts
There's a little test at the end, but also you can also look at https://ttahub.ohs.acf.hhs.gov/training-report/2031/session/2/participants
* https://jira.acf.gov/browse/TTAHUB-3187
> [TTAHUB-3187] populate regionId on old session report

- frontend/src/fetchers/activityReports.js
- frontend/src/pages/ActivityReport/__tests__/index.js
- frontend/src/pages/ActivityReport/__tests__/localStorage.js
- frontend/src/pages/ActivityReport/index.js
- src/routes/activityReports/handlers.js
- src/routes/activityReports/index.js
- src/services/activityReports.js
Modifies `possibleRecipients` to accept an optional report id. If the report id is provided, it returns recipients that *may be expired, but have been used on this report previously*.
It also adds a new endpoint
`/api/activity-report/activity-recipients/:reportId`
Use the seeded data. Be Hermione. Give yourself unlock permissions. The report with id 9999 already has a recipient that is Inactive. Unlock report 9999. Edit it, go to the account summary, remove the recipient from the dropdown, expand the dropdown and you should still have the old recipient in the list even though they are expired. Save the report. Be sure the save takes effect.
* https://jira.acf.gov/browse/TTAHUB-3095
> [TTAHUB-3095] Don't remove expired grants from the recipients dropdown when an AR is unlocked

- frontend/package.json
- frontend/yarn.lock
Address longstanding, harmless, yet annoying log output
No warnings:
Run yarn deps (or yarn docker:deps, or whatever your preferred flavor is) and observe a distinct lack of Evil Martians
> Move postCSS to peer deps and dev deps

- .cfignore
- .circleci/config.yml
- sql files are needed for the ssdi
- testing files should not be on deployed env
> [NO JIRA] Keep sql and drop test files

- src/services/recipient.js
Fetch topics data on the RTTAPA with Sequelize's ```separate: true``` flag, since the current way seems to run up against some limit with certain recipients.
Confirm the RTTAPA cards display the correct topics. Open the case from the support ticket. Confirm that the recipient is visible and that the goal query doesn't time out and display an error in the front end.
* https://jira.acf.gov/browse/TTAHUB-3192
> [TTAHUB-3192] Fetch topics separately for RTTAPA

- README.md
> Update network policy instructions in README

- src/services/activityReports.js
- src/services/activityReports.test.js
This change ensures that we only show inactive grants if the inactivation date is 60 days from either todays date for new reports. Or 60 days from the start date if an existing report. In Jon's previous PR he ensures that any grant that was linked via the activity recipient's table will still show in the grant list regardless of date.
- Make sure for a new report we show inactive grants within 60 days from today's date.
- Make sure for existing reports with and without a start date we show inactive grants respectively.
- Make sure Jon's fix in the previous PR still works as expected (see above description).
* https://jira.acf.gov/browse/TTAHUB-3096
> [TTAHUB-3096] Include inactive grants that fall within 60 day inactivation date

- config/config.js
- frontend/src/pages/Admin/TrainingReports.js
- frontend/src/pages/TrainingReportForm/pages/eventSummary.js
- src/policies/event.js
- src/services/event.test.js
- src/services/event.ts
The jira ticket has great, detailed information on the change but essentially it was four-fold: 
- Import and populate the POC in the form
- Fix the audience field so it populates the form
- Fix the event duration field so that it populates the "training type" field in the form
- Add clear specifications to the admin import page so we have a reference for expected headings and content
- Automatically populate the collaborators based on the National Center column in the import
Confirm using the XSLX file attached to the ticket that the fields are imported correctly. You may need to massage the data slightly, which I expect an engineer will do when the training reports are imported.
* https://jira.acf.gov/browse/TTAHUB-3240
> Update expected imports given new CSV

- src/app.js
This PR addresses a medium security alert identified during the dynamic security scan. The scan flagged the use of unsafe-inline in the style-src directive of our CSP. To mitigate this risk, we have updated our CSP configuration to include a nonce for inline styles.
- Verify that the application works as expected with the updated CSP configuration.
- Confirm that the dynamic security scan no longer flags the unsafe-inline issue.
* https://jira.acf.gov/browse/TTAHUB-3040
> [TTAHUB-3040] Fix medium security alert: add nonce to inline styles in CSP

- src/goalServices/reduceGoals.ts
- src/migrations/20240802204120-repair-multiple-aros.js
In two (reported) instances, goals ended up with new lines at the end, so I revised the reducer to capture this as the same goal. Additionally, we have a report where multiple AROs were created for a Objective/AR combination. No idea how.
- Prod DB
- Confirm the support cases are resolved (goals not duplicated, all information present)
* https://jira.acf.gov/browse/TTAHUB-3266
* https://jira.acf.gov/browse/TTAHUB-3267
> Fix duplicating goals on two reports from support cases

- src/migrations/20240801000000-merge_duplicate_args.js
This issue hasn't been seen in months and a number of possible causes of the problem have been fixed so this just cleans up historical cases
All this does is run `SELECT dedupe_args();`, which ideally never does anything, but will fix historical duplicate ARGs by merging down to one single record anchoring all the metadata about the link between any given AR and Goal pair. 66 dupes are expected to be deleted in this case and no metadata moved.
* https://jira.acf.gov/browse/TTAHUB-2553
> [TTAHUB-2553]Fix historical duplicate args

- .circleci/config.yml
- tests/api/playwright.config.js
- tests/e2e/activity-report.spec.ts
- tests/e2e/playwright.config.js
Fix playwright artifacts storage in CI.
* Before: Nothing in the "artifacts" tab in CI (test_e2e and test_api jobs).
* After: "artifacts" tab populated in CI (test_e2e and test_api jobs).
In the artifacts tab for one of the jobs, test_e2e for example, find and click on `tests/e2e/html-report/index.html`. A nice UI should be displayed with a video for each test, a trace, and screenshot. Watch a video. Play with the trace.
* https://jira.acf.gov/browse/TTAHUB-3279
> [TTAHUB-3279] Fix playwright artifacts storage in CI

- src/migrations/20240807172716-reset-session-completions.js
Four sessions are not editable because they have already been marked complete by POC. A support request has asked us to revert this completion status so that they can be edited.
To do this, we set:
* `pocComplete` to `false`
* `pocCompleteId` to `""`
* `pocCompleteDate` to `""`
...on both the event and the session
* Restore latest prod backup and run migrations.
* Impersonate user 9 and visit the following URLs:
* http://localhost:3000/training-report/5017/session/102/next-steps 
* http://localhost:3000/training-report/5017/session/74/participants 
* http://localhost:3000/training-report/5017/session/92/participants 
* http://localhost:3000/training-report/5017/session/101/next-steps
* Ensure every form is editable.
* https://jira.acf.gov/browse/TTAHUB-3265
> [TTAHUB-3265] Support request: Reset session completion status

- frontend/src/components/GoalCards/GoalDataController.js
- frontend/src/pages/RecipientRecord/pages/__tests__/GoalsObjectives.js
This was an issue on the RTR goals page. If we go to the second page of goals, then filter a result that only has one page. The user would be stuck on the second page with no results shown (event though the first page had results).
**NOTE:** I'm not sure if this impacts other pages, but we will start here first.
- Test the use case in the jira
CASE: Apply a goal text filter for something common like "class" while on the second or third page.
* https://jira.acf.gov/browse/TTAHUB-2765
> [TTAHUB-2765] Reset page when filter changes

- frontend/src/pages/TrainingReportForm/__tests__/index.js
- frontend/src/pages/TrainingReportForm/index.js
We need to capture the "eventSubmitted" variable in the data of a Training Report when the owner submits it. The "complete event" functionality depends on it. It seems to have been removed as part of a bug squash.
Recreate the issue described in this slack thread
https://adhoc.slack.com/archives/C022R5301L4/p1725032185745969
Once you submit the event in question, you should be able to complete it.
Alternately, confirm "eventSubmitted" is present in the request body when submitting a training report.
> Set event submitted: true when event is being submitted

- .circleci/config.yml
This PR escapes quotes in PR titles while extracting the text used for the slack notification message. It also adds a PR link to the successfull deployment message.
Verify the code change looks ok.
* https://jira.acf.gov/browse/TTAHUB-3336
- [ n/a] OHS demo complete
> [NO-TICKET] Escape "quotes" in PR titles while extracting the text.

- frontend/src/pages/ActivityReport/__tests__/formDataHelpers.js
- frontend/src/pages/ActivityReport/formDataHelpers.js
When an objective is created from and AR we populate the database field 'objectiveCreatedHere'. It looks like this was never being passed to the BE, so it was never persisted in the database. When the user clicks save draft on the objective, the value would come back to the FE as undefined. This would intern lock the objective text from being updated (even though it was created on the report).
- Make sure creating a new AR with objectives doesn't lock the objective text (also the column 'objectiveCreatedHere' is populated correctly).
- Make sure using objectives on report that were NOT created on the report have the correct value.
* https://jira.acf.gov/browse/TTAHUB-3370
> [TTAHUB-3370] Pass the 'createdHere' to the BE so its persisted

- frontend/src/pages/Admin/FeedPreview.js
- frontend/src/pages/Admin/__tests__/FeedPreview.js
- frontend/src/pages/Admin/__tests__/index.js
- frontend/src/pages/Admin/index.js
This is a tool to allow those authoring content in confluence to preview how it will look on the site via the admin interface
- Go the the admin interface
- Click on "feed preview"
- Enter information into the form and submit
- The "preview drawer" link pops up (it's small) and you can preview the drawer content.
> Add tool for previewing confluence RSS data

- src/models/hooks/activityReportGoal.js
- src/models/hooks/activityReportGoal.test.js
Adding a hook to populate the onAR and onApprovedAR flags when the merged goal is placed on the ActivityReportGoal records.
Merge goals that have been on an AR, the resulting goal has flags set correctly
* https://jira.acf.gov/browse/TTAHUB-3046
> [TTAHUB-3046] AR flags on merged goals need to be set

- src/services/communicationLog.test.js
- src/services/communicationLog.ts
The issue here is that the validation on the frontend (can we parse a valid date from what the user enters using the momentjs library?) normally combines with postgres date columns to standardize the saved format. Since we are saving the date here to a JSON field, the date field can contain any arbitrary value that moment can figure out. This change preempts the save and create communication log services to use moment's formatting to save whatever date it has parsed from user input.
Save a date in a non MM/DD/YYYY format  in the communication date field in the comm log. Save: the value in the UI and the database is corrected.
* https://jira.acf.gov/browse/TTAHUB-3452
> [TTAHUB-3452] Fix comm date validation

- frontend/src/pages/TrainingReportForm/pages/__tests__/eventSummary.js
- frontend/src/pages/TrainingReportForm/pages/eventSummary.js
Two form fields on the event summary were missing on blur handlers and therefore would not validate. This has been fixed
Confirm that event collaborators and regional point of contact fields are validated on blur if a selection was not made
* https://jira.acf.gov/browse/TTAHUB-3420
> [TTAHUB-3420] Fix two non-validating form fields

- frontend/src/pages/ResourcesDashboard/__tests__/index.js
- frontend/src/widgets/HorizontalTableWidget.js
- frontend/src/widgets/ResourceUseSparklineGraph.js
- frontend/src/widgets/__tests__/HorizontalTableWidget.js
- frontend/src/widgets/__tests__/ResourceUse.js
- src/services/dashboards/course.js
- src/services/dashboards/course.test.js
- src/services/dashboards/resource.js
Horizontal table widget was using nondescript aria-labels for its contents and also truncated date strings. Both of these are either hard to understand or inconsistent for screen-readers. This PR modifies those values so that they are more easily understood.
- Confirm hidden labels on Horizontal Table Widget for select row checkboxes and table headers are human-understandable
* https://jira.acf.gov/browse/TTAHUB-3423
> [TTAHUB-3423] Use separate labels for table data on Horizontal Table Widget

- Dockerfile
- docker-compose.debug.yml
- docker-compose.dss.yml
- docker-compose.override.yml
- docker-compose.test.yml
- docker-compose.yml
- yarn cache and node_modules are now in volumns to support sharing across containers and reuse between rebuilds of containers.
- side effect, (which is also good) host os architecture node_modules are now not loaded into the container for execution or deps 
- delete all node containers
- run yarn docker:deps
* https://jira.acf.gov/browse/TTAHUB-2549
> [TTAHUB-2549] Operation warp speed

- src/scopes/grants/index.test.js
- src/scopes/grants/recipientsWithoutTTA.js
The filter used to look like this:
```sql
WHERE
(ar."startDate", ar."endDate")
OVERLAPS
(DATE ${sequelize.escape(beginActivityDate)} - 1, DATE ${sequelize.escape(finishActivityDate)} + 1)
)
```
so if you filter for 3/20/2024 -> 3/20/2024, ARs from 3/19/2024 and 3/21/2024 would be included because of the `OVERLAPS`. The query now looks like this:
```sql
WHERE
ar."startDate" <= ${sequelize.escape(finishActivityDate)}
AND ar."endDate" >= ${sequelize.escape(beginActivityDate)}
```
* https://jira.acf.gov/browse/TTAHUB-3450
> [TTAHUB-3450] Update "recipients with no TTA" filter to not use overlaps

- src/queries/dataRequests/ohs/standard-goal-activity-reports.sql
Low-number ARs could hit on other ARs with IDs that contain the same IDs, and also legacy ARs use their own IDs that don't use our table pkey. This makes queries that include ARs from before July 31st, 2021 likely to be inaccurate.
It should give the same results the old query game, except for old ARs. Including old ARs will usually reduce the maximum number of ARs per URL because the max string length is longer.
Non Jira fix
> make ssdi results more accurate for early ARs

- frontend/src/pages/QADashboard/RecipientsWithNoTta/index.js
- frontend/src/widgets/HorizontalTableWidget.js
- frontend/src/widgets/RecipientsWithNoTtaWidget.js
- frontend/src/widgets/__tests__/HorizontalTableWidget.js
After merging to staging I noticed sorting on the "Recipients with No TTA" widget stopped working. This fixes the issue by allowing the values to be null but showing them as a '-'.
- Make sure sorting works on the No recipients widget.
- Mae sure sorts work on other widgets in the QA dash.
> Fix sorting on the recipients with no tta widget

- frontend/src/components/filter/FilterFEIRootCause.js
- frontend/src/components/filter/goalFilters.js
- frontend/src/pages/RecipientRecord/pages/constants.js
- src/scopes/goals/goalResponse.ts
- src/scopes/goals/index.js
- src/scopes/goals/index.test.js
Adds an FEI root cause/GoalFieldResponses filter to the RTR using basically the same query from the AR's `activityReportGoalResponse` filter.
* https://jira.acf.gov/browse/TTAHUB-3190
> [TTAHUB-3190] Add GoalFieldResponses filter to RTR

- src/queries/api/dashboards/qa/dashboard.sql
We only want to show "Specialist roles" on the role graph.
Make sure we do NOT show non-specialist roles on the role graph like AA.
SELECT * FROM "Roles" WHERE "isSpecialist" = true
> Only show specialist roles

- frontend/src/pages/RecipientRecord/pages/constants.js
- frontend/src/pages/RecipientSearch/constants.js
- src/scopes/grants/goalResponse.ts
- src/scopes/grants/index.js
- src/scopes/grants/index.test.js
- src/scopes/utils.ts
I overlooked this in 3190. I looked at the prototype and thought that we wanted this filter on the RTR, and NOT on the RTR **search** page. They want it on the search page. This is an entirely different filter for Grants and not Goals.
In this PR I add a new goalResponse filter for Grants and include it on the search page. It hides the goalResponse filter on the RTR but does not remove the code, because maybe we want it later?
Filter tests were added, but you can test by going to the RTR and using the filter.
* https://jira.acf.gov/browse/TTAHUB-3190
> [HOTFIX-3190] Add (and use) grants root cause filter

- frontend/src/widgets/DeliveryMethodGraph.js
Referring to the delivery method graph on the QA dashboard: virtual data was showing up under in-person and vice-versa. Hybrid was correct.
Confirm (easiest way to do that is view the response from the network tab and comparing it to the graph) that the data is correct
> Fix delivery method graph order on QA dash

- src/migrations/20241030114000-monitoring-import-cadence.js
Through observation some days miss the window to get the latest monitoring data due to dns failures or system reboots. This change will trigger the collection 4 times per 24 hours in an attempt to recover before the next day should the intended window be missed. Nothing happens if it is triggered and no work needs to be done.
was 8:30 am every day, now 2:30 AM, 8:30 AM, 2:30 PM, 8:30 PM
Validate the new cron schedule.
* https://jira.acf.gov/browse/TTAHUB-3500
> [TTAHUB-3500] Monitoring Import Cadence adjustment to bypass minor issues

- .circleci/README.md
- .circleci/config.yml
This update enhances the CircleCI configuration, specifically the `manual_manage_env_workflow`, to streamline the management of application environments by introducing dynamic environment-specific handling. Now, only `env_list` is required as an argument, with space, username, and password automatically inferred for each environment. Key improvements include flexibility in managing application states with options for start, stop, restart, or restage operations.
1. **Simplified Workflow Trigger**:
- The `manual_manage_env_workflow` now relies solely on the `env_list` parameter, eliminating the need for `space_list` and `cloudgov` parameters to manually specify spaces, usernames, or passwords.
- Environment-specific variables (e.g., `CLOUDGOV_DEV_PASSWORD`, `CLOUDGOV_SANDBOX_SPACE`) are …
> [TTAHUB-3064] Self Service Automation - Deployed Environment: Time Slice - Phase 1: Power down lower environments during off hours

- src/scopes/goals/endDate.ts
- src/scopes/goals/startDate.ts
Update the `startDate` filter to have valid date syntax in the query.
- Invalid: BETWEEN 2020/02/22 AND 2020/02/23
- Valid: BETWEEN 2020-02-22 AND 2020-02-23
To take this a little further and be a little more safe, we call `new Date('2020/02/22').toISOString()`.
Also updated the `endDate` filter to use this same method.
Go to the TTA history tab under the RTR and make sure the "Topics in activity reports" widget loads correctly.
* https://jira.acf.gov/browse/TTAHUB-3588
> [TTAHUB-3588] startDate filter bugfix

- src/services/activityReports.js
- src/services/activityReports.test.js
The frontend validates the complete date for next steps using moment, but moment will validate certain values that won't be accepted by postgres. The example from the ticket was "11/11/2023 12:00pm." This change means that the backend will re-validate using the same logic as the frontend and also outputs a formatted version that will be accepted by postgres.
Use "11/11/2023 12:00pm" as a value for a next step complete date on an activity report. Confirm it saves as "11/11/2023."
* https://jira.acf.gov/browse/TTAHUB-2295
> [TTAHUB-2295] Next steps validation

- frontend/src/components/BackLink.js
- frontend/src/components/BackLink.scss
Update the back link component to use the correct link color
Confirm the above. The hex for the correct color is #46789B and should be used in both regular and visited context.
* https://jira.acf.gov/browse/TTAHUB-3421
> [TTAHUB-3421] Link color

- src/lib/mailer/index.js
- src/lib/mailer/index.test.js
- src/services/event.ts
- Digests were not correctly logging "onCompleteNotification"
- An invalid constant was used for one of the jobs
- TR notifications had start date and end date backwards
- Confirm that digests send without error (this is onerous to set up locally, I apologize)
- Confirm that the correct constant was used the recipient report approved digest job
- Confirm that POC notifications will send for the TR report "missingSessionInfo" job
* https://jira.acf.gov/browse/TTAHUB-3326
> [TTAHUB-3326] Fix some mailer bugs

- src/scopes/grants/activeWithin.js
- src/widgets/helpers.js
There was a bug within a function for combining arbitrary scopes with scopes needed for grant replacement. A typo meant that Sequelize was attempting to treat an empty array as scope (i.e. ```[[]]```).
Since no scopes actually pass an include except the buggy one with the empty array, I removed the use of that function in this spot entirely.
You can apply the Date Started (AR) _on or before_ or _is within_ conditions on the regional dashboard and all the graphs load.
* https://jira.acf.gov/browse/TTAHUB-3630
> [TTAHUB-3630] Remove unneeded grant scope merge

- src/scopes/activityReport/resourceAttachment.js
- src/scopes/activityReport/resourceUrl.js
- src/scopes/goals/reportText.js
- src/scopes/goals/resouceUrl.js
- src/scopes/goals/resourceAttachment.js
Each of these scopes had a default value parameter that was never used, which accounts for all of the unused branches in each file.
* https://jira.acf.gov/browse/TTAHUB-3550
* https://jira.acf.gov/browse/TTAHUB-3551
* https://jira.acf.gov/browse/TTAHUB-3552
* https://jira.acf.gov/browse/TTAHUB-3555
* https://jira.acf.gov/browse/TTAHUB-3556
> [TTAHUB-3550/3551/3552/3555/3556] Coverage >= 90%

- .githooks/pre-commit
- frontend/package.json
Leverage the docker container when available for linting when available. When docker is not available make sure node_modules is populated before trying to lint.
Run changes are normal when pre-commit hook should run, and confirm it runs as expected.
* https://jira.acf.gov/browse/TTAHUB-3508
> [TTAHUB-3508] Pre-commit lint for docker users

- automation/common/scripts/postgrescli_install.sh
Update from postgresql-client-15_15.8 to postgresql-client-15_15.10 as the *.8 version is no longer available.
This client tool us used in the automation app within the production cloud.gov space as part of the DB backup process only. It does not have any effect in any way on the production or lower environments for running the TTA HUB website.
Manually trigger a db backup, or check that the following link has succeeded.
https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/20578/workflows/8d433144-8e5f-4be2-afd0-a16c6829234a/jobs/132601
* https://jira.acf.gov/browse/TTAHUB-3661
> [TTAHUB-3661] Update postgres client

- src/lib/cron.js
This disables only trainingReportTaskDueNotifications by requiring an env var to be set to `true` for it to execute. This seemed like the minimal version of this.
Seems like this would be very hard to test, but it's also a very simple change.
* https://jira.acf.gov/browse/TTAHUB-3600
> disable trainingReportTaskDueNotifications by requiring env var

- .circleci/config.yml
The URL to download v7 https://packages.cloudfoundry.org/stable?release=debian64&version=v7&source=github now results in a 404, switching to v8 which has been in use for automation tasks.
deploy works
* https://jira.acf.gov/browse/TTAHUB-3676
> [TTAHUB-3676] update cf cli tools for deployment from v7 to v8

- src/middleware/authMiddleware.test.js
```bash
--------------------------------------------|---------|----------|---------|---------|-------------------
File                                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------------------------------|---------|----------|---------|---------|-------------------
All files                                   |   42.01 |     9.05 |   27.39 |   43.87 |                   
src/middleware                             |     100 |      100 |     100 |     100 |                   
authMiddleware.js                         |     100 |      100 |     100 |     100 |                   
scopeConstants.js                         |     100 |      100 |     100 |     100 | …
```
> [TTAHUB-3569] Coverage >= 90% src/middleware/authMiddleware.js

- package.json
- yarn.lock
Q: Why 0.1.12?
A: https://security.snyk.io/package/npm/path-to-regexp/0.1.10
> yarn vuln: update path-to-regexp to 0.1.12 or higher

- src/migrations/20241125000000-fix-missing-goal-source.js
Uses the events that created the goals to infer the proper Goals.createdVia values. After discussing different less satisfactory possibilities for inferring Goals.source values, the decision was to not try to do so.
There's a small diagnostic query at the end that should look like:
```
item         | cnt
---------------------+-----
goals to be updated | 195
new activityReport  | 191
new rtr             |   4
```
* https://jira.acf.gov/browse/TTAHUB-3611
> [TTAHUB-3611] recover missing Goals.createdVia values

- src/scopes/activityReport/index.test.js
- src/scopes/utils.ts
Using a date constructor appends a UTC offset for some reason; we don't need it as the date in the URL params are already in an acceptable YYYY-MM-DD ISO format
> Remove extra hours from start date, end date filters

- src/testUtils.js
You've probably seen this a few times:
I think the only time we save a recipient in this test is with the call to `createRecipient` in `testUtils`, and the only unique column on that table is `id`, so I'm guessing wrapping this in `faker.unique` might help.
> No ticket - maybe fix the TR reason list flake

- frontend/src/pages/ActivityReport/Pages/__tests__/goalsObjectives.js
- frontend/src/pages/ActivityReport/Pages/goalsObjectives.js
So this appears to have been around for some time. If we remove a goal while actively editing another goal we loose all goals on the screen (reloading refreshes from the db).
1. Create a report with two recipients.
2. Add a template goal and obj then save.
3. Add a regular goal and obj then save.
4. Edit the first template goal.
5. With the edit of the goal open, click 'remove' via the ... context menu on the other goal.
6. The current goal you are editing should be preserved and after saving you should no longer see the removed goal.
* https://jira.acf.gov/browse/TTAHUB-3738
> [TTAHUB-3738] Fix bug when removing a goal while editing another

- src/queries/api/dashboards/qa/class.sql
OHS changed the cutoff date for the change in CLASS score cutoffs from 2025 to the same date in 2027 per https://eclkc.ohs.acf.hhs.gov/policy/pi/acf-ohs-pi-24-07, so this just updates the SSDI query to reflect that in advance.
There aren't really any report delivery dates out that far, though this is a small enough change to where if there isn't a typo it should be safe.
* https://jira.acf.gov/browse/TTAHUB-3714
> [TTAHUB-3714] Push CLASS score cutoffs back two years

- src/migrations/20250107000000-clean-orphan-objectives.js
This soft-deletes all Objectives that were created on an AR but aren't on an AR. @AdamAdHocTeam fixed a bug that caused a lot of these to be created and this is the cleanup. However, this doesn't limit itself to only recipient objectives, because other-entity Objectives that are not connected to any AR are even more useless because they can't even connect to a Goal.
There's a bit at the end confirming the orphan objectives are all removed that should look like:
```
ord |             item              | cnt
-----+-------------------------------+------
1 | orphaned objectives           | 9008
2 | objectives marked deleted     | 9008
3 | remaining orphaned objectives |    0
```
* https://jira.acf.gov/browse/TTAHUB-3741
> [TTAHUB-3741] set deletedAt for objectives created on ARs but not on an AR

- .circleci/config.yml
- automation/ci/scripts/acquire-lock.sh
- automation/ci/scripts/cf_lambda.sh
- automation/ci/scripts/release-lock.sh
- automation/configs/processed-retention.yml
- automation/configs/production-retention.yml
- automation/db-backup/scripts/db_retention.sh
- Relocate backup retention handling to its own step.
- Limit to only deleting a max of 15 file sets per execution
- Add a feature to the lock system to allow a build from the same branch to usurp the lock when the same job and a higher build id is used. This is to prevent canceled builds from leaving a lock in place and failing subsequent builds due to failing to acquire a lock 
- Trigger pipeline using either manual-retention-production or manual-retention-processed set to true.
* https://jira.acf.gov/browse/TTAHUB-3770
> [TTAHUB-3770] Breakout backup retention processing

- frontend/src/pages/RecipientRecord/pages/Profile.js
- frontend/src/pages/RecipientRecord/pages/__tests__/Profile.js
In order to synchronize the monitoring tab and the profile tab in the RTR, this PR removes the filter for active grants in the monitoring query and instead retrieves data for all grants listed on a recipient record. 
View the profile tab and confirm that all grants have profile data listed, even inactive ones.
* https://jira.acf.gov/browse/TTAHUB-3756
> [TTAHUB-3756] Display inactive grants profile data; fix minor alignment issue

- .circleci/config.yml
- Small logic error in the new cf_migrate job in circleci config file. Other steps leverage the automation app in production, but the migrate needs to be aligned with the app in the environment. This means the lock needs to be on the app being used for the app running the migration. 
Trigger a restore on an environment, set manual-restore-staging or manual-restore-sandbox or manual-restore-dev to true.
* https://jira.acf.gov/browse/TTAHUB-3770
> [TTAHUB-3770] - cf_migrate in circleci config needs to lock the env's app, not automation

- frontend/src/pages/ActivityReport/Pages/activitySummary.js
- src/services/citations.ts
- tests/e2e/activity-report.spec.ts
This is a quick bug fix for filtering out goals that don't have the standard property.
- Review all the code.
- Change the date on AR summary make sure there is no uncaught error in the console.
> Fix for monitoring standard check

- src/routes/goalTemplates/handlers.ts
- src/services/goalTemplates.test.js
- src/services/goalTemplates.ts
Fix an error in the Sequelize where options that was returning a truncated list of standard goals. 
Pre-requisite: Your DB has monitoring goals
Create an AR for a grant that has monitoring goals. Confirm that the _full_ list of standard goals appears in the goal dropdown, **including** the monitoring goal.
Create an AR for a grant that does not have a. monitoring goal. Confirm that the _full_ list of standard goals appears in the goal dropdown, **excluding** the monitoring goal.
> Fix monitoring SQL for goal templates

- src/migrations/20250107000001-merge-duplicate-objectives.js
This finds all duplicate, uncomplete objectives (having the same `title` and `objectiveId`) and merges forward to either the chronologically next complete objective if one exists, or to the open objective with the most recent status update. It's long because it also merges the AROs underneath, and all the ARO links from there.
Every major step leaves behind an inspectable temp table, and also there are two result queries that should look like:
```
table_name            | updated_count | inserted_count | deleted_count
----------------------------------+---------------+----------------+---------------
ActivityReportObjectiveTopics    |            44 |              2 |            54
ActivityReportObjectiveCourses   |             0 |              0 |             0
ActivityReportObjectiveFiles …
```
> [TTHUB-3737] Merge duplicate uncomplete objectives

- src/migrations/20250121000000-add-aro-constraint.js
- src/services/dashboards/course.test.js
Adds constraint on the ActivityReportObjectives table so there can only be one record linking a given AR and Objective at a time, and fixes the tests that broke. The other 'broken' tests seem to just be unrelated flaky tests.
There's really nothing to test; this is just to prevent future duplicate AROs. No duplicate AROs have been seen recently. There's also an ARO dupe merge in https://github.com/HHS/Head-Start-TTADP/pull/2596, so the database should be totally clean even if somehow new dupe AROs sneak in between now and deployment.
* https://jira.acf.gov/browse/TTAHUB-3380
> [TTAHUB-3380] add dupe constraint to ARO

- src/lib/apiErrorHandler.js
- src/lib/apiErrorHandler.test.js
Adds code to automatically restart the server when a `SequelizeConnectionAcquireTimeoutError `occurs. Since we have a handler that exits the Node.js process for unhandled exceptions, an unhandled error is intentionally thrown upon encountering a `SequelizeConnectionAcquireTimeoutError` to trigger that mechanism.
Look at the code.
Verify tests pass.
* https://jira.acf.gov/browse/TTAHUB-3717
* https://jira.acf.gov/browse/TTAHUB-3837
> Auto restart on SequelizeConnectionAcquireTimeoutError

- src/lib/resource.js
- src/lib/resource.test.js
Update the ECKLC URL to the new HeadStart.gov for the resource metadata scrape.
- Make sure we didn't miss anything.
* https://jira.acf.gov/browse/TTAHUB-3776
> [TTAHUB-3776] Update the meta data url for resource scrape

- src/migrations/20250206180000-eo-close-goals-and-objectives.js
- src/widgets/helpers.js
- src/widgets/topicFrequencyGraph.js
Topics are soft deleted, so they will show up in the database through a "raw" query but not in a managed query. This change fixes a bug with the TTA history graph in the recipient record that combines data from two sources: a direct query to our database and a managed query through our database relationship software.
The TTA history page loads correctly
> [Prod] Handle a case in the TTA history graph where a topic is returned from the database but is null in the UI

- frontend/src/pages/ActivityReport/Pages/components/Objective.js
- src/services/reportCache.js
- src/services/reportCache.test.js
I was unable to reproduce this error so I think for now we can do two things:
1. Prevent submitting objective topics if the ID is null.
2. Log a more detailed error message in the terminal if it occurs again.
Hopefully these will let us narrow down if its a FE or BE issue.
- Make sure you cant save an objective if the topic id is null (you might need to modify the FE options).
- Ensure there is no other info we should add to the audit logger.
* https://jira.acf.gov/browse/TTAHUB-3718
> [TTAHUB-3718] Prevent and log error saving ARO topics

- frontend/src/components/MultiSelect.js
- frontend/src/components/selectOptionsReset.js
This ticket updates the color of the remove 'x' for individual items in react select.
New color should be: #1B1B1B
- Review the change
- Test it on various pages AR summary, objectives, TR, etc.
- Make sure we didn't miss any locations
* https://jira.acf.gov/browse/TTAHUB-3815
> [TTAHBU-3815] Update color of remove 'x' to meet accessibility contrast

- .circleci/config.yml
- src/app.js
This reverts commit a11310fe17e5850e69f2be145c72c1370807c860, reversing changes made to 7219e2740dc35795f5450e0b14231769bb5ced15.
We need to rethink how to handle resolving this OWASP finding. The way I implemented it works fine locally and in CI, but breaks in higher environments.
> Revert OWASP ZAP fix

- frontend/src/widgets/HorizontalTableWidget.js
- frontend/src/widgets/__tests__/HorizontalTableWidget.js
The HorizontalTableWidget was rendering checkboxes, expecting a `title` property to be provided. This PR just falls back to the `heading` property, which should be provided in all cases.
This also fixes TTAHUB-3814.
- Go to http://localhost:3000/dashboards/qa-dashboard/recipients-with-no-tta
- Make sure the checkboxes in the table have valid aria-label values.
* https://jira.acf.gov/browse/TTAHUB-3813
* https://jira.acf.gov/browse/TTAHUB-3814
> [TTAHUB-3813] A11y review: checkbox labels on HorizontalTableWidget

- frontend/src/widgets/DashboardOverviewContainer.js
- frontend/src/widgets/OverviewWidgetField.js
- frontend/src/widgets/QualityAssuranceDashboardOverview.js
Each of the links on the QA dashboard have the same link text and no aria label to differentiate them. This PR just adds an aria label to each of them.
Make sure each link has a label:
* https://jira.acf.gov/browse/TTAHUB-3817
> [TTAHUB-3817] Add aria labels to links with unique text

- src/migrations/20250224000000-bring-back-status-for-suspended.js
A migration update on 2/14/25 inadvertently removed the ability to transition suspended goals back to their previous status. This also caused an issue where objectives could no longer be added to goals.
This PR resolves the issue by restoring the previous status from the audit log (ZALGoalStatusChanges), making sure that suspended goals can be correctly transitioned back.
Without first running the migration and with the recent production snapshot, e.g. one from 2/21/25 available in keybase:
- impersonate the user mentioned in the JIRA
- navigate to the RTR and look for goal 94772
- note that the goal cannot be moved to "Not Started"
- run the migration
- verify that the goal can now be moved to "In Progress", it's previous status.
* https://jira.acf.gov/browse/TTAHUB-3925
- [n/a] Meets …
> [TTAHUB-3925] Restore previous status for suspended goals

- .circleci/config.yml
- frontend/src/components/CommunicationLog/pages/log.js
- frontend/src/pages/RecipientRecord/pages/CommunicationLogForm/__tests__/index.js
- frontend/src/pages/RegionalCommunicationLog/__tests__/index.js
Adds help drawers for the "purpose" and "results" form fields to the communication log form (regional and RTR).
Open the drawer and make sure the content loads correctly.
https://github.com/user-attachments/assets/ada5151f-06bd-4b91-925e-b68c3da020d1
* https://jira.acf.gov/browse/TTAHUB-3788
> [TTAHUB-3788] Communication log form drawers

- src/services/similarity.js
- src/services/similarity.test.js
If the API key environment variable that we use to authenticate to the similarity API is not defined correctly, then authentication to the API will fail. If authentication fails, then the request would return non-valid JSON, and the `return await response.json()` will throw the error mentioned in TTAHUB-3615.
If we assume that we have correctly defined the API key in cloud.gov, then we just need to check the response status before attempting to parse it as JSON. That's what this PR does.
Make sure the change makes sense.
* https://jira.acf.gov/browse/TTAHUB-3615
> [TTAHUB-3615] Similarity API response failure - unexpected token

- src/routes/activityReports/handlers.js
- src/routes/activityReports/handlers.test.js
- src/services/activityReports.js
- src/services/activityReports.test.js
Soft delete goals and objectives when report is soft deleted
- Create a report, add a goal and objective (create new for both)
- Delete report, confirm goals and objectives are marked as deletedAt in the DB. (Right now, they are simply left hanging)
* https://jira.acf.gov/browse/TTAHUB-3858
> [TTAHUB-3858] Also soft-delete goals and objectives when report deleted

- frontend/src/widgets/BarGraph.js
The smallest value on the QA FEI root cause bar chart was being cutoff. The issue is that if we set the min value for this range to be the smallest value in the set it will never show that value. I have added a small buffer for the start and end of the range.
- Ensure the smallest value in the graph shows a bar
- Check other widgets that use this component make sure we didn't break them
* https://jira.acf.gov/browse/TTAHUB-3838
> [TTAHUB-3838] Buffer the min and max range on the horizontal bar chart

- .circleci/config.yml
- similarity_api/src/application.py
- similarity_api/src/requirements.txt
- similarity_api/src/settings.py
- similarity_api/src/sim/compute.py
Rather than update the flask ap scheduler package that is causing failing deploys, I think we can remove it, since we didn't actually end up leveraging that functionality.
Confirm the similarity API builds and functions on dev (goal nudge, similarity group goals)
> Remove unused sim score cache scheduler functionality

- src/services/recipient.js
- src/services/recipient.test.js
Reverts more changes that happened recently related to how endDate was calculated, restoring things to how they were before.
Go to http://localhost:3000/recipient-tta-records/263/region/11/rttapa?
Search for G63912
Make sure it shows a good value for `Last TTA`.
Before:
After:
Additionally, make sure the issue from a previous (and related) support case is still resolved:
- http://localhost:3000/recipient-tta-records/7683/region/11/rttapa?
- Ensure G95724 still has an endDate of 11/08/2024
* https://jira.acf.gov/browse/TTAHUB-3917
> [TTAHUB-3917] Support case related to endDate calculation

- src/lib/mailer/index.js
- src/lib/mailer/index.test.js
- src/lib/mailer/trainingReportTaskDueNotifications.test.js
- src/services/userSettings.js
- src/services/users.js
- src/services/users.test.js
This PR fixes a bug for the retrieval of the active users. It also ensures that the getUserById() only returns active users for the TR alerts.
- Test e-mail sending for active / inactive user (for a variety of cases).
* https://jira.acf.gov/browse/TTAHUB-3449
> [TTAHUB-3449] Only send e-mails to active users

- frontend/src/pages/RecipientRecord/pages/CommunicationLog.js
- frontend/src/pages/RecipientRecord/pages/__tests__/CommunicationLog.js
- frontend/src/pages/RegionalCommunicationLogDashboard/components/RegionalCommLogTable.js
Fix this:
View the comm log table with the "Program specialist or regional office" purpose and confirm that it doesn't overflow into the next cell 
> Fix overflowing table cells in comm log

- .circleci/config.yml
This change temporarily disables the restore of the processed database to staging to allow for penetration testing setup and execution.
Look at the change. This will be tested once merged.
* https://jira.acf.gov/browse/TTAHUB-3967
> [TTAHUB-3967] Temporarily disable restoring processed database to staging.

- src/goalServices/getGoalsForReport.ts
- src/goalServices/reduceGoals.test.ts
- src/goalServices/reduceGoals.ts
Addresses the errors in production related to the relation being undefined.
Look at the code; make sure the tests pass
On main branch:
- restore any recent production backup. e.g. the one on 2/21/25 from Keybase or newer
- filter for report 51003
- observe that clicking on that report generates the error and that the goals are not loaded
- switch to this branch
- confirm that error is no longer happening and the goals section is visible
* https://jira.acf.gov/browse/TTAHUB-3938
- [n/a] QA review …
> [TTAHUB-3938] Prevent accessing non existent relation

- src/middleware/canWriteReportsInRegionMiddleware.js
- src/middleware/canWriteReportsInRegionMiddleware.test.js
- src/routes/goalTemplates/handlers.test.js
- src/routes/goalTemplates/handlers.ts
- src/routes/goalTemplates/index.js
- src/services/standardGoal.test.js
- src/services/standardGoals.ts
This is the new backend route that fetches data for the RTTAPA page. It is a partial rewrite of the existing function, streamlined to not rely on JavaScript. Note that I have changed the field names and data structure of what will be the goal cards, so when we attach it to a frontend, we will have to rework how the data is accessed.
Confirm that all fields required by the design are present, that the test makes sense, and that the logic for fetching the goals is correct.
* https://jira.acf.gov/browse/TTAHUB-3960
> [TTAHUB-3960] Standard goals: new backend route for goal cards/RTTAPA page

- frontend/src/Routes.js
- frontend/src/components/SiteNav.js
We're releasing the communication log globally, so the feature flag guards can be removed.
> [NO-TICKET] Remove commlog feature flag guards for release

- src/models/hooks/sessionReportPilot.js
- src/models/hooks/sessionReportPilot.test.js
The condition in the afterUpdate hook was a bit strange, and it has been improved.
Tests were added to validate expected behavior, but...
- Get a processed data dump
- Try to submit the session in the linked issue
- Ensure it is marked 'Complete'
- Also, ensure you can still mark not-previously-submitted sessions as 'Complete'
* https://jira.acf.gov/browse/TTAHUB-3996
> [TTAHUB-3996] Support case: session cannot be marked complete

- .circleci/config.yml
Current db restore is failing due to a timeout of 15 minutes.
This appears to have been an arbitrary choice, so I am increasing the timeout to 30 min.
Example run here:
https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/27435/workflows/6ad7232e-9675-43a0-aaed-c4a0d544c4a3/jobs/156439?invite=true#step-110-1142917_80
This job only runs against the prod branch, so it's not easily testable, but the change is a one-liner increase to a static value
> increase db restore timeout

- package.json
- yarn.lock
Noticed in the New Relic APM dashboard that our version is significantly behind and recommended to upgrade.
* Updated package.json
* Ran `yarn install --mode update-lockfile`
* Ran `yarn deps`, `yarn build`, spun up local docker and verified everything came up ok
Build & deploy, verify APM data is still being ingested.
> [NO-TICKET] Bump New Relic version

- README.md
Update the README to include information on connecting to redis, along with some other helpful, related commands.
Tested in dev, sandbox, prod.
```
cf connect-to-service tta-smarthub-dev ttahub-redis-dev
Finding the service instance details...
Setting up SSH tunnel...
SSH tunnel created.
Connecting client...
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:49977> PING
PONG
```
> [TTAHUB-646] Add redis connect info to README

- src/tools/createMonitoringGoals.js
- src/tools/createMonitoringGoals.test.js
Disabling auto-close of monitoring goals.
* https://jira.acf.gov/browse/TTAHUB-4049
> Disabling auto-close of monitoring goals

- src/migrations/20250421000000-delete-dupe-objective.js
A user who wanted to correct the title of an Objective on a Goal ended up creating a (near) duplicate instead, but they don't currently have a way to remove the extra Objective. This PR is for removing the extra.
Before this should get back one Objective, and after zero:
`SELECT COUNT(*) FROM "Objectives" WHERE "deletedAt" IS NULL AND title = 'TTA Specialists will provide foundational information on the Head Start Director role and responsibilities that include leadership development; systems to support program planning and staffing supports; program governance; and the five-year grant application process.';`
* https://jira.acf.gov/browse/TTAHUB-4077
> [TTAHUB-4077] Delete unwanted objective

- frontend/src/components/GoalCards/GoalCard.js
- frontend/src/components/GoalCards/__tests__/GoalCard.js
- frontend/src/pages/RecipientRecord/pages/Monitoring/components/SpecialistTags.js
- When the creator has a single role, there is a single "Entered by" tag for that role.
- When the creator has multiple roles, there is an "Entered by" tag for each role.
- When the creator has no roles, there is a single "Unavailable" tag.
- Visit the RTR
- Validate the tests
- Add/remove roles for yourself to test behavior
* https://jira.acf.gov/browse/TTAHUB-3422
> [TTAHUB-3422] Update display of "Entered by" value on goal card

- .circleci/config.yml
All automated db restore jobs use the '`ta-automation` "app" for running tasks, and only a single instance of the app can be deployed at a time.  I had attempted to split the locking on a per-environment basis, but this results in the tasks failing to run due to the fact that only one can be in the "staging" state at a time in cloud foundry.
Therefore, use the same lock for all jobs.  This resolves the error [which can be seen here](https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/28548/workflows/a5f2e73b-2a50-4ded-ab4d-4012e4691946/jobs/163091):
Ran the manual db restore job, however the only way to really test is via the cron itself.
https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/28596/workflows/117e72cc-910a-46c3-9f2f-d87894b2cda1
N/A
> [NO-TICKET] Use the same lock for all db-restore jobs

- docs/it-ams-monitoring-data.md
- src/services/citations.test.js
- src/services/citations.ts
We have been relying on the time gap between when TTA is provided addressing a Finding/citation and when the final follow-up review closes to ensure that the AR has already been written and approved, but while the latest fix was working its way through, at least one user has gotten outside that window. This expands the logic so that as long as the `reportDeliveryDate` of the latest review is after the start date of the AR, the citation can still be selected. 
This actually impacts the same user as https://github.com/HHS/Head-Start-TTADP/pull/2777 if you update to May data.
* https://jira.acf.gov/browse/TTAHUB-4064
> [TTAHUB-4064] allow citations on reviews that close after AR startDate

- README.md
- package.json
Reverting change from https://github.com/HHS/Head-Start-TTADP/pull/2796 merged earlier today.
This will need to go through further compliance review.
> Revert "[TTAHUB-4072] Enable node inspector in deployed environments"

- src/widgets/overview.js
We were counting recipients with multiple regions as separate recipients in the numerator but not denominator of the dashboard overview widget. This brings the calculations in line.
Check the main tta dashboard with "program types" as a filter while able to see all regions and see that the number remains below 100%.
> [TTAHUB-4013] only count recipients once across regions

- src/services/citations.test.js
- src/services/citations.ts
This excludes any findings where the MonitoringFinding and MonitoringFindingHistory records have been deleted at the source, i.e. in IT-AMS.
There's a Finding/citation ANC marked deleted at https://tta-smarthub-staging.app.cloud.gov/recipient-tta-records/1027/region/5/monitoring/review and so there should only be one non-compliance citation showing instead of 2.
* https://jira.acf.gov/browse/TTAHUB-4197
> [TTAHUB-4197] do not return findings/citations deleted at source

- automation/configs/process.yml
- automation/configs/processed-backup.yml
- automation/configs/processed-restore.yml
- automation/configs/processed-retention.yml
- automation/configs/production-backup.yml
- automation/configs/production-restore.yml
- automation/configs/production-retention.yml
* Increases allocated memory for db backup/restore automation jobs from 512 MB to 1GB.  This is intended to address recent failures seen due to OOM while these jobs are running, presumably due to the underlying database increasing in size.  Given that these jobs run in ~5-10 minutes at low-traffic times, the overall impact of increased allocated memory on account total should be minimal.
Successful run against dev:
https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/29498/workflows/f8df79d9-0ffe-45ed-b5df-357d9e757ee3
> more db restore memory

- src/services/activityReports.js
- src/services/activityReports.test.js
Change the availability of expired grants from 61 days to 90
You should be able to select the older replaced Grant for the Recipient at https://tta-smarthub-staging.app.cloud.gov/recipient-tta-records/1671/region/2/profile on an AR, then select a citation in it.
Turcotte LLC as of Jul 3
* https://jira.acf.gov/browse/TTAHUB-4301
> extend inactive Grant availability to 90 days

- docs/it-ams-monitoring-data.md
- docs/monitoring-tech.md
- src/services/citations.ts
- src/tools/createMonitoringGoals.js
IT-AMS started using "Elevated Deficiency" as a status for Findings that should be treated as equivalent to "Active"
Recipient 6301 (Caldwell Parish on prod) should show selectable citations. Use this link to easily find them:
https://tta-smarthub-staging.app.cloud.gov/recipient-tta-records/6301/region/6/profile
* https://jira.acf.gov/browse/TTAHUB-4330
> [TTAHUB-4330]Treat "Elevated Deficiency" as Active status for Findings

- .circleci/config.yml
zap "stable" docker repo no longer has a `latest` tag.
* there are two versions of this repo, [stable](https://hub.docker.com/r/softwaresecurityproject/zap-stable/tags) and [bare](https://hub.docker.com/r/softwaresecurityproject/zap-bare/tags).
* the `latest` tag only exists in the `bare` repo, so I have opted to use the latest explicit version from the stable repo.
Successful run:
https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/30293/workflows/1e45b254-a936-48c6-aa71-1d4f5be478e7
* N/A
> [NO-TICKET] fix zap image tag

- .circleci/config.yml
* After each deploy to cloud.gov, DB migrations are run via a cf "task" that executes in the application space.
* This task was always targeting "dev", when it should have been targeting "dev-green", "dev-blue", etc.
* This would have only happened when the space name doesn't match the app name, so staging and prod were unaffected. 
Run a deploy targeting dev environment, verify the correct app/env is being targeted for migrations via log inspection
Before this fix:
`cf run-task ************-dev --command 'yarn db:migrate:prod' --name 'deploy_(dev-pink)`
After:
`cf run-task ************-dev-pink --command 'yarn db:migrate:prod' --name 'deploy_(dev-pink)`
https://app.circleci.com/pipelines/github/HHS/Head-Start-TTADP/30442/workflows/c865d067-5409-4614-8831-4b2e98a011b6/jobs/181429
N/A
- …
> [NO-TICKET] Fix migrations being run against incorrect dev environment

- README.md
- bin/replica-connect.sh
* This is a workaround script for connecting to a replica DB in cloud.gov.  We currently have a replica running in prod and in dev-pink
* The usual `connect-to-service` plugin does not work for replica databases unfortunately, so I have created something equivalent.  This script gets the db info via VCAP_SERVICES on the app host, sets up an SSH tunnel through host in a background process, then starts a psql connection to this given address.  
* It will catch exit signals to the main process and attempt to close the SSH tunnel.  I have validated this works in a variety of cases myself, but just in case it doesn't it will a) print the PID of the tunnel process when created b) cleanup any previous zombie processes it finds on startup
* We still need more for TTAHUB-4371, but this is an …
> [TTAHUB-4371] Add script for connecting to replica DB

- frontend/src/components/GoalCards/StandardGoalCard.js
- frontend/src/components/GoalCards/__tests__/StandardGoalCard.js
- src/services/standardGoals.ts
Confirm that the monitoring goals display on the RTR, show the little red flag, and the correct "OHS" label with the "system-generated" tooltip.
* https://jira.acf.gov/browse/TTAHUB-4384
> Monitoring goals should show flag and "system-generated" message

- frontend/src/components/SharedGoalComponents/constants.js
- frontend/src/pages/StandardGoalForm/__tests__/RestartStandardGoal.js
Updated the text to say 'Reopen goal' instead of 'Restart goal'.
- Review code
- Make sure the button shows correctly.
* https://jira.acf.gov/browse/TTAHUB-4382
> [TTAHUB-4382] Change restart goal button text

- src/migrations/20250901000000-close_prestandard_goals_etc.js
Merged goals are not necessarily closed in the process of being merged, meaning that there is a crop of effectively duplicate goals that causes problems for constraints we want to apply in the standard Goal era. This makes it so those merged-away goals also get Closed 
This should allow the follow-on migration to apply successfully.
* https://jira.acf.gov/browse/TTAHUB-4308
* https://jira.acf.gov/browse/TTAHUB-4005
> [TTAHUB-4308]close all merged goals

- .circleci/config.yml
Noticed that CircleCI released a new feature: auto-retries.  Due to the fact that our backend tests are still somewhat flaky, I have enabled 3 automatic retries on this job and the db restore job.  This will function the same as "retry from failed" behavior, which is what we would usually click when the normal build_test_deploy job.
Reference:
https://circleci.com/changelog/automatic-retry-of-workflows-released/
Validated job runs as normal, and that jobs will retry as expected.
N/A
> [NO-TICKET] Auto-retry CircleCI from failed step 3x

- frontend/src/widgets/FrequencyGraph.js
- frontend/src/widgets/__tests__/FrequencyGraph.js
- src/widgets/frequencyGraph.js
- src/widgets/frequencyGraph.test.js
- src/widgets/totalHrsAndRecipientGraph.test.js
- tests/api/widgets.spec.ts
This ticket is simply the removal of the reasons widget from the TTA History (we only show topics now).
- Make sure the topics widget still works and we don't allow the reasons widget to be displayed.
* https://jira.acf.gov/browse/TTAHUB-4114
> [TTAHUB-4114] Remove reason from TTA History

- src/services/activityReports.js
This fixes a bug that was coming up in new relic when viewing a legacy OE report.
- Review the change.
- View a legacy OE report and ensure there are no 500 errors.
> [BUG] Null reference when accessing recipient grant for OE report

- frontend/src/Constants.js
- frontend/src/__tests__/localStorageCleanup.js
- frontend/src/hooks/useLocalStorageCleanup.js
- frontend/src/pages/CollaborationReportForm/formDataHelpers.js
- frontend/src/pages/CollaborationReportForm/index.js
Two bugs. One: backend not handling invalid start/end dates and Two: local storage not being cleaned up properly
To repro in staging,
1. Save a collab report with no fields filled out
2. DB error for start/end date being invalid on create
3. Fill out start and end date, the report will save
4. Return to collab report landing, click new report
5. Save again after filling out start and end date. Another DB error, this time because the ID was submitted
> Fix typo in local storage hook + collab report dates

- frontend/src/pages/CollaborationReportForm/Pages/components/Review.js
- frontend/src/pages/CollaborationReportForm/Pages/components/__tests__/Review.js
- src/services/collabReports.ts
Two bugs on collab report: 
1. If an creator is also an approver, saves draft without submitting, the creator/approver is presented with an approval status select and is unable to submit. 
2. Revise the getAlerts query for collab reports so that approvers only see submitted reports
Confirm that the cases above are fixed
> Fix approver not submitted view on collab report

- .circleci/config.yml
add tta-automation to the list of envs for cache clear.  tta-automation is a dedicated environment for running tasks like backing up the db and processing the db files
one line change, other envs work, validated locally
> [NO-TICKET] add tta-automation to the list of envs for cache clear
